### ISSUE TITLE
【Bug】腾讯云函数定时运行失败

### ISSUE THREAD

**Issue by wanlongsj** [RayWangQvQ/BiliBiliToolPro#11]
版本号：（v0.0.1）
运行环境：（腾讯云函数自动运行,Actions,Win）

问题描述：（腾讯云函数其他都能启动唯独定时触发异常）

日志信息：（<html>
<body>

异常：System.Collections.Generic.KeyNotFoundException: The given key ',' was not present in the dictionary.
--
at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 135
at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65

</body>
</html>）

**Comment by wanlongsj** [comment]
我真眼瞎....
