### ISSUE TITLE
群辉docker+青龙 Couldn't find a valid ICU package 

### ISSUE THREAD

**Issue by Unicorni** [RayWangQvQ/BiliBiliToolPro#115]
青龙v2.12.1

总是运行不起来。那个运行环境装了，用命令行装的。
docker exec -it qinglong bash /ql/config/extra.sh
成功了
但是总是运行不起来，有什么解决方法吗？帮帮我，救命
日志-bili天选时刻
## 开始执行... 2022-04-16 18:37:22

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/raywangqvq_bilibilitoolpro

Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
bili_task_liveLottery.sh: line 15: 19235 Aborted                 dotnet run --project ./src/Ray.BiliBiliTool.Console --ENVIRONMENT=Production --runTasks=LiveLottery

## 执行结束... 2022-04-16 18:37:49 耗时 27 秒

**Comment by RayWangQvQ** [comment]
`docker exec -it qinglong bash /ql/config/extra.sh`的日志不贴下吗？

**Comment by wfmm-sky** [comment]
我跟你遇到的一模一样，好像是青龙的版本太高了，前一阵子我可以正常挂，某次更新完就是这样了

**Comment by RayWangQvQ** [comment]
已解决：#266
