### ISSUE TITLE
【Bug】云函数 手动测试时任务可以正常加载，但自动触发时无法加载任务

### ISSUE THREAD

**Issue by jiucai39** [RayWangQvQ/BiliBiliToolPro#121]
以下为日志
START RequestId: f4fd4e8b-5f7f-4100-b9ef-6ef15f65fc92
=>监听到事件：{"Message":"Daily","Time":"2022-04-19T07:40:00Z","TriggerName":"DailyTask","Type":"Timer"}
=>调用函数,开始处理事件
进入main_handler
{"Message":"Daily","Time":"2022-04-19T07:40:00Z","TriggerName":"DailyTask","Type":"Timer"}
触发事件中的附加消息（任务编码）为：Daily
开始运行BiliBiliTool......
Unhandled exception. System.FormatException: The short switch '-runTasks=Daily' is not defined in the switch mappings.
at Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider.Load()
at Microsoft.Extensions.Hosting.HostBuilder.Build()
at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 )
at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 23
at Ray.BiliBiliTool.Console.Program.CreateHost(String[] args) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 41
./index.sh: line 3: 31 Aborted ./Ray.BiliBiliTool.Console $runTasks

**Comment by RayWangQvQ** [comment]
同 #120 ，已经修复了，重新部署下应该就好了

**Comment by jiucai39** [comment]
> 同 #120 ，已经修复了，重新部署下应该就好了
试了一下，好像还是不行呢
