### ISSUE TITLE
您好，请问为啥青龙按照教程拉好库，运行会出错？

### ISSUE THREAD

**Issue by dxmsk** [RayWangQvQ/BiliBiliToolPro#124]
repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/raywangqvq_bilibilitoolpro

Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
bili_task_daily.sh: line 17:   579 Aborted                 (core dumped) dotnet run --project ./src/Ray.BiliBiliTool.Console

## 执行结束... 2022-04-20 10:08:03 耗时 0 秒sue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）

**Comment by RayWangQvQ** [comment]
参考：#266
