### ISSUE TITLE
【Bug】bili库拉取后,其他任务执行时会报日志信息的错误

### ISSUE THREAD

**Issue by bossxiaochuan** [RayWangQvQ/BiliBiliToolPro#125]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
运行环境：LINUX+青龙

问题描述：bili库拉取后,其他任务执行时会报日志信息的错误

日志信息：## 开始执行... 2022-04-21 00:35:43

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/raywangqvq_bilibilitoolpro

Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
bili_task_daily.sh: line 17:   740 Aborted                 (core dumped) dotnet run --project ./src/Ray.BiliBiliTool.Console

**Comment by RayWangQvQ** [comment]
参考：#266
