### ISSUE TITLE
腾讯云函数运行不了

### ISSUE THREAD

**Issue by Testplayers** [RayWangQvQ/BiliBiliToolPro#150]
START RequestId: 37379eb1-cd15-4159-968a-3e19a755aabb

=>监听到事件：{"key1":"test value 1","key2":"test value 2"}

=>调用函数,开始处理事件

进入main_handler

{"key1":"test value 1","key2":"test value 2"}

触发事件中未包含附加消息（任务编码）

开始运行BiliBiliTool......

[09:21:13 INF] BiliBiliToolPro 开始运行...

2022-05-07T09:21:13.2877737Z File target /var/user/Logs/log20220507.txt was locked, attempting to open next in sequence (attempt 1)

2022-05-07T09:21:13.2973597Z File target /var/user/Logs/log20220507_001.txt was locked, attempting to open next in sequence (attempt 2)

2022-05-07T09:21:13.2975001Z File target /var/user/Logs/log20220507_002.txt was locked, attempting to open next in sequence (attempt 3)

[09:21:13 INF] 【目标任务】Daily

[09:21:13 INF] 【账号个数】2个

[09:21:13 INF] 随机休眠18分钟

[09:39:13 INF] ######### 账号 1 #########

[09:39:13 WRN] 异常：System.FormatException: The format of value 'Mozilla/5.0(WindowsNT10.0;Win64;x64)AppleWebKit/537.36(KHTML,likeGecko)Chrome/100.0.4896.75Safari/537.36Edg/100.0.1185.36' is invalid.

   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String , Object , Int32& )

   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor , HeaderStoreItemInfo , String )

   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor , String )

   at System.Net.Http.Headers.HttpHeaders.Add(String , String )

   at Ray.BiliBiliTool.Agent.Extensions.ServiceCollectionExtension.<>c__1`1.<AddBiliBiliClientApi>b__1_1(IServiceProvider sp, HttpClient c) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/Extensions/ServiceCollectionExtension.cs:line 92

   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass1_1.<ConfigureHttpClient>b__2(HttpClient )

   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String )

   at Microsoft.Extensions.DependencyInjection.HttpApiExtensions.HttpApiProvider`1.CreateHttpApi(IServiceProvider serviceProvider, String name)

   at Microsoft.Extensions.DependencyInjection.HttpApiExtensions.<>c__DisplayClass0_0`1.<AddHttpApi>b__0(IServiceProvider serviceProvider)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope )

   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type )

   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )

   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 145

   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 67

[09:39:13 INF] ######### 账号 2 #########

[09:39:13 WRN] 异常：System.FormatException: The format of value 'Mozilla/5.0(WindowsNT10.0;Win64;x64)AppleWebKit/537.36(KHTML,likeGecko)Chrome/100.0.4896.75Safari/537.36Edg/100.0.1185.36' is invalid.

   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String , Object , Int32& )

   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor , HeaderStoreItemInfo , String )

   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor , String )

   at System.Net.Http.Headers.HttpHeaders.Add(String , String )

   at Ray.BiliBiliTool.Agent.Extensions.ServiceCollectionExtension.<>c__1`1.<AddBiliBiliClientApi>b__1_1(IServiceProvider sp, HttpClient c) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/Extensions/ServiceCollectionExtension.cs:line 92

   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass1_1.<ConfigureHttpClient>b__2(HttpClient )

   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String )

   at Microsoft.Extensions.DependencyInjection.HttpApiExtensions.HttpApiProvider`1.CreateHttpApi(IServiceProvider serviceProvider, String name)

   at Microsoft.Extensions.DependencyInjection.HttpApiExtensions.<>c__DisplayClass0_0`1.<AddHttpApi>b__0(IServiceProvider serviceProvider)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite , RuntimeResolverContext )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite , TArgument )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope )

   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type )

   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )

   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 145

   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 67

[09:39:13 INF] 运行结束

函数结束

=>返回 {"key1":"test value 1","key2":"test value 2"}

=>推送函数处理结果

Response RequestId: 37379eb1-cd15-4159-968a-3e19a755aabb RetMsg: {"key1":"test value 1","key2":"test value 2"}

END RequestId: 37379eb1-cd15-4159-968a-3e19a755aabb

Report RequestId: 37379eb1-cd15-4159-968a-3e19a755aabb Duration: 1081473ms Memory: 128MB MemUsage: 33.08MB

=>长轮询获取事件

**Comment by RayWangQvQ** [comment]
`UserAgent`配置的不对，改下试试

**Comment by Testplayers** [comment]
好的，谢谢
