### ISSUE TITLE
【Bug】用云函数定时运行出现了这个问题

### ISSUE THREAD

**Issue by luv1029** [RayWangQvQ/BiliBiliToolPro#157]
版本：V0.1.0
运行环境：云函数
问题：云函数定时运行提示这样

[03:17:01 WRN] 异常：System.Collections.Generic.KeyNotFoundException: The given key ',' was not present in the dictionary.

   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 146

   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 67

[03:17:01 INF] 运行结束

函数结束

=>返回 {"Message":"","Time":"2022-05-15T03:17:00Z","TriggerName":"SCF-timer-1652584504","Type":"Timer"}

=>推送函数处理结果

Response RequestId: 1326b747-f247-4731-8f73-2be1f38ee523 RetMsg: {"Message":"","Time":"2022-05-15T03:17:00Z","TriggerName":"SCF-timer-1652584504","Type":"Timer"}

END RequestId: 1326b747-f247-4731-8f73-2be1f38ee523

Report RequestId: 1326b747-f247-4731-8f73-2be1f38ee523 Duration: 1388ms Memory: 128MB MemUsage: 24.84MB

=>长轮询获取事件

**Comment by hahashifeng** [comment]
同样的问题，测试没问题，但是定时就会这样
