### ISSUE TITLE
青龙面板安装的时候一直提示缺少libicu

### ISSUE THREAD

**Issue by hahashifeng** [RayWangQvQ/BiliBiliToolPro#159]
## 开始执行... 2022-05-17 16:37:13

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/raywangqvq_bilibilitoolpro

Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
bili_task_daily.sh: line 17:  1160 Aborted                 (core dumped) dotnet run --project ./src/Ray.BiliBiliTool.Console

## 执行结束... 2022-05-17 16:37:13 耗时 0 秒

**Comment by llKIMZll** [comment]
同问

**Comment by funxiaop** [comment]
同求解决方法

**Comment by RayWangQvQ** [comment]
已解决：#266
