### ISSUE TITLE
随机休眠完自动闪退

### ISSUE THREAD

**Issue by lzyr9010** [RayWangQvQ/BiliBiliToolPro#161]
版本号：[BiliBiliToolPro-V0.1.0](https://github.com/RayWangQvQ/BiliBiliToolPro/releases/tag/0.1.0)
运行环境：[bilibili-tool-pro-v0.1.0-win-x86-x64.zip](https://github.com/RayWangQvQ/BiliBiliToolPro/releases/download/0.1.0/bilibili-tool-pro-v0.1.0-win-x86-x64.zip)

问题描述：随机休眠完自动闪退
日志信息：（2022-05-18 14:54:12.585 +08:00 [INF] BiliBiliToolPro 开始运行...

2022-05-18 14:54:12.723 +08:00 [INF] 【目标任务】Daily,LiveLottery,UnfollowBatched,Test
2022-05-18 14:54:12.727 +08:00 [INF] 【账号个数】1个

2022-05-18 14:54:12.731 +08:00 [INF] 随机休眠1分钟

2022-05-18 14:55:12.733 +08:00 [INF] ========= 账号 1 =========

2022-05-18 14:55:12.803 +08:00 [WRN] 异常：System.Collections.Generic.KeyNotFoundException: The given key 'Daily,LiveLottery,UnfollowBatched,Test' was not present in the dictionary.
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 146
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 67
2022-05-18 14:55:12.805 +08:00 [INF] 运行结束
）

**Comment by lzyr9010** [comment]
[](url
[log20220518.txt](https://github.com/RayWangQvQ/BiliBiliToolPro/files/8713896/log20220518.txt)
)
