### ISSUE TITLE
【Bug】docker部署的也报错了

### ISSUE THREAD

**Issue by y785201595** [RayWangQvQ/BiliBiliToolPro#206]
root@8b5cac33a9b6:/app# dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=Dail                                                                                                                              y
[14:59:10 INF] BiliBiliToolPro 开始运行...

[14:59:10 INF] 【目标任务】Daily
[14:59:10 INF] 【账号个数】1个

[14:59:10 INF] 随机休眠1分钟

[15:00:10 INF] ######### 账号 1 #########

[15:00:10 INF] =====开始 每日任务 =====

[15:00:10 INF] ---开始 登录 ---
[15:00:28 ERR] [REQUEST]
GET /x/web-interface/nav HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, applicatio                                                                                                                              n/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[EXCEPTION]
System.Net.Http.HttpRequestException: Request headers must contain only ASCII ch                                                                                                                              aracters.
   at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async)
   at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async, E                                                                                                                              ncoding encoding)
   at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, Stri                                                                                                                              ng cookiesFromContainer, Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, B                                                                                                                              oolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, B                                                                                                                              oolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(H                                                                                                                              ttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationTok                                                                                                                              en cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Bool                                                                                                                              ean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(Http                                                                                                                              RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpReque                                                                                                                              stMessage request, Context context, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, C                                                                                                                              ontext context, CancellationToken cancellationToken, ExceptionPredicates shouldR                                                                                                                              etryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5                                                                                                                               onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable,                                                                                                                               Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, Cancellat                                                                                                                              ionToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMe                                                                                                                              ssage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHand                                                                                                                              ler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) i                                                                                                                              n /code/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegati                                                                                                                              ngHandler.cs:line 30
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync                                                                                                                              (HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage requ                                                                                                                              est, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean                                                                                                                               disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken origi                                                                                                                              nalCancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequest                                                                                                                              Context context)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestCont                                                                                                                              ext context)

[ELAPSED] 00:00:17.7358136
[15:00:28 ERR] 程序发生异常：Request headers must contain only ASCII characters.
[15:00:28 ERR] 程序发生异常：Request headers must contain only ASCII characters.
[15:00:28 WRN] 异常：System.Net.Http.HttpRequestException: Request headers must                                                                                                                               contain only ASCII characters.
   at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async)
   at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async, E                                                                                                                              ncoding encoding)
   at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, Stri                                                                                                                              ng cookiesFromContainer, Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, B                                                                                                                              oolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, B                                                                                                                              oolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(H                                                                                                                              ttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationTok                                                                                                                              en cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Bool                                                                                                                              ean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(Http                                                                                                                              RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpReque                                                                                                                              stMessage request, Context context, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, C                                                                                                                              ontext context, CancellationToken cancellationToken, ExceptionPredicates shouldR                                                                                                                              etryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5                                                                                                                               onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable,                                                                                                                               Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, Cancellat                                                                                                                              ionToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMe                                                                                                                              ssage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHand                                                                                                                              ler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) i                                                                                                                              n /code/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegati                                                                                                                              ngHandler.cs:line 30
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync                                                                                                                              (HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage requ                                                                                                                              est, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean                                                                                                                               disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken origi                                                                                                                              nalCancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequest                                                                                                                              Context context)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestCont                                                                                                                              ext context)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(Api                                                                                                                              RequestContext request)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(Htt                                                                                                                              pClientContext context, Object[] arguments)
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /co                                                                                                                              de/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 51
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks)                                                                                                                               in /code/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 145
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(Cancellation                                                                                                                              Token cancellationToken) in /code/src/Ray.BiliBiliTool.Console/BiliBiliToolHoste                                                                                                                              dService.cs:line 67
[15:00:28 INF] 运行结束

**Comment by hecarli555** [comment]
> root@8b5cac33a9b6:/app# dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=Dail y [14:59:10 INF] BiliBiliToolPro 开始运行...
> 
> [14:59:10 INF] 【目标任务】Daily [14:59:10 INF] 【账号个数】1个
> 
> [14:59:10 INF] 随机休眠1分钟
> 
> [15:00:10 INF] ######### 账号 1 #########
> 
> [15:00:10 INF] =====开始 每日任务 =====
> 
> [15:00:10 INF] ---开始 登录 --- [15:00:28 ERR] [REQUEST] GET /x/web-interface/nav HTTP/1.1 Referer: https://www.bilibili.com/ Origin: https://www.bilibili.com Host: api.bilibili.com Accept: application/json, text/plain, _/_, application/json; q=0.001, applicatio n/xml; q=0.001 Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6 Sec-Fetch-Dest: empty Sec-Fetch-Mode: cors Sec-Fetch-Site: same-site Connection: keep-alive
> 
> [EXCEPTION] System.Net.Http.HttpRequestException: Request headers must contain only ASCII ch aracters. at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async) at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async, E ncoding encoding) at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, Stri ng cookiesFromContainer, Boolean async) at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, B oolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, B oolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(H ttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationTok en cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Bool ean async, CancellationToken cancellationToken) at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(Http RequestMessage request, CancellationToken cancellationToken) at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpReque stMessage request, Context context, CancellationToken cancellationToken) at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, C ontext context, CancellationToken cancellationToken, ExceptionPredicates shouldR etryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext) at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, Cancellat ionToken cancellationToken, Boolean continueOnCapturedContext) at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMe ssage request, CancellationToken cancellationToken) at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHand ler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) i n /code/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegati ngHandler.cs:line 30 at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync (HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage requ est, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken origi nalCancellationToken) at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequest Context context) at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestCont ext context)
> 
> [ELAPSED] 00:00:17.7358136 [15:00:28 ERR] 程序发生异常：Request headers must contain only ASCII characters. [15:00:28 ERR] 程序发生异常：Request headers must contain only ASCII characters. [15:00:28 WRN] 异常：System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters. at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async) at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async, E ncoding encoding) at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, Stri ng cookiesFromContainer, Boolean async) at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, B oolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, B oolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(H ttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationTok en cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Bool ean async, CancellationToken cancellationToken) at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(Http RequestMessage request, CancellationToken cancellationToken) at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpReque stMessage request, Context context, CancellationToken cancellationToken) at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, C ontext context, CancellationToken cancellationToken, ExceptionPredicates shouldR etryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext) at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, Cancellat ionToken cancellationToken, Boolean continueOnCapturedContext) at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMe ssage request, CancellationToken cancellationToken) at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHand ler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) i n /code/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegati ngHandler.cs:line 30 at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync (HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage requ est, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken origi nalCancellationToken) at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequest Context context) at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestCont ext context) at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(Api RequestContext request) at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(Htt pClientContext context, Object[] arguments) at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /co de/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 51 at Ray.BiliBiliTool.Application.DailyTaskAppService.Login() at Ray.BiliBiliTool.Application.DailyTaskAppService.DoTask() at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /code/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 145 at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(Cancellation Token cancellationToken) in /code/src/Ray.BiliBiliTool.Console/BiliBiliToolHoste dService.cs:line 67 [15:00:28 INF] 运行结束

请问大佬，群晖的docker部署的话，指令是怎么写的？

**Comment by RayWangQvQ** [comment]
cookie配置值不正确

**Comment by y785201595** [comment]
发现了问题是因为谷歌浏览器的问题。cookie中有些字符会balh_server_inner=__custom__; balh_is_closed=; balh_server_custom_tw=https://å“”å“©.plus; balh_server_custom_hk=**https://å“”å**“©.plus; balh_server_custom_th=https://å“”å“©.plus; balh_server_custom=https://å“”å“©.plus; innersign=0;
这样显示，后面换用Microsoft Edge浏览器恢复正常

**Comment by y785201595** [comment]
估计是什么鬼插件搞的
