### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by i2stay** [RayWangQvQ/BiliBiliToolPro#215]
大佬，这个报错怎么解决
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
bili_task_daily.sh: line 17: 23767 Aborted                 (core dumped) dotnet run --project ./src/Ray.BiliBiliTool.Console

**Comment by RayWangQvQ** [comment]
dotnet环境没有装好，按文档从头开始再试下

**Comment by RayWangQvQ** [comment]
已解决：#266
