### ISSUE TITLE
【Bug】腾讯云函数多账号cookie异常

### ISSUE THREAD

**Issue by TdlicheZ** [RayWangQvQ/BiliBiliToolPro#220]
版本号：0.1.1
运行环境：腾讯云函数，win

问题描述：腾讯云函数-函数配置-环境变量-Ray_BiliBiliCookies__1、2，在同一台电脑上使用chrome打开b站登录账号并获取两个账号的cookie后，腾讯云函数测试时无法同时完成两个账号的dailytask。在重新获取异常账号2的cookie后，账号2可以正常运行，但原先可以运行的账号1的cookie又异常且出现与之前账号2同样的情况。总的来说就是两个账号无法同时运行，新获取cookie的账号可以正常运行，但前一个账号就会异常。

日志信息：
[02:55:36 INF] ========= 账号 2 =========

[02:55:36 INF] =====开始 每日任务 =====

[02:55:36 INF] ---开始 登录 ---

[02:55:49 WRN] 登录异常，请检查Cookie是否错误或过期

[02:55:49 ERR] 程序发生异常：登录失败，请检查Cookie

[02:55:49 ERR] 程序发生异常：登录失败，请检查Cookie

[02:55:49 WRN] 异常：System.Exception: 登录失败，请检查Cookie

   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()

   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoTask()

   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 147

   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 67

[02:55:49 INF] 运行结束

函数结束

**Comment by KudouRan** [comment]
issues 重复 #186
