### ISSUE TITLE
进行日常任务时发生错误：账号异常无法分享

### ISSUE THREAD

**Issue by 26560** [RayWangQvQ/BiliBiliToolPro#228]
![image](https://user-images.githubusercontent.com/107015987/180200303-7735fb31-9b9c-4ceb-8aba-64457d4eb034.png)
应该是此账号的问题，测试小号分享成功。
但是我无法找到账号异常的原因，尝试重置cookie也无法解决问题。
望大佬帮个忙看看问题所在？

**Comment by layui0320** [comment]
在b站软件上测试是否正常分享，然后问b站客服账号状态。

**Comment by RayWangQvQ** [comment]
从日志看没看出啥问题...

**Comment by huagjichen** [comment]
我也是一直分享失败，但是用客户端分享没问题

**Comment by zhougjstudy** [comment]
我也是还出现了一些异常
## 开始执行... 2023-01-06 09:00:00


repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

[09:00:06 INF] BiliBiliToolPro 开始运行...

[09:00:06 INF] 【目标任务】Daily
[09:00:06 INF] 【账号个数】1个

[09:00:06 INF] ######### 账号 1 #########

[09:00:06 INF] =====开始 每日任务 =====

[09:00:06 INF] ---开始 登录 ---
[09:00:11 INF] 【用户名】夜xx中的
[09:00:11 INF] 【会员类型】月度大会员
[09:00:11 INF] 【会员状态】无/过期
[09:00:11 INF] 【硬币余额】641
[09:00:11 INF] 【距升级Lv6】141天（如每日做满65点经验）
[09:00:11 INF] 登录成功，经验+5 √
[09:00:11 INF] -----结束-----

[09:00:17 INF] ---开始 观看、分享视频 ---
[09:00:31 INF] 【随机视频】【符文之地传说】新英雄 加里奥 初登场（中英日韩俄西）
[09:00:31 INF] 今天已经观看过了，不需要再看啦
[09:00:45 ERR] 视频分享失败，原因: 账号异常,操作失败
[09:00:45 INF] ----------结束----------

[09:00:45 INF] ---开始 投币 ---
[09:00:52 INF] 【今日已投】0枚
[09:00:52 INF] 【目标欲投】5枚
[09:00:52 INF] 【还需再投】5枚
[09:00:59 INF] 【投币前余额】 : 641
[09:01:28 INF] 【视频】数据结构与算法(合集)
[09:01:31 INF] 投币成功，经验+10 √
[09:01:39 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:01:50 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:02:10 INF] 【视频】用八宝粥罐子开锁
[09:02:16 INF] 投币成功，经验+10 √
[09:02:25 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:02:34 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:02:50 INF] 【视频】阅片无数但是最后一期【阅片无数Ⅱ 71】
[09:02:57 INF] 投币成功，经验+10 √
[09:03:03 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:03:11 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:03:32 INF] 【视频】哔哩哔哩年度大冤种 做了两年视频没赚一分钱
[09:03:38 INF] 投币成功，经验+10 √
[09:03:49 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:04:01 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:04:15 INF] 【视频】小火车查尔斯 #3 结局，查尔斯超进化！我遇到了水怪！
[09:04:18 INF] 投币成功，经验+10 √
[09:04:18 INF] 投币任务完成
[09:04:26 INF] 【硬币余额】636
[09:04:26 INF] -----结束-----

[09:04:26 INF] ---开始 直播签到 ---
[09:04:31 INF] 【签到结果】成功
[09:04:31 INF] 【本次获取】3000点用户经验,2根辣条,再签到3天可以获得666银瓜子
[09:04:31 INF] -------结束-------

[09:04:31 INF] ---开始 漫画签到 ---
[09:04:36 INF] 【签到结果】成功
[09:04:36 INF] -------结束-------

[09:04:36 INF] ---开始 漫画阅读 ---
[09:04:41 INF] 【漫画阅读】成功, 阅读漫画为：堀与宫村
[09:04:41 INF] -------结束-------

[09:04:41 INF] ---开始 银瓜子兑换硬币 ---
[09:04:41 INF] 已配置为关闭，跳过
[09:04:41 INF] ----------结束----------

[09:04:41 INF] ---开始 领取大会员福利 ---
[09:04:41 INF] 普通会员和月度大会员每月不赠送B币券，不需要领取权益喽
[09:04:41 INF] ----------结束----------

[09:04:41 INF] ---开始 领取大会员漫画权益 ---
[09:04:41 INF] 不是会员，跳过
[09:04:41 INF] ------------结束------------

[09:04:41 INF] ---开始 B币券充电 ---
[09:04:41 INF] 不是年度大会员，跳过
[09:04:41 INF] --------结束--------

[09:04:41 INF] =========结束=========

[09:04:41 INF] 

========================

 v0.3.2 开源 by https://github.com/RayWangQvQ/BiliBiliToolPro

[09:04:41 INF] ·开始推送·Daily任务·
2023-01-06T01:04:41.6134213Z 开始推送到:PushPlus
2023-01-06T01:04:41.7963633Z Response status: OK.
2023-01-06T01:04:41.7964121Z Response content: {"code":200,"msg":"请求成功","data":"a1e2d2769d134abe9853cce256a470fb","count":null}.

[09:04:41 INF] 运行环境：Development
[09:04:41 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[09:04:41 INF] 运行结束


## 执行结束... 2023-01-06 09:04:41  耗时 281 秒

**Comment by RayWangQvQ** [comment]
今天抽空测了下，发现好像跟`cookie`中的`buvid3`有关，待会发一版试一下看能不能修复

**Comment by RayWangQvQ** [comment]
试试`v0.4.6`

**Comment by Remonli** [comment]
似乎是修复了，我下载了新版，运行了两次都没有报错了。

**Comment by zhougjstudy** [comment]
> 试试`v0.4.6`

我不知道为什么分享突然又好了，能够正常分享了。不知道具体原因是什么，0.4.6版本就暂时不测试了。

**Comment by kingsleygithub001** [comment]
0.4.6实测已经可以正常分享
