### ISSUE TITLE
漫画签到异常

### ISSUE THREAD

**Issue by cathuub** [RayWangQvQ/BiliBiliToolPro#24]
下载来试了试，发现漫画签到异常，逐推测是否可能是本号从未进入过哔哩哔哩漫画软件所致。
不知道能否添加多选项可以更细节调控每日具体的任务，比如取消漫画签到。
因为怕长期错误导致b站检测到账号异常封禁······（下附日志内报错结果）
另外也许可以在教程内添加如何获取多个cookie，
正常会想注销然后再登录，但这会导致cookie失效，因此需要手动在浏览器内清除cookie缓存才能登录2个以上账号。

**Comment by cathuub** [comment]
刚刚复现了一下，发现存在多次尝试签到漫画的可能，我明天再试试，排除一下这个可能
——————————————————————————————————————————————————
2022-03-02 23:14:43.422 +08:00 [INF] ---开始 漫画签到 ---
2022-03-02 23:15:03.608 +08:00 [DBG] [REQUEST]
POST /twirp/activity.v1.Activity/ClockIn?platform=android HTTP/1.1
Origin: https://manga.bilibili.com
Host: manga.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 400 Bad Request
Date: Wed, 02 Mar 2022 15:15:04 GMT
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip,x-risk-header
Access-Control-Allow-Methods: GET,POST,OPTIONS
Access-Control-Allow-Origin: https://manga.bilibili.com
X-Trace-Id: 4ba61314bee11567
Cross-Origin-Resource-Policy: cross-origin
Content-Type: application/json
Content-Length: 94

{"code":"invalid_argument","msg":"clockin clockin is duplicate","meta":{"argument":"clockin"}}

[EXCEPTION]
WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：400 Bad Request
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

[ELAPSED] 00:00:20.1543405
2022-03-02 23:15:03.608 +08:00 [INF] 【签到结果】失败
2022-03-02 23:15:03.609 +08:00 [INF] 【原因】今日已签到过，无法重复签到
2022-03-02 23:15:03.610 +08:00 [INF] -------结束-------

**Comment by cathuub** [comment]
看来确实是多次签到的原因······
