### ISSUE TITLE
青龙运行不知道为啥就是这样。搞不懂？

### ISSUE THREAD

**Issue by WjueM** [RayWangQvQ/BiliBiliToolPro#255]
## 开始执行... 2022-08-22 17:02:05

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
bili_task_daily.sh: line 17: 21350 Aborted                 (core dumped) dotnet run --project ./src/Ray.BiliBiliTool.Console

## 执行结束... 2022-08-22 17:02:05 耗时 0 秒

**Comment by WjueM** [comment]
这是什么原因呢？有没有大佬帮忙看看！

**Comment by layui0320** [comment]
没用过青龙，但这里已经给出信息了
`Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.`

可以考虑用docker部署，develop分支已更新docker部署文档

**Comment by lx769021906** [comment]
还是用docker部署吧，青龙直接搞不懂

**Comment by RayWangQvQ** [comment]
DotNet环境没装好，贴下运行extra.sh的日志

**Comment by RayWangQvQ** [comment]
已解决：#266
