### ISSUE TITLE
VipBigPoint运行报错

### ISSUE THREAD

**Issue by franco1013** [RayWangQvQ/BiliBiliToolPro#283]
版本号：最新版
运行环境：docker

问题描述：VipBigPoint运行报错

日志信息：我按照设置将 Ray_Serilog__WriteTo__0__Args__restrictedToMinimumLevel设置成Debug了。出来的就是这个日志，但感觉不像是debug日志

dotnet Ray.BiliBiliTool.Console.dll --runTasks=VipBigPointy
root@029e17f90802:/app# dotnet Ray.BiliBiliTool.Console.dll --runTasks=VipBigPointy
[19:00:39 INF] BiliBiliToolPro 开始运行...

2022-09-10T11:00:39.9950128Z File target /app/Logs/log20220910.txt was locked, attempting to open next in sequence (attempt 1)
2022-09-10T11:00:39.9957936Z File target /app/Logs/log20220910_001.txt was locked, attempting to open next in sequence (attempt 2)
2022-09-10T11:00:39.9960042Z File target /app/Logs/log20220910_002.txt was locked, attempting to open next in sequence (attempt 3)
[19:00:40 INF] 【目标任务】VipBigPointy
[19:00:40 INF] 【账号个数】1个

[19:00:40 INF] 随机休眠5分钟

[19:05:40 INF] 账号 1 ：

[19:05:40 WRN] 异常：System.Collections.Generic.KeyNotFoundException: The given key 'VipBigPointy' was not present in the dictionary.
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /code/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 146
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /code/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 67
[19:05:40 INF] 运行结束

**Comment by windfsy** [comment]
+1

**Comment by RayWangQvQ** [comment]
于 #260 统一追踪
