### ISSUE TITLE
观看分享视频投币非法访问

### ISSUE THREAD

**Issue by XueGao233** [RayWangQvQ/BiliBiliToolPro#287]
![image](https://user-images.githubusercontent.com/69283292/191693930-06be8cfa-d3dc-4a90-be79-84bbd4b44a22.png)

**Comment by hayoial** [comment]
一模一样

**Comment by lxhlemon** [comment]
异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 322

**Comment by ranyev5** [comment]
异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 322
臣附议

**Comment by hecarli555** [comment]
我也出现这个问题了

**Comment by windskyxb** [comment]
我也出现了这种情况
[log20220925.txt](https://github.com/RayWangQvQ/BiliBiliToolPro/files/9639815/log20220925.txt)

**Comment by Carpe0iem** [comment]
一样观看分享视频非法访问

**Comment by zzzqu** [comment]
+1

**Comment by fengchenzhihun1** [comment]
+1

**Comment by GreatLoch123** [comment]
确实 b站更新接口了吗

**Comment by 4pease** [comment]
+1

**Comment by majinnn** [comment]
mark

**Comment by noahziheng** [comment]
same issue

**Comment by x1737886903** [comment]
请问如何处理

**Comment by banjuer** [comment]
1

**Comment by Suplinna** [comment]
同 客户端分享视频 失败

**Comment by nevertoday** [comment]
我也有这个问题，有的帐号有， 有的帐号没有 ~ 难道是我帐号登录太多了， 太平凡了， 能投币成功， 但总提示这个 ！今天是我第二天本机使用这个。

**Comment by feixukeji** [comment]
仍然提示该问题：

[12:42:52 INF] ---开始 观看、分享视频 ---
[12:43:38 ERR] 观看、分享视频失败，继续其他任务。失败信息:非法访问

[12:43:38 INF] ---开始 投币 ---
[12:44:06 INF] 【今日已投】0枚
[12:44:06 INF] 【目标欲投】5枚
[12:44:06 INF] 【还需再投】5枚
[12:44:34 INF] 【投币前余额】 : 349.7
[12:45:41 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 322

**Comment by RayWangQvQ** [comment]
投币异常已于 #418 修复，分享异常会于 #321 继续追踪

**Comment by nevertoday** [comment]
棒呆
