### ISSUE TITLE
【其他】青龙运行出错

### ISSUE THREAD

**Issue by yonggedebaqi** [RayWangQvQ/BiliBiliToolPro#294]
## 开始执行... 2022-10-15 10:55:23

repo目录: /ql/data/repo
bili仓库目录: 

Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
bili_dev_task_daily.sh: line 17:  7695 Aborted                 (core dumped) dotnet run --project ./src/Ray.BiliBiliTool.Console

## 执行结束... 2022-10-15 10:55:25 耗时 2 秒

**Comment by RayWangQvQ** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/issues/266
