### ISSUE TITLE
【Bug】运行每日任务脚本 报错

### ISSUE THREAD

**Issue by While-Shark** [RayWangQvQ/BiliBiliToolPro#296]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
qinglongV2.12.2
运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）
树莓派4B docker运行qinglong容器
问题描述：（提issue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）
启动每日任务，脚本报错
![image](https://user-images.githubusercontent.com/24545680/196173599-bd7e76e8-bfae-4bf8-927e-5a084747fa7c.png)

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）
repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/raywangqvq_bilibilitoolpro

System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/ql/data/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/Ray.BiliBiliTool.Console' with working directory '/ql/data/repo/raywangqvq_bilibilitoolpro'. Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

## 执行结束... 2022-10-17 20:04:12 耗时 79 秒

**Comment by RayWangQvQ** [comment]
[https://user-images.githubusercontent.com/31154238/201953749-b46509de-c906-4cf8-94c5-af33048cd999.png](https://user-images.githubusercontent.com/31154238/201953749-b46509de-c906-4cf8-94c5-af33048cd999.png)

试试这个
