### ISSUE TITLE
【Bug】大会积分任务运行有报错，有报错日志

### ISSUE THREAD

**Issue by FlechazoPh** [RayWangQvQ/BiliBiliToolPro#297]
版本号：0.2.1
运行环境：linux q青龙

问题描述：大会员积分任务报错

日志信息：
<img width="519" alt="image" src="https://user-images.githubusercontent.com/94276146/196590937-6e2c4fb3-0e57-465c-aa58-c60bfd54787b.png">

[11:27:05 INF] ------当前任务状态------
[11:27:05 INF] 打卡：√
[11:27:05 INF] -福利任务
[11:27:05 INF] ---大会员福利大积分：√
[11:27:05 INF] -体验任务
[11:27:05 INF] ---浏览大会员权益页面：√
[11:27:05 INF] -日常任务
[11:27:05 INF] ---浏览追番频道页10秒：√
[11:27:05 INF] ---浏览影视频道页10秒：√
[11:27:05 INF] ---浏览会员购页面10秒：X
[11:27:05 INF] ---观看任意正片内容：X
[11:27:05 INF] ---购买单点付费影片：X
[11:27:05 INF] ---购买指定会员购商品：X
[11:27:05 INF] ------------------------

[11:27:05 INF] ---开始 签到 ---
[11:27:05 INF] 已完成，跳过
[11:27:05 INF] 今日获得签到积分：10
[11:27:05 INF] 累计签到89天
[11:27:05 INF] -----结束-----

[11:27:05 INF] ---开始 福利任务 ---
[11:27:05 INF] 已完成，跳过
[11:27:05 INF] -------结束-------

[11:27:05 INF] ---开始 体验任务 ---
[11:27:05 INF] 已完成，跳过
[11:27:05 INF] -------结束-------

[11:27:05 INF] ---开始 浏览追番频道页10秒 ---
[11:27:05 INF] 已完成，跳过
[11:27:05 INF] -------------结束-------------

[11:27:05 INF] ---开始 浏览影视频道页10秒 ---
[11:27:05 INF] 已完成，跳过
[11:27:05 INF] -------------结束-------------

[11:27:05 INF] ---开始 浏览会员购页面10秒 ---
[11:27:05 INF] 待实现...
[11:27:05 INF] -------------结束-------------

[11:27:05 INF] ---开始 观看任意正片内容 ---
[11:27:05 INF] 开始完成任务
[11:27:05 INF] 待开发...
[11:27:05 INF] -----------结束-----------

[11:27:05 INF] ---开始 购买单点付费影片（仅领取） ---
[11:27:05 INF] 已领取，跳过
[11:27:05 INF] ----------------结束----------------

[11:27:05 INF] ---开始 购买指定大会员产品（仅领取） ---
[11:27:05 ERR] 购买指定大会员产品（仅领取）失败，继续其他任务。失败信息:Sequence contains no matching element

[11:27:05 INF] ---开始 购买指定会员购商品（仅领取） ---
[11:27:05 ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[11:27:05 ERR] 程序发生异常：Object reference not set to an instance of an object.
[11:27:05 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /ql/data/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 153
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 67
[11:27:05 INF] 运行结束

**Comment by 873896135** [comment]
同问

**Comment by LYDQE** [comment]
我也遇到，大会员积分任务签到直接全部报错

**Comment by Toylee2019** [comment]
同问

**Comment by Ricardo-X-Chen** [comment]
same problem

**Comment by nibazshab** [comment]
同样的问题

**Comment by cnxjg** [comment]
[01:07:55 INF] ---开始 浏览影视频道页10秒 ---
[01:07:55 ERR] 浏览影视频道页10秒失败，继续其他任务。失败信息:Sequence contains no matching element

[01:07:55 INF] ---开始 浏览会员购页面10秒 ---
[01:07:55 INF] 待实现...
[01:07:55 INF] -------------结束-------------

[01:07:55 INF] ---开始 观看任意正片内容 ---
[01:07:55 ERR] 观看任意正片内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:55 INF] ---开始 购买单点付费影片（仅领取） ---
[01:07:55 ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:55 INF] ---开始 购买指定大会员产品（仅领取） ---
[01:07:55 ERR] 购买指定大会员产品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:55 INF] ---开始 购买指定会员购商品（仅领取） ---
[01:07:55 ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:55 ERR] 程序发生异常：Object reference not set to an instance of an object.
[01:07:55 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 168
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76


你们怎么解决的啊？？？？

**Comment by nibazshab** [comment]
没解决呢，没管它 @cnxjg

**Comment by cnxjg** [comment]
> 没解决呢，没管它 @cnxjg

好吧

**Comment by Redbeanw44602** [comment]
我也遇到这个问题了

**Comment by kingsleygithub001** [comment]
同样的问题，大会员积分任务全部失败

**Comment by FangDoudouY** [comment]
同问

**Comment by RayWangQvQ** [comment]
于 #260 统一追踪
