### ISSUE TITLE
测试时可以正常使用，部署完毕创建触发器后出现异常

### ISSUE THREAD

**Issue by twdpy** [RayWangQvQ/BiliBiliToolPro#30]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）

问题描述：（测试时可以正常使用，部署完毕创建触发器后出现异常）

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）
 异常：System.Collections.Generic.KeyNotFoundException: The given key ',' was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at Ray.BiliBiliTool.Console.HostedServices.BiliBiliToolHostedService.DoTasks(String[] tasks) in /mnt/g/github/bilibilitool/src/Ray.BiliBiliTool.Console/HostedServices/BiliBiliToolHostedService.cs:line 90

   at Ray.BiliBiliTool.Console.HostedServices.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /mnt/g/github/bilibilitool/src/Ray.BiliBiliTool.Console/HostedServices/BiliBiliToolHostedService.cs:line 52

**Comment by JsiAng233** [comment]
确实我也是这个问题 用的腾讯云函数
日志:

START RequestId: 211deb7e-ad7e-450d-8019-76f9e97ca8eb

[step 1]初始化，开始加载函数文件 index.sh

成功加载index.sh函数文件

=>完成

[step 2]初始化完成，开始发送ready信号

Init Report RequestId: 211deb7e-ad7e-450d-8019-76f9e97ca8eb Coldstart: 539ms (PullCode: 450ms InitRuntime: 11ms InitFunction: 78ms) Memory: 64MB MemUsage: 3.47MB

=>完成

[step 3]开始循环监听处理事件调用

=>长轮询获取事件

=>监听到事件：{"Message":"","Time":"2022-03-23T00:00:00Z","TriggerName":"SCF-timer-1647915268","Type":"Timer"}

=>调用函数,开始处理事件

进入main_handler

{"Message":"","Time":"2022-03-23T00:00:00Z","TriggerName":"SCF-timer-1647915268","Type":"Timer"}

触发事件中的附加消息（任务编码）为：,

开始运行BiliBiliTool......

[00:00:02 INF] BiliBiliToolPro 开始运行...

2022-03-23T00:00:02.7554948Z File target /var/user/Logs/log20220323.txt was locked, attempting to open next in sequence (attempt 1)

2022-03-23T00:00:02.7647925Z File target /var/user/Logs/log20220323_001.txt was locked, attempting to open next in sequence (attempt 2)

2022-03-23T00:00:02.7649223Z File target /var/user/Logs/log20220323_002.txt was locked, attempting to open next in sequence (attempt 3)

[00:00:02 INF] 【目标任务】,

[00:00:02 INF] 【账号个数】1个

[00:00:02 INF] 随机休眠8分钟

[00:08:02 INF] 账号 1 ：

[00:08:02 WRN] 异常：System.Collections.Generic.KeyNotFoundException: The given key ',' was not present in the dictionary.

   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 146

   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 67

[00:08:02 INF] 运行结束

函数结束

=>返回 {"Message":"","Time":"2022-03-23T00:00:00Z","TriggerName":"SCF-timer-1647915268","Type":"Timer"}

=>推送函数处理结果

Response RequestId:211deb7e-ad7e-450d-8019-76f9e97ca8eb RetMsg:{"Message":"","Time":"2022-03-23T00:00:00Z","TriggerName":"SCF-timer-1647915268","Type":"Timer"}

END RequestId:211deb7e-ad7e-450d-8019-76f9e97ca8eb

Report RequestId:211deb7e-ad7e-450d-8019-76f9e97ca8eb Duration:481476ms Memory:64MB MemUsage:30.150482MB

大佬 这个怎么解决啊

**Comment by RayWangQvQ** [comment]
明显时触发器里附加信息没填。。。

https://github.com/RayWangQvQ/BiliBiliToolPro/blob/0.0.7/tencentScf/README.md#323-%E6%89%8B%E5%8A%A8%E8%BF%90%E8%A1%8C%E6%B5%8B%E8%AF%95

附加信息里填`Daily`
