### ISSUE TITLE
视频分享失败，原因: 账号异常,操作失败

### ISSUE THREAD

**Issue by Remonli** [RayWangQvQ/BiliBiliToolPro#321]
版本号： 0.2.2

运行环境： Linux Debian testing

问题描述：视频分享还是提示失败

日志信息：[23:25:41 ERR] 视频分享失败，原因: 账号异常,操作失败

不是每天都失败，大概一半一半概率能成功。

**Comment by Remonli** [comment]
还是很多报错.

```
【今日已投】0枚
【目标欲投】5枚
【还需再投】5枚
【投币前余额】 : 1
因硬币余额不足，目标投币数调整为: 1
异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
```

**Comment by DumKing** [comment]
同样的问题+1

**Comment by windfsy** [comment]
+1

**Comment by azhen98** [comment]
1

**Comment by zhutianxiang06** [comment]
+1

**Comment by DumKing** [comment]
@RayWangQvQ 这个有没有好的修复方案🤨🤨🤨

**Comment by lidaheyaya** [comment]
+1

**Comment by RayWangQvQ** [comment]
由 #228 统一追踪，观关闭改issue

**Comment by RayWangQvQ** [comment]
已修复
