### ISSUE TITLE
【Bug】视频没有权限

### ISSUE THREAD

**Issue by HunterXing** [RayWangQvQ/BiliBiliToolPro#343]
版本号：最新版
运行环境：docker/linux
问题描述：

日志信息：
System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetRandomVideoOfUp(Int64 upId, Int32 total) in /code/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 84
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /code/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 329
   
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/38486063/204543544-2fd14cad-e571-4ba2-a0ad-78841c974e05.png">

**Comment by RayWangQvQ** [comment]
升级到最新版本可以解决
