### ISSUE TITLE
【Bug】青龙运行时报错:Name does not resolve

### ISSUE THREAD

**Issue by gaoxiang7552** [RayWangQvQ/BiliBiliToolPro#35]
青龙环境任务运行时报错:

[EXCEPTION]
System.Net.Http.HttpRequestException: Name does not resolve (api.live.bilibili.com:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)

**Comment by yiyungent** [comment]
这个应该是网络问题

**Comment by AmazingXiaomi** [comment]
我也出现了
