### ISSUE TITLE
【Bug】青龙里扫码登录后报错sequence contains no element

### ISSUE THREAD

**Issue by moonipulate** [RayWangQvQ/BiliBiliToolPro#366]
版本号：~~v0.3.1~~ v0.3.2
运行环境：qinglong（qinglong跑在linux docker里）

问题描述：在青龙里执行“bili扫码登录”任务后扫码成功后报错

follow的是这个步骤：https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md#142-%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1%E6%8B%89%E5%BA%93

日志信息：

[03:40:38 INF] 我数到10，动作快点
[03:40:38 INF] [1]等待扫描...
[03:40:46 INF] 未扫码

[03:40:46 INF] [2]等待扫描...
[03:40:55 INF] 扫描成功！
[03:40:55 INF] --------结束--------

[03:40:55 INF] ---开始 添加ck到青龙环境变量 ---
[03:40:55 INF] 用户不存在，新增cookie
[03:40:55 ERR] 程序发生异常：Sequence contains no elements
[03:40:55 ERR] 程序发生异常：Sequence contains no elements
[03:40:55 ERR] 程序异常终止，原因：Sequence contains no elements
[03:40:55 INF] 运行环境：Development
[03:40:55 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[03:40:55 INF] 运行结束
[03:40:55 FTL] Host terminated unexpectedly!
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at Ray.BiliBiliTool.Application.LoginTaskAppService.AddOrUpdateCkToQingLong(BiliCookie ckInfo)
   at Ray.BiliBiliTool.Application.LoginTaskAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 168
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 64
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 27

**Comment by RayWangQvQ** [comment]
更新到v0.3.2试试

**Comment by moonipulate** [comment]
我测试了下Develop branch set cookie 不会报错了
