### ISSUE TITLE
腾讯云自动部署失败

### ISSUE THREAD

**Issue by niu541412** [RayWangQvQ/BiliBiliToolPro#373]
我是用的github  action保持代码更新。
这两天才发现自动部署腾讯云函数会一直失败。最近一次成功部署是12月12日。错误的几行代码如下。完整的日志附在最后。
> 开始部署到云函数
> 
> ⠋ 正在安装 Tencent Serverless CLI
> 
> ⠙ 正在安装 Tencent Serverless CLI
> 
> ⠹ 正在安装 Tencent Serverless CLI
> 
> ⠸ 正在安装 Tencent Serverless CLI
> 
> ⠼ 正在安装 Tencent Serverless CLI
> 
> ⠴ 正在安装 Tencent Serverless CLI
> /opt/hostedtoolcache/node/14.21.1/x64/lib/node_modules/serverless/bin/serverless.js:87
>           throw error;
>           ^
> 
> HTTPError: Response code 530 (Unknown Status)
>     at Request.<anonymous> (/opt/hostedtoolcache/node/14.21.1/x64/lib/node_modules/serverless/node_modules/got/dist/source/as-promise/index.js:118:42)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
>   code: 'ERR_NON_2XX_3XX_RESPONSE',
>   timings: {
>     start: 1671595829127,
>     socket: 1671595829128,
>     lookup: 1671595829418,
>     connect: 1671595829427,
>     secureConnect: 1671595829449,
>     upload: 1671595829449,
>     response: 1671595829510,
>     end: 1671595829513,
>     error: undefined,
>     abort: undefined,
>     phases: {
>       wait: 1,
>       dns: 290,
>       tcp: 9,
>       tls: 22,
>       request: 0,
>       firstByte: 61,
>       download: 3,
>       total: 386
>     }
>   }
> }

尝试换了cookie，腾讯密钥key，部署区域等手段都未解决。
[完整部署日志logs_56.zip](https://github.com/RayWangQvQ/BiliBiliToolPro/files/10274423/logs_56.zip)

另外试了下手动上传zip部署是没有问题的。

**Comment by niu541412** [comment]
经过我一番研究，是github action的默认ubuntu-latest image[从12月15日变成22.04版本](https://github.com/actions/runner-images/issues/6399)所致。
这个版本不提供node.js v12了。但是部署腾讯云的脚本内两个依赖。
checkout@v2 和 setup-node@v2 好像是需要这个版本的。

**Comment by niu541412** [comment]
确认大概率是网络问题，多试几次就有概率部署成功
