### ISSUE TITLE
运行“天选时刻”分组不存在，尝试创建...后报错

### ISSUE THREAD

**Issue by CandyKIng1991** [RayWangQvQ/BiliBiliToolPro#378]
版本号：3.2
运行环境：Win

问题描述：“天选时刻”分组不存在，尝试创建...后报错

日志信息：
[23:10:07 ERR] 程序发生异常：Object reference not set to an instance of an object.
[23:10:07 ERR] 程序发生异常：Object reference not set to an instance of an object.
[23:10:07 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.DomainService.LiveDomainService.GetOrCreateTianXuanGroupId() in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/LiveDomainService.cs:line 374
   at Ray.BiliBiliTool.DomainService.LiveDomainService.GroupFollowing() in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/LiveDomainService.cs:line 289
   at Ray.BiliBiliTool.Application.LiveLotteryTaskAppService.AutoGroupFollowings()
   at Ray.BiliBiliTool.Application.LiveLotteryTaskAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 158
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76

**Comment by RayWangQvQ** [comment]
Can you provide debug level logs for further troubleshooting
