### ISSUE TITLE
青龙运行报错，Couldn't find a valid ICU package installed on the system

### ISSUE THREAD

**Issue by s1023315593** [RayWangQvQ/BiliBiliToolPro#38]
版本号：青龙2.10.2

问题描述：
![image](https://user-images.githubusercontent.com/61337932/159218835-3e2e1b75-a79c-41fd-b8e1-c103660c67d7.png)
自行百度了 去下载了 yum install libicu / yum -y install libicu-devel / yum install libunwind  再次重启青龙还是无果 不得已请教下大佬

**Comment by s1023315593** [comment]
自行处理完毕了，在青龙配置里面加 export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1  再次运行则成功

**Comment by 896965554** [comment]
[23:06:37 INF] BiliBiliToolPro 开始运行...

[23:06:37 INF] 【目标任务】UnfollowBatched
[23:06:37 INF] 【账号个数】1个

[23:06:37 INF] 随机休眠8分钟

[23:14:37 INF] 账号 1 ：

[23:14:38 WRN] 异常：System.FormatException: New-line characters are not allowed in header values.
   at System.Net.Http.Headers.HttpHeaders.CheckContainsNewLine(String value)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at Ray.BiliBiliTool.Agent.Extensions.ServiceCollectionExtension.<>c__1`1.<AddBiliBiliClientApi>b__1_2(IServiceProvider sp, HttpClient c) in /ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Agent/Extensions/ServiceCollectionExtension.cs:line 102
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass1_1.<ConfigureHttpClient>b__2(HttpClient client)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at Microsoft.Extensions.DependencyInjection.HttpApiExtensions.HttpApiProvider`1.CreateHttpApi(IServiceProvider serviceProvider, String name)
   at Microsoft.Extensions.DependencyInjection.HttpApiExtensions.<>c__DisplayClass0_0`1.<AddHttpApi>b__0(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 149
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 67
[23:14:38 INF] 运行结束

**Comment by 896965554** [comment]
大佬麻烦了
