### ISSUE TITLE
【异常】扫码登录报错500

### ISSUE THREAD

**Issue by wenluqi** [RayWangQvQ/BiliBiliToolPro#391]
版本号：
运行环境：青龙部署
问题描述：bili扫码登录报错500

日志信息：[13:14:48 INF] 我数到10，动作快点
[13:14:48 INF] [1]等待扫描...
[13:14:59 INF] 扫描成功！
[13:14:59 INF] --------结束--------

[13:14:59 INF] ---开始 添加ck到青龙环境变量 ---
[13:14:59 INF] 用户已存在，更新cookie
[13:14:59 INF] Key：Ray_BiliBiliCookies__0
[13:15:01 ERR] [REQUEST]
PUT /api/envs HTTP/1.1
Host: localhost:5600
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoicU5VSDF4Wmc1NDhiQ2Y1U21Wd1dkOF81RG9tSXFUMFJIUFFUM1VGelZvWUdFcmRPTEdzOGw2SGR1QTlMRV8tOXNwV1ZCSkMtd0ZMTnVvSlZoYi1sTC1aUDR4MiIsImlhdCI6MTY3MzY3MjA0NywiZXhwIjoxNjczOTMxMjQ3fQ.AguWNBGLs7XM9RaqEfPqUpwQJxwdDIuYQ14PfWMISqNCU_ZO_-sI3x06i5Sn5h40
Accept: application/json; q=0.001, application/xml; q=0.001
Content-Type: application/json

{"id":0,"value":"SESSDATA=71b4f604%2C1689225299%2C7e0d6%2A12; bili_jct=a1aec9626c3dc2daa81d10579b5ed4ef; DedeUserID=382432778; DedeUserID__ckMd5=83d96ec83e50e473; sid=7onrfqb6","name":"Ray_BiliBiliCookies__0","remarks":"bili-382432778"}

[RESPONSE]
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Access-Control-Allow-Origin: *
ETag: W/"3c-xGgW407qTUtH0+OGy1UkuzKm1Ko"
Date: Sat, 14 Jan 2023 05:15:01 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Type: application/json; charset=utf-8
Content-Length: 60

{"code":500,"message":"celebrate request validation failed"}

[EXCEPTION]
WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：500 Internal Server Error
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

[ELAPSED] 00:00:02.0466782
[13:15:01 ERR] 程序发生异常：One or more errors occurred. (服务器响应了错误的http状态码：500 Internal Server Error)
[13:15:01 ERR] 程序发生异常：One or more errors occurred. (服务器响应了错误的http状态码：500 Internal Server Error)
[13:15:01 ERR] 程序异常终止，原因：One or more errors occurred. (服务器响应了错误的http状态码：500 Internal Server Error)
[13:15:01 INF] 运行环境：Development
[13:15:01 INF] 应用目录：/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[13:15:01 INF] 运行结束
[13:15:01 FTL] Host terminated unexpectedly!
System.AggregateException: One or more errors occurred. (服务器响应了错误的http状态码：500 Internal Server Error)
 ---> System.Net.Http.HttpRequestException: 服务器响应了错误的http状态码：500 Internal Server Error
 ---> WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：500 Internal Server Error
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(ApiRequestContext request)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   --- End of inner exception stack trace ---
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.Application.LoginTaskAppService.AddOrUpdateCkToQingLong(BiliCookie ckInfo)
   at Ray.BiliBiliTool.Application.LoginTaskAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 168
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 64
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 27

**Comment by RayWangQvQ** [comment]
青龙v2.15.5未复现
![image](https://user-images.githubusercontent.com/31154238/212460803-6f055d86-029c-4707-9362-ba6a074c9726.png)

说下青龙版本

**Comment by wenluqi** [comment]
v2.10.13

**Comment by RayWangQvQ** [comment]
建议使用青龙较新版本进行测试

**Comment by DoiiarX** [comment]
我的报错是502，你这个是500。你日志不完全，但你也用的5600端口。

你可以参考一下解决方案。

https://notion.doiiars.com/article/fixing-bilibilitoolpro-dockercompose-failure
