### ISSUE TITLE
【Bug】大积分任务报错

### ISSUE THREAD

**Issue by KevinXu07** [RayWangQvQ/BiliBiliToolPro#392]
版本号：0.3.2
运行环境：Debian11 linux 青龙运行

问题描述：如题

日志信息：[22:45:26 INF] ---开始 观看任意正片内容 ---
[22:45:26 ERR] 观看任意正片内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[22:45:26 INF] ---开始 购买单点付费影片（仅领取） ---
[22:45:26 ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[22:45:26 INF] ---开始 购买指定大会员产品（仅领取） ---
[22:45:26 ERR] 购买指定大会员产品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[22:45:26 INF] ---开始 购买指定会员购商品（仅领取） ---
[22:45:26 ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[22:45:26 ERR] 程序发生异常：Object reference not set to an instance of an object.
[22:45:26 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 168
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76

**Comment by RayWangQvQ** [comment]
重复
