### ISSUE TITLE
【Bug】Bili每日任务 签到失败，继续其他任务。"抱歉，您的账号存在风险，暂时无法参与本任务哦~","

### ISSUE THREAD

**Issue by LightningAlpaca** [RayWangQvQ/BiliBiliToolPro#401]
版本号：0.4.0(青龙自动已更新）
运行环境：（armbian-docker）

问题描述：（签到失败，继续其他任务。失败信息:{"Code":6007000,"Message":"抱歉，您的账号存在风险，暂时无法参与本任务哦~","Data":null}。）

日志信息：（repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

[01:07:23 INF] BiliBiliToolPro 开始运行...

[01:07:23 INF] 【目标任务】VipBigPoint
[01:07:23 INF] 【账号个数】1个

[01:07:23 INF] ######### 账号 1 #########

[01:07:24 INF] =====开始 大会员大积分 =====

[01:07:24 INF] ---开始 测试Cookie ---
[01:07:35 INF] 【用户名】闪xx羊驼
[01:07:35 INF] 【会员类型】年度大会员
[01:07:35 INF] 【会员状态】正常
[01:07:35 INF] 【硬币余额】120.2
[01:07:35 INF] 【当前经验】32898
[01:07:35 INF] 您已是 Lv6 的大佬了，无敌是多么寂寞~
[01:07:35 INF] -----------结束-----------

[01:07:39 INF] ------当前任务状态------
[01:07:39 INF] 打卡：X
[01:07:39 INF] -福利任务
[01:07:39 INF] ---大会员福利大积分：√
[01:07:39 INF] -体验任务
[01:07:39 INF] ---浏览大会员权益页面：√
[01:07:39 INF] ---领取大会员卡券包权益：√
[01:07:39 INF] -日常任务
[01:07:39 INF] ---浏览追番频道页10秒：X
[01:07:39 INF] ---浏览会员购页面10秒：X
[01:07:39 INF] ---观看任意正片内容：X
[01:07:39 INF] ---购买单点付费影片：X
[01:07:39 INF] ---购买指定会员购商品：X
[01:07:39 INF] ------------------------

[01:07:39 INF] ---开始 签到 ---
[01:07:47 ERR] 签到失败，继续其他任务。失败信息:{"Code":6007000,"Message":"抱歉，您的账号存在风险，暂时无法参与本任务哦~","Data":null}

[01:07:47 INF] ---开始 福利任务 ---
[01:07:47 ERR] 福利任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:47 INF] ---开始 体验任务 ---
[01:07:47 ERR] 体验任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:47 INF] ---开始 浏览追番频道页10秒 ---
[01:07:47 ERR] 浏览追番频道页10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:47 INF] ---开始 浏览影视频道页10秒 ---
[01:07:47 ERR] 浏览影视频道页10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:47 INF] ---开始 浏览会员购页面10秒 ---
[01:07:47 INF] 待实现...
[01:07:47 INF] -------------结束-------------

[01:07:47 INF] ---开始 观看任意正片内容 ---
[01:07:47 ERR] 观看任意正片内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:47 INF] ---开始 购买单点付费影片（仅领取） ---
[01:07:47 ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:47 INF] ---开始 购买指定大会员产品（仅领取） ---
[01:07:47 ERR] 购买指定大会员产品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:47 INF] ---开始 购买指定会员购商品（仅领取） ---
[01:07:47 ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:07:47 ERR] 程序发生异常：Object reference not set to an instance of an object.
[01:07:47 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 168
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76
[01:07:47 INF] 运行环境：Development
[01:07:47 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[01:07:47 INF] 运行结束）
天选时刻等其他都正常

**Comment by limx2021** [comment]
一样的问题

**Comment by liuyongyong6699** [comment]
一样，这个问题你是如何解决的

**Comment by JMuar** [comment]
一样的问题
