### ISSUE TITLE
扫码登入报错502 develop分支

### ISSUE THREAD

**Issue by r27153733** [RayWangQvQ/BiliBiliToolPro#429]
WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：502 Bad Gateway
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

[ELAPSED] 00:00:02.0343348
[19:41:36 ERR] 程序发生异常：One or more errors occurred. (服务器响应了错误的http状态码：502 Bad Gateway)
[19:41:36 ERR] 程序发生异常：One or more errors occurred. (服务器响应了错误的http状态码：502 Bad Gateway)
[19:41:36 ERR] 程序异常终止，原因：One or more errors occurred. (服务器响应了错误的http状态码：502 Bad Gateway)
[19:41:36 INF] 运行环境：Development
[19:41:36 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[19:41:36 INF] 运行结束
[19:41:36 FTL] Host terminated unexpectedly!
System.AggregateException: One or more errors occurred. (服务器响应了错误的http状态码：502 Bad Gateway)
 ---> System.Net.Http.HttpRequestException: 服务器响应了错误的http状态码：502 Bad Gateway
 ---> WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：502 Bad Gateway
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(ApiRequestContext request)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   --- End of inner exception stack trace ---
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.Application.LoginTaskAppService.AddOrUpdateCkToQingLong(BiliCookie ckInfo)
   at Ray.BiliBiliTool.Application.LoginTaskAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 168
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 64
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Program.cs:line 27

**Comment by RayWangQvQ** [comment]
未复现，需要debug级别日志

**Comment by DoiiarX** [comment]
经过熬夜排查我解决了这个bug。以下是思路和解决方案。

主要是端口问题。这部分不在你日志内。如果和我一样，应该是由于dockercompose端口不一样导致的。

https://notion.doiiars.com/article/fixing-bilibilitoolpro-dockercompose-failure
