### ISSUE TITLE
【Bug】VipBigPoint 大会员积分任务报错

### ISSUE THREAD

**Issue by Sibadaer** [RayWangQvQ/BiliBiliToolPro#445]
`会员类型】年度大会员
【会员状态】正常
【硬币余额】617.3
【距升级Lv5】69天（如每日做满65点经验）
-----------结束-----------
------当前任务状态------
打卡：X
-福利任务
---大会员福利大积分：X
-体验任务
---浏览大会员权益页面：X
---领取大会员卡券包权益：√
-日常任务
---浏览追番频道页10秒：X
---浏览会员购页面10秒：X
---观看任意正片内容：X
---购买单点付费影片：X
---购买指定会员购商品：X

---开始 签到 ---
签到失败，继续其他任务。失败信息:{"Code":6007000,"Message":"抱歉，您的账号存在风险，暂时无法参与本任务哦~","Data":null}
---开始 福利任务 ---
福利任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.
---开始 体验任务 ---
体验任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.
---开始 浏览追番频道页10秒 ---
浏览追番频道页10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.
---开始 浏览影视频道页10秒 ---
浏览影视频道页10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.
---开始 浏览会员购页面10秒 ---
待实现...
-------------结束-------------
---开始 观看任意正片内容 ---
观看任意正片内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.
---开始 购买单点付费影片（仅领取） ---
购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.
---开始 购买指定大会员产品（仅领取） ---
购买指定大会员产品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.
---开始 购买指定会员购商品（仅领取） ---
购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.
程序发生异常：Object reference not set to an instance of an object.
异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 168
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76`

#  每次运行都是这样，请教下大伙是怎么解决的？

**Comment by Sibadaer** [comment]
# 每日任务模块报错这样， 你们碰到过嘛？


[09:00:13 INF] 【会员类型】月度大会员
[09:00:13 INF] 【会员状态】无/过期
[09:00:13 INF] 【硬币余额】4
[09:00:13 INF] 【距升级Lv5】89天（如每日做满65点经验）
[09:00:13 INF] 登录成功，经验+5 √
[09:00:13 INF] -----结束-----

[09:00:20 INF] ---开始 观看、分享视频 ---
[09:00:37 INF] 【随机视频】忘川里的水鬼
[09:00:45 INF] 视频播放成功，已观看到第4秒，经验+5 √
[09:00:52 ERR] 视频分享失败，原因: 账号异常,操作失败
[09:00:52 INF] ----------结束----------

[09:00:52 INF] ---开始 投币 ---
[09:00:58 INF] 【今日已投】0枚
[09:00:58 INF] 【目标欲投】5枚
[09:00:58 INF] 【还需再投】5枚
[09:01:03 INF] 【投币前余额】 : 4
[09:01:03 INF] 因硬币余额不足，目标投币数调整为: 4
[09:01:39 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:01:57 INF] 【视频】⚡狂飙，但是全员押韵⚡
[09:02:02 INF] 投币成功，经验+10 √
[09:02:15 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetRandomVideoOfUp(Int64 upId, Int32 total) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 84
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 329
[09:02:23 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:02:42 INF] 【视频】厦门.网红市场
[09:02:45 INF] 投币成功，经验+10 √
[09:02:52 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetRandomVideoOfUp(Int64 upId, Int32 total) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 84
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 329
[09:03:03 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:03:19 INF] 【视频】南方人第一次吃回民饭馆!黏糊糊的扒肉太香了!
[09:03:22 INF] 投币成功，经验+10 √
[09:03:33 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetRandomVideoOfUp(Int64 upId, Int32 total) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 84
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 329
[09:03:46 WRN] 异常：System.Exception: 非法访问
   at Ray.BiliBiliTool.DomainService.VideoDomainService.GetVideoCountOfUp(Int64 upId) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs:line 101
   at Ray.BiliBiliTool.DomainService.DonateCoinDomainService.TryCanDonateVideoByUps(List`1 upIds, Int32 tryCount) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/DonateCoinDomainService.cs:line 324
[09:04:02 INF] 【视频】【学医致用】瘦了60斤后，终于明白怎么才瘦的快了！I 看了这个视频让你暴瘦10斤！
[09:04:09 INF] 投币成功，经验+10 √
[09:04:09 INF] 投币任务完成
[09:04:12 INF] 【硬币余额】0
[09:04:12 INF] -----结束-----

[09:04:12 INF] ---开始 直播签到 ---
[09:04:15 INF] 【签到结果】成功
[09:04:15 INF] 【本次获取】3000点用户经验,2根辣条,再签到4天可以获得50根辣条
[09:04:15 INF] -------结束-------

[09:04:15 INF] ---开始 漫画签到 ---
[09:04:19 INF] 【签到结果】成功
[09:04:19 INF] -------结束-------

[09:04:19 INF] ---开始 漫画阅读 ---
[09:04:23 INF] 【漫画阅读】成功, 阅读漫画为：堀与宫村
[09:04:23 INF] -------结束-------

[09:04:23 INF] ---开始 银瓜子兑换硬币 ---
[09:04:23 INF] 已配置为关闭，跳过
[09:04:23 INF] ----------结束----------

[09:04:23 INF] ---开始 领取大会员福利 ---
[09:04:23 INF] 普通会员和月度大会员每月不赠送B币券，不需要领取权益喽
[09:04:23 INF] ----------结束----------

[09:04:23 INF] ---开始 领取大会员漫画权益 ---
[09:04:23 INF] 不是会员，跳过
[09:04:23 INF] ------------结束------------

[09:04:23 INF] ---开始 B币券充电 ---
[09:04:23 INF] 不是年度大会员，跳过
[09:04:23 INF] --------结束--------

[09:04:23 INF] =========结束=========

[09:04:23 INF] 

========================

**Comment by RayWangQvQ** [comment]
You should post the version and the debug logs of `bilibili_tool`, otherwise, no one can help you

**Comment by Sibadaer** [comment]
补充bug 版本和 日志文件
# 版本 v0.4.6

## 日志文件

### 1 BiliBiliToolPro_bili_task_vipBigPoint 模块
[2023-02-16-13-32-00.log](https://github.com/RayWangQvQ/BiliBiliToolPro/files/10753158/2023-02-16-13-32-00.log)

### 2 BiliBiliToolPro_bili_task_daily 模块

[2023-02-16-09-00-00.log](https://github.com/RayWangQvQ/BiliBiliToolPro/files/10753163/2023-02-16-09-00-00.log)

**Comment by limx2021** [comment]
每日模块没出错，大会员模块一样

**Comment by RayWangQvQ** [comment]
> 1 模块 ： BiliBiliToolPro_bili_task_vipBigPoint 频率: 每次

重复已知问题，已由 #260 追踪

> 2 模块 ： BiliBiliToolPro_bili_task_daily 频率: 每次

如上，建议检查下自己账号，我这边也未能重现

**Comment by catlair** [comment]
抱歉，您的账号存在风险，暂时无法参与本任务哦 这就是字面意思，手机打开打几分页面查看是否异常

**Comment by kettly1260** [comment]
> 抱歉，您的账号存在风险，暂时无法参与本任务哦 这就是字面意思，手机打开大积分页面查看是否异常

但是我自己用手机是可以做的，不知道为什么脚本不行
