### ISSUE TITLE
【Bug】粉丝牌报错

### ISSUE THREAD

**Issue by Salomens** [RayWangQvQ/BiliBiliToolPro#446]
版本号：最新版4.6
运行环境：青龙

问题描述：直播间粉丝牌报错

日志信息：## 开始执行... 2023-02-17 07:56:39

已安装dotnet，当前版本：6.0.405

repo目录: /ql/repo
bili仓库目录: /ql/repo/RayWangQvQ_BiliBiliToolPro

[07:56:45 INF] BiliBiliToolPro 开始运行...

[07:56:45 INF] 【目标任务】LiveFansMedal
[07:56:45 INF] 【账号个数】1个

[07:56:45 INF] ######### 账号 1 #########

[07:56:46 INF] =====开始 直播间互动 =====

[07:56:46 INF] ---开始 发送弹幕 ---
[07:56:46 INF] 检测到直播 Cookie 未正确配置，尝试自动配置中...
[07:56:50 INF] 直播 Cookie 配置成功！
[07:56:50 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
[07:56:57 ERR] [REQUEST]
GET /xlive/web-ucenter/user/MedalWall?target_id=355624442 HTTP/1.1
Referer: https://live.bilibili.com/
Origin: https://live.bilibili.com
Host: api.live.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Thu, 16 Feb 2023 23:56:57 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Bili-Status-Code: 0
Bili-Trace-Id: d762736d0353adcb
X-Bili-Trace-Id: 87e1d01ad7093f9bd762736d0353adcb
Access-Control-Allow-Origin: https://live.bilibili.com
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip
Cross-Origin-Resource-Policy: cross-origin
Vary: Accept-Encoding,Origin
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from blzone11
Content-Type: application/json; charset=utf-8
Expires: Thu, 16 Feb 2023 23:56:56 GMT
Content-Length: 3304

{"code":0,"message":"0","ttl":1,"data":{"list":[{"medal_info":{"target_id":883968,"level":12,"medal_name":"暴漫","medal_color_start":9272486,"medal_color_end":9272486,"medal_color_border":9272486,"guard_level":0,"wearing_status":0,"medal_id":5291,"intimacy":5588,"next_intimacy":10000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"暴走漫画","target_icon":"https://i0.hdslb.com/bfs/face/c93ff5df2cd0c0c9384b139c86d1a56a9540c9a2.jpg","link":"https://space.bilibili.com/883968","live_status":2,"official":1},{"medal_info":{"target_id":10119428,"level":12,"medal_name":"保肝片","medal_color_start":9272486,"medal_color_end":9272486,"medal_color_border":9272486,"guard_level":0,"wearing_status":0,"medal_id":28976,"intimacy":4718,"next_intimacy":10000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"小片片说大片","target_icon":"https://i2.hdslb.com/bfs/face/949fd3f0b9fe23703c970d494edc41ae52ee32de.jpg","link":"https://space.bilibili.com/10119428","live_status":2,"official":1},{"medal_info":{"target_id":337521240,"level":12,"medal_name":"派派派","medal_color_start":9272486,"medal_color_end":9272486,"medal_color_border":9272486,"guard_level":0,"wearing_status":0,"medal_id":123430,"intimacy":4553,"next_intimacy":10000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"记录生活的蛋黄派","target_icon":"https://i0.hdslb.com/bfs/face/9ba6c7a0d3a2ebfe9db2f46219ece98e210d0269.jpg","link":"https://space.bilibili.com/337521240","live_status":0,"official":1},{"medal_info":{"target_id":500971120,"level":5,"medal_name":"小干部","medal_color_start":6126494,"medal_color_end":6126494,"medal_color_border":6126494,"guard_level":0,"wearing_status":0,"medal_id":559424,"intimacy":399,"next_intimacy":1000,"today_feed":100,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"陈怀安_Aaa","target_icon":"https://i1.hdslb.com/bfs/face/89292a9917cf8b64a6fe4bf11d8ad9897589683a.jpg","link":"https://space.bilibili.com/500971120","live_status":0,"official":1},{"medal_info":{"target_id":3493089022839682,"level":5,"medal_name":"流亦霏","medal_color_start":6126494,"medal_color_end":6126494,"medal_color_border":6126494,"guard_level":0,"wearing_status":0,"medal_id":907500,"intimacy":299,"next_intimacy":1000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"一只香酥霏霏","target_icon":"https://i1.hdslb.com/bfs/face/f9d0bdcdce2732506956e2d57741b7611934caa9.jpg","link":"https://space.bilibili.com/3493089022839682","live_status":0,"official":0},{"medal_info":{"target_id":1626479,"level":5,"medal_name":"半个人","medal_color_start":6126494,"medal_color_end":6126494,"medal_color_border":6126494,"guard_level":0,"wearing_status":0,"medal_id":136221,"intimacy":299,"next_intimacy":1000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"是我阿半","target_icon":"https://i2.hdslb.com/bfs/face/7a5077a87b6f4a85c07799c52b78c80a2dd5e196.jpg","link":"https://space.bilibili.com/1626479","live_status":0,"official":1}],"count":6,"close_space_medal":0,"only_show_wearing":0,"name":"徽章的鸢尾花","icon":"https://i2.hdslb.com/bfs/face/d778917a9ebe8120444f046f0ba89ef1410a72f8.jpg","uid":355624442,"level":5}

[EXCEPTION]
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.list[4].medal_info.target_id | LineNumber: 0 | BytePositionInLine: 2127.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Converters.Int32Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at WebApiClientCore.ApiResponseContextExtensions.JsonDeserializeAsync(ApiResponseContext context, Type objType)
   at WebApiClientCore.Attributes.JsonReturnAttribute.SetResultAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

[ELAPSED] 00:00:06.1539057
[07:56:57 ERR] 发送弹幕失败，继续其他任务。失败信息:One or more errors occurred. (The JSON value could not be converted to System.Int32. Path: $.data.list[4].medal_info.target_id | LineNumber: 0 | BytePositionInLine: 2127.)

[07:56:57 INF] ---开始 点赞直播间 ---
[07:56:57 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
[07:57:01 ERR] [REQUEST]
GET /xlive/web-ucenter/user/MedalWall?target_id=355624442 HTTP/1.1
Referer: https://live.bilibili.com/
Origin: https://live.bilibili.com
Host: api.live.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Thu, 16 Feb 2023 23:57:01 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Bili-Status-Code: 0
Bili-Trace-Id: 2c6ad16a7017592c
X-Bili-Trace-Id: 76781b98de298d502c6ad16a7017592c
Access-Control-Allow-Origin: https://live.bilibili.com
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip
Cross-Origin-Resource-Policy: cross-origin
Vary: Accept-Encoding,Origin
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from blzone11
Content-Type: application/json; charset=utf-8
Expires: Thu, 16 Feb 2023 23:57:00 GMT
Content-Length: 3304

{"code":0,"message":"0","ttl":1,"data":{"list":[{"medal_info":{"target_id":883968,"level":12,"medal_name":"暴漫","medal_color_start":9272486,"medal_color_end":9272486,"medal_color_border":9272486,"guard_level":0,"wearing_status":0,"medal_id":5291,"intimacy":5588,"next_intimacy":10000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"暴走漫画","target_icon":"https://i0.hdslb.com/bfs/face/c93ff5df2cd0c0c9384b139c86d1a56a9540c9a2.jpg","link":"https://space.bilibili.com/883968","live_status":2,"official":1},{"medal_info":{"target_id":10119428,"level":12,"medal_name":"保肝片","medal_color_start":9272486,"medal_color_end":9272486,"medal_color_border":9272486,"guard_level":0,"wearing_status":0,"medal_id":28976,"intimacy":4718,"next_intimacy":10000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"小片片说大片","target_icon":"https://i2.hdslb.com/bfs/face/949fd3f0b9fe23703c970d494edc41ae52ee32de.jpg","link":"https://space.bilibili.com/10119428","live_status":2,"official":1},{"medal_info":{"target_id":337521240,"level":12,"medal_name":"派派派","medal_color_start":9272486,"medal_color_end":9272486,"medal_color_border":9272486,"guard_level":0,"wearing_status":0,"medal_id":123430,"intimacy":4553,"next_intimacy":10000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"记录生活的蛋黄派","target_icon":"https://i0.hdslb.com/bfs/face/9ba6c7a0d3a2ebfe9db2f46219ece98e210d0269.jpg","link":"https://space.bilibili.com/337521240","live_status":0,"official":1},{"medal_info":{"target_id":500971120,"level":5,"medal_name":"小干部","medal_color_start":6126494,"medal_color_end":6126494,"medal_color_border":6126494,"guard_level":0,"wearing_status":0,"medal_id":559424,"intimacy":399,"next_intimacy":1000,"today_feed":100,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"陈怀安_Aaa","target_icon":"https://i1.hdslb.com/bfs/face/89292a9917cf8b64a6fe4bf11d8ad9897589683a.jpg","link":"https://space.bilibili.com/500971120","live_status":0,"official":1},{"medal_info":{"target_id":3493089022839682,"level":5,"medal_name":"流亦霏","medal_color_start":6126494,"medal_color_end":6126494,"medal_color_border":6126494,"guard_level":0,"wearing_status":0,"medal_id":907500,"intimacy":299,"next_intimacy":1000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"一只香酥霏霏","target_icon":"https://i1.hdslb.com/bfs/face/f9d0bdcdce2732506956e2d57741b7611934caa9.jpg","link":"https://space.bilibili.com/3493089022839682","live_status":0,"official":0},{"medal_info":{"target_id":1626479,"level":5,"medal_name":"半个人","medal_color_start":6126494,"medal_color_end":6126494,"medal_color_border":6126494,"guard_level":0,"wearing_status":0,"medal_id":136221,"intimacy":299,"next_intimacy":1000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"是我阿半","target_icon":"https://i2.hdslb.com/bfs/face/7a5077a87b6f4a85c07799c52b78c80a2dd5e196.jpg","link":"https://space.bilibili.com/1626479","live_status":0,"official":1}],"count":6,"close_space_medal":0,"only_show_wearing":0,"name":"徽章的鸢尾花","icon":"https://i2.hdslb.com/bfs/face/d778917a9ebe8120444f046f0ba89ef1410a72f8.jpg","uid":355624442,"level":5}

[EXCEPTION]
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.list[4].medal_info.target_id | LineNumber: 0 | BytePositionInLine: 2127.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Converters.Int32Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at WebApiClientCore.ApiResponseContextExtensions.JsonDeserializeAsync(ApiResponseContext context, Type objType)
   at WebApiClientCore.Attributes.JsonReturnAttribute.SetResultAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

[ELAPSED] 00:00:04.0563524
[07:57:01 ERR] 点赞直播间失败，继续其他任务。失败信息:One or more errors occurred. (The JSON value could not be converted to System.Int32. Path: $.data.list[4].medal_info.target_id | LineNumber: 0 | BytePositionInLine: 2127.)

[07:57:01 INF] ---开始 直播时长挂机 ---
[07:57:01 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
[07:57:07 ERR] [REQUEST]
GET /xlive/web-ucenter/user/MedalWall?target_id=355624442 HTTP/1.1
Referer: https://live.bilibili.com/
Origin: https://live.bilibili.com
Host: api.live.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Thu, 16 Feb 2023 23:57:07 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Bili-Status-Code: 0
Bili-Trace-Id: 62d879fdec00c189
X-Bili-Trace-Id: 3daee8ae2e6ec3d562d879fdec00c189
Access-Control-Allow-Origin: https://live.bilibili.com
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip
Cross-Origin-Resource-Policy: cross-origin
Vary: Accept-Encoding,Origin
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from blzone09
Content-Type: application/json; charset=utf-8
Expires: Thu, 16 Feb 2023 23:57:06 GMT
Content-Length: 3304

{"code":0,"message":"0","ttl":1,"data":{"list":[{"medal_info":{"target_id":883968,"level":12,"medal_name":"暴漫","medal_color_start":9272486,"medal_color_end":9272486,"medal_color_border":9272486,"guard_level":0,"wearing_status":0,"medal_id":5291,"intimacy":5588,"next_intimacy":10000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"暴走漫画","target_icon":"https://i0.hdslb.com/bfs/face/c93ff5df2cd0c0c9384b139c86d1a56a9540c9a2.jpg","link":"https://space.bilibili.com/883968","live_status":2,"official":1},{"medal_info":{"target_id":10119428,"level":12,"medal_name":"保肝片","medal_color_start":9272486,"medal_color_end":9272486,"medal_color_border":9272486,"guard_level":0,"wearing_status":0,"medal_id":28976,"intimacy":4718,"next_intimacy":10000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"小片片说大片","target_icon":"https://i2.hdslb.com/bfs/face/949fd3f0b9fe23703c970d494edc41ae52ee32de.jpg","link":"https://space.bilibili.com/10119428","live_status":2,"official":1},{"medal_info":{"target_id":337521240,"level":12,"medal_name":"派派派","medal_color_start":9272486,"medal_color_end":9272486,"medal_color_border":9272486,"guard_level":0,"wearing_status":0,"medal_id":123430,"intimacy":4553,"next_intimacy":10000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"记录生活的蛋黄派","target_icon":"https://i0.hdslb.com/bfs/face/9ba6c7a0d3a2ebfe9db2f46219ece98e210d0269.jpg","link":"https://space.bilibili.com/337521240","live_status":0,"official":1},{"medal_info":{"target_id":500971120,"level":5,"medal_name":"小干部","medal_color_start":6126494,"medal_color_end":6126494,"medal_color_border":6126494,"guard_level":0,"wearing_status":0,"medal_id":559424,"intimacy":399,"next_intimacy":1000,"today_feed":100,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"陈怀安_Aaa","target_icon":"https://i1.hdslb.com/bfs/face/89292a9917cf8b64a6fe4bf11d8ad9897589683a.jpg","link":"https://space.bilibili.com/500971120","live_status":0,"official":1},{"medal_info":{"target_id":3493089022839682,"level":5,"medal_name":"流亦霏","medal_color_start":6126494,"medal_color_end":6126494,"medal_color_border":6126494,"guard_level":0,"wearing_status":0,"medal_id":907500,"intimacy":299,"next_intimacy":1000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"一只香酥霏霏","target_icon":"https://i1.hdslb.com/bfs/face/f9d0bdcdce2732506956e2d57741b7611934caa9.jpg","link":"https://space.bilibili.com/3493089022839682","live_status":0,"official":0},{"medal_info":{"target_id":1626479,"level":5,"medal_name":"半个人","medal_color_start":6126494,"medal_color_end":6126494,"medal_color_border":6126494,"guard_level":0,"wearing_status":0,"medal_id":136221,"intimacy":299,"next_intimacy":1000,"today_feed":0,"day_limit":1500,"guard_icon":"","honor_icon":""},"target_name":"是我阿半","target_icon":"https://i2.hdslb.com/bfs/face/7a5077a87b6f4a85c07799c52b78c80a2dd5e196.jpg","link":"https://space.bilibili.com/1626479","live_status":0,"official":1}],"count":6,"close_space_medal":0,"only_show_wearing":0,"name":"徽章的鸢尾花","icon":"https://i2.hdslb.com/bfs/face/d778917a9ebe8120444f046f0ba89ef1410a72f8.jpg","uid":355624442,"level":5}

[EXCEPTION]
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.list[4].medal_info.target_id | LineNumber: 0 | BytePositionInLine: 2127.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Converters.Int32Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at WebApiClientCore.ApiResponseContextExtensions.JsonDeserializeAsync(ApiResponseContext context, Type objType)
   at WebApiClientCore.Attributes.JsonReturnAttribute.SetResultAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

[ELAPSED] 00:00:06.0923958
[07:57:07 ERR] 直播时长挂机失败，继续其他任务。失败信息:One or more errors occurred. (The JSON value could not be converted to System.Int32. Path: $.data.list[4].medal_info.target_id | LineNumber: 0 | BytePositionInLine: 2127.)

[07:57:07 INF] ==========结束==========

[07:57:07 INF]

**Comment by RayWangQvQ** [comment]
确认bug，int溢出，晚上我来修，感谢反馈

**Comment by RayWangQvQ** [comment]
已于`v1.0.0`版本修复
