### ISSUE TITLE
【Bug】投币发生未预计异常：非法访问

### ISSUE THREAD

**Issue by chenmg2020** [RayWangQvQ/BiliBiliToolPro#451]
版本号：最新
运行环境：Linux，青龙面板

问题描述：
[23:30:55 ERR] 投币发生未预计异常：非法访问
[23:30:55 ERR] 投币失败，继续其他任务。失败信息:投币发生未预计异常：非法访问

日志信息：
[23:30:55 ERR] 投币发生未预计异常：非法访问
[23:30:55 ERR] 投币失败，继续其他任务。失败信息:投币发生未预计异常：非法访问

**Comment by catlair** [comment]
这东西大积分，分享之后怎么投币也开始401了😀

**Comment by chenmg2020** [comment]
今天还是这样，其他没问题，就投币显示非法访问

[08:19:52 INF] ---开始 观看、分享视频 ---
[08:20:31 INF] 【随机视频】骑行海南露营野外很多蚂蚁钻进帐篷晚上睡觉很不舒服
[08:21:02 INF] 视频播放成功，已观看到第10秒，经验+5 √
[08:21:21 INF] 视频分享成功，经验+5 √
[08:21:21 INF] ----------结束----------

[08:21:21 INF] ---开始 投币 ---
[08:21:43 INF] 【今日已投】0枚
[08:21:43 INF] 【目标欲投】5枚
[08:21:43 INF] 【还需再投】5枚
[08:21:56 INF] 【投币前余额】 : 419
[08:23:08 INF] 【视频】拍视频手机掉下悬崖，去悬崖找手机很危险一不小心就会掉下山谷
[08:23:27 ERR] 投币发生未预计异常：非法访问
[08:23:27 ERR] 投币失败，继续其他任务。失败信息:投币发生未预计异常：非法访问

[08:23:27 INF] ---开始 直播签到 ---
[08:23:46 INF] 【签到结果】成功
[08:23:46 INF] 【本次获取】3000点用户经验,2根辣条,再签到3天可以获得666银瓜子
[08:23:46 INF] -------结束-------

[08:23:46 INF] ---开始 漫画签到 ---
[08:23:57 INF] 【签到结果】成功
[08:23:57 INF] -------结束-------

**Comment by kingsleygithub001** [comment]
同样的错误，今天开始出现

**Comment by Crazy-FuQing** [comment]
我也出现同样的错误
![1676775963952](https://user-images.githubusercontent.com/46838021/219909904-3ed2a521-def3-4f1c-b1ed-714210faaf57.png)

**Comment by lovemwy** [comment]
昨天，我也出现了，手动投了4个币后，剩一个币的时候又尝试运行了一次，成功投币了，今天还是出现这种情况了

**Comment by mima454188** [comment]
[12:52:58 INF] ---开始 投币 ---
[12:53:04 INF] 【今日已投】2枚
[12:53:04 INF] 【目标欲投】5枚
[12:53:04 INF] 【还需再投】3枚
[12:53:12 INF] 【投币前余额】 : 2
[12:53:12 INF] 因硬币余额不足，目标投币数调整为: 2
[12:53:47 INF] 【视频】好奇号发现了火星上曾经存在水的惊人线索
[12:53:51 ERR] 投币发生未预计异常：非法访问
[12:53:51 ERR] 投币失败，继续其他任务。失败信息:投币发生未预计异常：非法访问

**Comment by RayWangQvQ** [comment]
可能是cookie里的`buvid`导致的，之前解决分享失败，发现加上可以成功

**Comment by liuxiangxiangyuan** [comment]
用扫码登陆，没返回 `buvid` 这种咋搞

**Comment by lovemwy** [comment]
手动获取cookie后确实可以了

**Comment by RayWangQvQ** [comment]
> 用扫码登陆，没返回 `buvid` 这种咋搞

在想办法

**Comment by MachRB** [comment]
手动获取cookie就能解决分享及投币问题，扫码登录的确与bug。

**Comment by RayWangQvQ** [comment]
已于dev先行版修复：
![image](https://user-images.githubusercontent.com/31154238/219965158-8615e3a5-2396-4ba5-846a-b46271eb8238.png)

暂时先不发main，观察几天再说

**Comment by liuxiangxiangyuan** [comment]
我看 poll 接口扫码完成会返回一个 refresh_token，有计划开发可以自动去 refresh 吗？

**Comment by catlair** [comment]
> 我看 poll 接口扫码完成会返回一个 refresh_token，有计划开发可以自动去 refresh 吗？

1. 没卵用
2. 没有会逆向 wasm 的大手子

**Comment by Crazy-FuQing** [comment]
dev版本依旧报错，且漫画签到会报错
![image](https://user-images.githubusercontent.com/46838021/220275174-08444227-2380-457f-bc04-717e624dc091.png)
![1676963979513](https://user-images.githubusercontent.com/46838021/220275271-2c45344b-46cc-4a62-8f15-14920d5c640f.png)


[14:39:46 INF] 
---开始 投币 ---
[14:39:49 INF] 【今日已投】0枚
[14:39:49 INF] 【目标欲投】5枚
[14:39:49 INF] 【还需再投】5枚
[14:39:52 INF] 【投币前余额】 : 21
[14:40:26 INF] 【视频】哈哈哈哈！头回见放屁前摇！
[14:40:29 INF] 投币成功，经验+10 √
[14:41:04 INF] 【视频】罗翔领导过年收礼构成受贿罪吗？
[14:41:08 ERR] 投币发生未预计异常：非法访问
[14:41:08 ERR] 投币失败，继续其他任务。失败信息:投币发生未预计异常：非法访问

[14:41:08 INF] 
---开始 直播签到 ---
[14:41:13 INF] 【签到结果】失败
[14:41:13 INF] 【原因】今日已签到过,无法重复签到
Unhandled exception. [14:41:13 INF] 
---开始 漫画签到 ---
System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.AddCoinsForVideo(UserInfo userInfo) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 172
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()


## 执行结束...   耗时 187 秒

**Comment by RayWangQvQ** [comment]
不是漫画签到，是aop在异步情况下处理问题，投币的异常被跑到下个函数里了。
我来修。

**Comment by catlair** [comment]
> 不是漫画签到，是aop在异步情况下处理问题，投币的异常被跑到下个函数里了。 我来修。

说到漫画签到，我不明白这个漫画阅读有什么意义（除了给自己的历史加一个这个）

![image](https://user-images.githubusercontent.com/44313800/220358748-e08663ec-dae5-49a2-9397-ce59f90a470e.png)

**Comment by RayWangQvQ** [comment]
AOP的异步问题已解决，但投币确实还存在问题，刚试了下，5个币，投到第4个异常了，改天我再排查下把，应该还是cookie的问题

![image](https://user-images.githubusercontent.com/31154238/220414762-fed75988-b58d-4327-89d8-2785f3c0087e.png)

**Comment by RayWangQvQ** [comment]
> 说到漫画签到，我不明白这个漫画阅读有什么意义（除了给自己的历史加一个这个）
> 
很久以前合的PR了，应该是一个签到吧，具体意义我也不知道。
这个应该给个开关的，或者说其实每个任务都应该有个配置开关的，被我一直拖着没做，改天我来给写了吧。

**Comment by leeima** [comment]
手动换cookie就好了

**Comment by RayWangQvQ** [comment]
已于`v1.0.0`修复

![image](https://user-images.githubusercontent.com/31154238/221243229-5f20738a-00b4-495d-b9a1-d92192d31a12.png)

测了2天，5次投币都是成功，先把`1.0.0`版本出来了，如果还有问题，就后续小版本继续修吧

**Comment by Remonli** [comment]
@RayWangQvQ 然后这样又账号分享失败了呀。

**Comment by RayWangQvQ** [comment]
我的是正常的，你检查cookie，或者重新扫码登录试试
