### ISSUE TITLE
【Bug】程序不加载其所在目录下的配置文件

### ISSUE THREAD

**Issue by hui-shao** [RayWangQvQ/BiliBiliToolPro#464]
**版本号** v1.0.0

**运行环境** CentOS 7.9, 采用“下载到本地‘’部署方式，没有设置环境变量，使用 appsettings.json 进行配置。

**问题描述：**

当我在 `/root/Logs` 目录下执行 `../bili-task/Ray.BiliBiliTool.Console` 时，程序会报错，日志如下文。实际上，这是程序找不到配置文件。
我的预期是，程序应当加载 Ray.BiliBiliTool.Console 所在位置下的 appsettings.json，而不是去加载执行指令时的目录下的配置文件。
另：似乎 v0.4.6 没这个问题？可能和作者修复支持了 Ctrl + C 有关（因为改动了运行流程）

我不熟悉 .net ，但我在使用 python 时也常常遇到这种“程序所在目录”和“运行目录”的问题，python 中的解决方案是 `os.chdir(sys.path[0])` , 如此处理后可以切换到 py 文件所在目录并正确加载配置文件。

**日志信息：**

```
[root@r3c2 Logs]# ../bili-task/Ray.BiliBiliTool.Console 
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The expected physical path was '/root/Logs/appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo )
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean )
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 )
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Ray.BiliBiliTool.Console.Program.CreateHost(String[] args) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 43
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 23
   at Ray.BiliBiliTool.Console.Program.<Main>(String[] args)
Aborted
[root@r3c2 Logs]# 
```

**Comment by hui-shao** [comment]
**补充**
原先 0.4.6 版本时在 crontab 中这样配置即可正常运行：
`05 13 * * * /root/bili-task/Ray.BiliBiliTool.Console --runTasks="Daily&LiveFansMedal" > /root/bili-tasks-log.txt 2>&1`
但现在必须这样，先加一个切换目录，否则会报上文所述的错误：
`05 13 * * * cd /root/bili-task ; ./Ray.BiliBiliTool.Console --runTasks="Daily&LiveFansMedal" > /root/bili-tasks-log.txt 2>&1`

**Comment by RayWangQvQ** [comment]
收到，我来排查下。

但从用法上，推荐方式就是cd过去。

**Comment by hui-shao** [comment]
> 收到，我来排查下。
> 
> 但从用法上，推荐方式就是cd过去。

ok。保持现状也可。毕竟严格来说，这也算不上一个bug。
但希望在文档中注明一下，好像并没有关于此条目的说明。

p.s. 可以考虑用 docsify 建立一个文档站点，这样也更方便新手入门。

**Comment by RayWangQvQ** [comment]
嗯，刚才试了下，确实跟你描述的一样，原因是加了`hostBuilder.UseContentRoot(Directory.GetCurrentDirectory());`，删掉就变回以前了

![image](https://user-images.githubusercontent.com/31154238/221422940-ef7de06c-793c-4fa6-a119-142d676fe815.png)

但其实加上才是dotnet的官方标准，以前是我写漏了。

另外我发现，日志的Logs也被记到运行命令的目录下了，这个Serilog的标准，也不是我有意设置的。

但从常理上讲，确实又不该这样，存取都在二进制运行文件同目录才合理。。。

抽空我来研究下dotnet和Serilog为啥是当前这样设计，暂时建议先cd吧

**Comment by RayWangQvQ** [comment]
> p.s. 可以考虑用 docsify 建立一个文档站点，这样也更方便新手入门。

太高调了，还是闷声发大财吧，不搞大新闻

**Comment by hui-shao** [comment]
> 嗯，刚才试了下，确实跟你描述的一样，原因是加了`hostBuilder.UseContentRoot(Directory.GetCurrentDirectory());`，删掉就变回以前了
> 
> ![image](https://user-images.githubusercontent.com/31154238/221422940-ef7de06c-793c-4fa6-a119-142d676fe815.png)
> 
> 但其实加上才是dotnet的官方标准，以前是我写漏了。
> 
> 另外我发现，日志的Logs也被记到运行命令的目录下了，这个Serilog的标准，也不是我有意设置的。
> 
> 但从常理上讲，确实又不该这样，存取都在二进制运行文件同目录才合理。。。
> 
> 抽空我来研究下dotnet和Serilog为啥是当前这样设计，暂时建议先cd吧

的确，Log 的问题我也发现了，不过目前用着 cd 也是完全没问题的。期待后续有更好的方案吧。
