### ISSUE TITLE
【Bug】仍然存在int转换不了问题

### ISSUE THREAD

**Issue by Salomens** [RayWangQvQ/BiliBiliToolPro#466]
版本号：1.0
运行环境：docker 

问题描述：直播间报错
点赞直播间失败，继续其他任务。失败信息:The JSON value could not be converted to System.Int32. Path: $.data.mid | LineNumber: 0 | BytePositionInLine: 62.

日志信息：root@ad8b5f723406:/app# dotnet Ray.BiliBiliTool.Console.dll --runTasks=LiveFansMedal
[11:15:24 INF] BiliBiliToolPro 开始运行...

[11:15:24 INF] 【目标任务】LiveFansMedal
[11:15:24 INF] 【账号个数】1个

[11:15:24 INF] 随机休眠10分钟

[11:25:24 INF] ######### 账号 1 #########

[11:25:25 INF] =====开始 直播间互动 =====

[11:25:25 INF] ---开始 发送弹幕 ---
[11:25:25 INF] 检测到直播 Cookie 未正确配置，尝试自动配置中...
[11:25:42 INF] 直播 Cookie 配置成功！
[11:25:42 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
[11:25:52 INF] 【主播】周杉 
[11:26:17 INF] 【主播】暴走漫画 
[11:26:41 INF] 【主播】小片片说大片 
[11:27:07 INF] 【主播】记录生活的蛋黄派 
[11:27:38 INF] 【主播】陈怀安_Aaa 
[11:28:12 INF] 【主播】一只香酥霏霏 
[11:28:30 ERR] [REQUEST]
GET /x/space/wbi/acc/info?mid=3493089022839682 HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Mon, 27 Feb 2023 03:28:30 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST,PUT,DELETE
Access-Control-Allow-Origin: https://www.bilibili.com
Access-Control-Expose-Headers: X-Rid-Result
Bili-Status-Code: 0
Bili-Trace-Id: 09179935f2fe8700
Vary: Origin
X-Bili-Trace-Id: e6bd281180d85e1409179935f2fe8700
X-Rid-Result: 2
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip,x-risk-header
Cross-Origin-Resource-Policy: cross-origin
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from blzone01
Content-Type: application/json; charset=utf-8
Expires: Mon, 27 Feb 2023 03:28:29 GMT
Content-Length: 2602

{"code":0,"message":"0","ttl":1,"data":{"mid":3493089022839682,"name":"一只香酥霏霏","sex":"保密","face":"https://i1.hdslb.com/bfs/face/f9d0bdcdce2732506956e2d57741b7611934caa9.jpg","face_nft":0,"face_nft_type":0,"sign":"拒绝画饼","rank":10000,"level":3,"jointime":0,"moral":0,"silence":0,"coins":0,"fans_badge":true,"fans_medal":{"show":false,"wear":false,"medal":null},"official":{"role":0,"title":"","desc":"","type":-1},"vip":{"type":1,"status":0,"due_date":1672934400000,"vip_pay_type":0,"theme_type":0,"label":{"path":"","text":"","label_theme":"","text_color":"","bg_style":0,"bg_color":"","border_color":"","use_img_label":true,"img_label_uri_hans":"","img_label_uri_hant":"","img_label_uri_hans_static":"https://i0.hdslb.com/bfs/vip/d7b702ef65a976b20ed854cbd04cb9e27341bb79.png","img_label_uri_hant_static":"https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/KJunwh19T5.png"},"avatar_subscript":0,"nickname_color":"","role":0,"avatar_subscript_url":"","tv_vip_status":0,"tv_vip_pay_type":0},"pendant":{"pid":0,"name":"","image":"","expire":0,"image_enhance":"","image_enhance_frame":""},"nameplate":{"nid":40,"name":"老司机","image":"https://i1.hdslb.com/bfs/face/88013f24627e8db0ee3261adf7c8a7d0077c4d4e.png","image_small":"https://i0.hdslb.com/bfs/face/075ed5043bdabcbe4f8bc6d730d630cb4b6ade13.png","level":"高级勋章","condition":"直播主播等级\u003e=20级"},"user_honour_info":{"mid":0,"colour":null,"tags":[]},"is_followed":false,"top_photo":"http://i0.hdslb.com/bfs/space/cb1c3ef50e22b6096fde67febe863494caefebad.png","theme":{},"sys_notice":{},"live_room":{"roomStatus":1,"liveStatus":0,"url":"https://live.bilibili.com/26529551?broadcast_type=0\u0026is_room_feed=1","title":"微胖天花板","cover":"http://i0.hdslb.com/bfs/live/user_cover/7d6ce91c69b4d8966e7c8a0209e98429f39bd278.jpg","roomid":26529551,"roundStatus":0,"broadcast_type":0,"watched_show":{"switch":true,"num":54,"text_small":"54","text_large":"54人看过","icon":"https://i0.hdslb.com/bfs/live/a725a9e61242ef44d764ac911691a7ce07f36c1d.png","icon_location":"","icon_web":"https://i0.hdslb.com/bfs/live/8d9d0f33ef8bf6f308742752d13dd0df731df19c.png"}},"birthday":"11-11","school":{"name":""},"profession":{"name":"","department":"","title":"","is_show":0},"tags":null,"series":{"user_upgrade_status":3,"show_upgrade_window":false},"is_senior_member":0,"mcn_info":null,"gaia_res_type":0,"gaia_data":null,"is_risk":false,"elec":{"show_info":{"show":false,"state":-1,"title":"","icon":"","jump_url":""}},"contract":{"is_display":false,"is_follow_display":false}}

[EXCEPTION]
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.mid | LineNumber: 0 | BytePositionInLine: 62.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at WebApiClientCore.ApiResponseContextExtensions.JsonDeserializeAsync(ApiResponseContext context, Type objType)
   at WebApiClientCore.Attributes.JsonReturnAttribute.SetResultAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

[ELAPSED] 00:00:18.2430657
[11:28:30 ERR] 发送弹幕失败，继续其他任务。失败信息:The JSON value could not be converted to System.Int32. Path: $.data.mid | LineNumber: 0 | BytePositionInLine: 62.

[11:28:30 INF] -------结束-------

[11:28:30 INF] ---开始 点赞直播间 ---
[11:28:30 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
[11:28:44 INF] 【主播】周杉 
[11:29:18 INF] 【主播】暴走漫画 
[11:29:47 INF] 【主播】小片片说大片 
[11:30:12 INF] 【主播】记录生活的蛋黄派 
[11:30:45 INF] 【主播】陈怀安_Aaa 
[11:31:15 INF] 【主播】一只香酥霏霏 
[11:31:28 ERR] [REQUEST]
GET /x/space/wbi/acc/info?mid=3493089022839682 HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Mon, 27 Feb 2023 03:31:28 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST,PUT,DELETE
Access-Control-Allow-Origin: https://www.bilibili.com
Access-Control-Expose-Headers: X-Rid-Result
Bili-Status-Code: 0
Bili-Trace-Id: d318cd817aaea0f4
Vary: Origin
X-Bili-Trace-Id: e18226a7c664381bd318cd817aaea0f4
X-Rid-Result: 2
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip,x-risk-header
Cross-Origin-Resource-Policy: cross-origin
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from blzone01
Content-Type: application/json; charset=utf-8
Expires: Mon, 27 Feb 2023 03:31:27 GMT
Content-Length: 2602

{"code":0,"message":"0","ttl":1,"data":{"mid":3493089022839682,"name":"一只香酥霏霏","sex":"保密","face":"https://i1.hdslb.com/bfs/face/f9d0bdcdce2732506956e2d57741b7611934caa9.jpg","face_nft":0,"face_nft_type":0,"sign":"拒绝画饼","rank":10000,"level":3,"jointime":0,"moral":0,"silence":0,"coins":0,"fans_badge":true,"fans_medal":{"show":false,"wear":false,"medal":null},"official":{"role":0,"title":"","desc":"","type":-1},"vip":{"type":1,"status":0,"due_date":1672934400000,"vip_pay_type":0,"theme_type":0,"label":{"path":"","text":"","label_theme":"","text_color":"","bg_style":0,"bg_color":"","border_color":"","use_img_label":true,"img_label_uri_hans":"","img_label_uri_hant":"","img_label_uri_hans_static":"https://i0.hdslb.com/bfs/vip/d7b702ef65a976b20ed854cbd04cb9e27341bb79.png","img_label_uri_hant_static":"https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/KJunwh19T5.png"},"avatar_subscript":0,"nickname_color":"","role":0,"avatar_subscript_url":"","tv_vip_status":0,"tv_vip_pay_type":0},"pendant":{"pid":0,"name":"","image":"","expire":0,"image_enhance":"","image_enhance_frame":""},"nameplate":{"nid":40,"name":"老司机","image":"https://i2.hdslb.com/bfs/face/88013f24627e8db0ee3261adf7c8a7d0077c4d4e.png","image_small":"https://i0.hdslb.com/bfs/face/075ed5043bdabcbe4f8bc6d730d630cb4b6ade13.png","level":"高级勋章","condition":"直播主播等级\u003e=20级"},"user_honour_info":{"mid":0,"colour":null,"tags":[]},"is_followed":false,"top_photo":"http://i2.hdslb.com/bfs/space/cb1c3ef50e22b6096fde67febe863494caefebad.png","theme":{},"sys_notice":{},"live_room":{"roomStatus":1,"liveStatus":0,"url":"https://live.bilibili.com/26529551?broadcast_type=0\u0026is_room_feed=1","title":"微胖天花板","cover":"http://i0.hdslb.com/bfs/live/user_cover/7d6ce91c69b4d8966e7c8a0209e98429f39bd278.jpg","roomid":26529551,"roundStatus":0,"broadcast_type":0,"watched_show":{"switch":true,"num":54,"text_small":"54","text_large":"54人看过","icon":"https://i0.hdslb.com/bfs/live/a725a9e61242ef44d764ac911691a7ce07f36c1d.png","icon_location":"","icon_web":"https://i0.hdslb.com/bfs/live/8d9d0f33ef8bf6f308742752d13dd0df731df19c.png"}},"birthday":"11-11","school":{"name":""},"profession":{"name":"","department":"","title":"","is_show":0},"tags":null,"series":{"user_upgrade_status":3,"show_upgrade_window":false},"is_senior_member":0,"mcn_info":null,"gaia_res_type":0,"gaia_data":null,"is_risk":false,"elec":{"show_info":{"show":false,"state":-1,"title":"","icon":"","jump_url":""}},"contract":{"is_display":false,"is_follow_display":false}}

[EXCEPTION]
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.mid | LineNumber: 0 | BytePositionInLine: 62.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at WebApiClientCore.ApiResponseContextExtensions.JsonDeserializeAsync(ApiResponseContext context, Type objType)
   at WebApiClientCore.Attributes.JsonReturnAttribute.SetResultAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

[ELAPSED] 00:00:12.2217955
[11:31:28 ERR] 点赞直播间失败，继续其他任务。失败信息:The JSON value could not be converted to System.Int32. Path: $.data.mid | LineNumber: 0 | BytePositionInLine: 62.

[11:31:28 INF] --------结束--------

[11:31:28 INF] ---开始 直播时长挂机 ---
[11:31:28 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
[11:31:48 INF] 【主播】周杉 
[11:32:17 INF] 【主播】暴走漫画 
[11:32:39 INF] 【主播】小片片说大片 
[11:33:07 INF] 【主播】记录生活的蛋黄派 
[11:33:33 INF] 【主播】陈怀安_Aaa 
[11:34:10 INF] 【主播】一只香酥霏霏 
[11:34:30 ERR] [REQUEST]
GET /x/space/wbi/acc/info?mid=3493089022839682 HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Mon, 27 Feb 2023 03:34:30 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST,PUT,DELETE
Access-Control-Allow-Origin: https://www.bilibili.com
Access-Control-Expose-Headers: X-Rid-Result
Bili-Status-Code: 0
Bili-Trace-Id: 5c0768eea9d4b013
Vary: Origin
X-Bili-Trace-Id: 62e3320b9c0267ef5c0768eea9d4b013
X-Rid-Result: 2
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip,x-risk-header
Cross-Origin-Resource-Policy: cross-origin
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from blzone03
Content-Type: application/json; charset=utf-8
Expires: Mon, 27 Feb 2023 03:34:29 GMT
Content-Length: 2602

{"code":0,"message":"0","ttl":1,"data":{"mid":3493089022839682,"name":"一只香酥霏霏","sex":"保密","face":"https://i1.hdslb.com/bfs/face/f9d0bdcdce2732506956e2d57741b7611934caa9.jpg","face_nft":0,"face_nft_type":0,"sign":"拒绝画饼","rank":10000,"level":3,"jointime":0,"moral":0,"silence":0,"coins":0,"fans_badge":true,"fans_medal":{"show":false,"wear":false,"medal":null},"official":{"role":0,"title":"","desc":"","type":-1},"vip":{"type":1,"status":0,"due_date":1672934400000,"vip_pay_type":0,"theme_type":0,"label":{"path":"","text":"","label_theme":"","text_color":"","bg_style":0,"bg_color":"","border_color":"","use_img_label":true,"img_label_uri_hans":"","img_label_uri_hant":"","img_label_uri_hans_static":"https://i0.hdslb.com/bfs/vip/d7b702ef65a976b20ed854cbd04cb9e27341bb79.png","img_label_uri_hant_static":"https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/KJunwh19T5.png"},"avatar_subscript":0,"nickname_color":"","role":0,"avatar_subscript_url":"","tv_vip_status":0,"tv_vip_pay_type":0},"pendant":{"pid":0,"name":"","image":"","expire":0,"image_enhance":"","image_enhance_frame":""},"nameplate":{"nid":40,"name":"老司机","image":"https://i2.hdslb.com/bfs/face/88013f24627e8db0ee3261adf7c8a7d0077c4d4e.png","image_small":"https://i0.hdslb.com/bfs/face/075ed5043bdabcbe4f8bc6d730d630cb4b6ade13.png","level":"高级勋章","condition":"直播主播等级\u003e=20级"},"user_honour_info":{"mid":0,"colour":null,"tags":[]},"is_followed":false,"top_photo":"http://i1.hdslb.com/bfs/space/cb1c3ef50e22b6096fde67febe863494caefebad.png","theme":{},"sys_notice":{},"live_room":{"roomStatus":1,"liveStatus":0,"url":"https://live.bilibili.com/26529551?broadcast_type=0\u0026is_room_feed=1","title":"微胖天花板","cover":"http://i0.hdslb.com/bfs/live/user_cover/7d6ce91c69b4d8966e7c8a0209e98429f39bd278.jpg","roomid":26529551,"roundStatus":0,"broadcast_type":0,"watched_show":{"switch":true,"num":54,"text_small":"54","text_large":"54人看过","icon":"https://i0.hdslb.com/bfs/live/a725a9e61242ef44d764ac911691a7ce07f36c1d.png","icon_location":"","icon_web":"https://i0.hdslb.com/bfs/live/8d9d0f33ef8bf6f308742752d13dd0df731df19c.png"}},"birthday":"11-11","school":{"name":""},"profession":{"name":"","department":"","title":"","is_show":0},"tags":null,"series":{"user_upgrade_status":3,"show_upgrade_window":false},"is_senior_member":0,"mcn_info":null,"gaia_res_type":0,"gaia_data":null,"is_risk":false,"elec":{"show_info":{"show":false,"state":-1,"title":"","icon":"","jump_url":""}},"contract":{"is_display":false,"is_follow_display":false}}

[EXCEPTION]
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.mid | LineNumber: 0 | BytePositionInLine: 62.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at WebApiClientCore.ApiResponseContextExtensions.JsonDeserializeAsync(ApiResponseContext context, Type objType)
   at WebApiClientCore.Attributes.JsonReturnAttribute.SetResultAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

[ELAPSED] 00:00:20.2068032
[11:34:30 ERR] 直播时长挂机失败，继续其他任务。失败信息:The JSON value could not be converted to System.Int32. Path: $.data.mid | LineNumber: 0 | BytePositionInLine: 62.

[11:34:30 INF] ---------结束---------

[11:34:30 INF] ==========结束==========

[11:34:30 INF] 

========================

 v1.0.0 开源 by https://github.com/RayWangQvQ/BiliBiliToolPro

[11:34:30 INF] ·开始推送·LiveFansMedal任务·
2023-02-27T03:34:30.7477555Z 开始推送到:Server酱Turbo版
2023-02-27T03:34:31.9405751Z Response status: OK.
2023-02-27T03:34:31.9407275Z Response content: {"code":0,"message":"","data":{"pushid":"111813521","readkey":"SCT552s6UpELVOG","error":"SUCCESS","errno":0}}.

[11:34:31 INF] 运行环境：Production
[11:34:31 INF] 应用目录：/app

[11:34:31 INF] 运行结束

**Comment by RayWangQvQ** [comment]
收到

**Comment by RayWangQvQ** [comment]
dev已修复，稍后发布main

**Comment by Salomens** [comment]
@RayWangQvQ dev已解决，谢谢
