### ISSUE TITLE
【Bug】青龙面板扫码登录：程序异常终止，原因：Cookie字符串为空

### ISSUE THREAD

**Issue by vip198926** [RayWangQvQ/BiliBiliToolPro#467]
版本号：最新版（先行版）
运行环境：Linux，青龙面板

问题描述：扫码登录时出现 程序异常终止，原因：Cookie字符串为空

日志信息：
[21:06:39 INF] 我数到10，动作快点
[21:06:39 INF] [1]等待扫描...
[21:07:02 INF] 扫描成功！
[21:07:03 ERR] 程序发生异常：Cookie字符串为空
[21:07:03 INF] --------结束--------

[21:07:03 ERR] 程序发生异常：Cookie字符串为空
[21:07:03 INF] =========结束=========

[21:07:03 ERR] 程序异常终止，原因：Cookie字符串为空
[21:07:03 INF] 运行环境：Development
[21:07:03 INF] 应用目录：/ql/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console

[21:07:03 INF] 运行结束
[21:07:03 FTL] Host terminated unexpectedly!
System.Exception: Cookie字符串为空
   at Ray.BiliBiliTool.Infrastructure.Cookie.CookieInfo.Check() in /ql/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Infrastructure/Cookie/CookieInfo.cs:line 22
   at Ray.BiliBiliTool.Agent.BiliCookie.Check() in /ql/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Agent/BiliCookie.cs:line 64
   at Ray.BiliBiliTool.DomainService.LoginDomainService.LoginByQrCodeAsync(CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.DomainService/LoginDomainService.cs:line 106
   at Ray.BiliBiliTool.Application.LoginTaskAppService.QrCodeLoginAsync(CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 60
   at Ray.BiliBiliTool.Application.LoginTaskAppService.DoTaskAsync(CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 47
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 166
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /ql/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Program.cs:line 27

## 执行结束... 2023-02-27 21:07:03 耗时 62 秒

**Comment by RayWangQvQ** [comment]
已修复
