### ISSUE TITLE
【其他】扫码登录报错

### ISSUE THREAD

**Issue by treasunew** [RayWangQvQ/BiliBiliToolPro#502]
![image](https://user-images.githubusercontent.com/104483693/224616768-dcdbe295-b044-4105-9006-905935ffb3e2.png)

**Comment by RayWangQvQ** [comment]
青龙版本号和debug日志呢？提issue遵守下规则哈

**Comment by RayWangQvQ** [comment]
我自己测试，在青龙v2.15.2和v2.15.9都是没问题的：

![image](https://user-images.githubusercontent.com/31154238/224758728-9384402b-49f4-466a-9acf-5c02a7d08de9.png)

**Comment by treasunew** [comment]
> 我自己测试，在青龙v2.15.2和v2.15.9都是没问题的：
> 
> ![image](https://user-images.githubusercontent.com/31154238/224758728-9384402b-49f4-466a-9acf-5c02a7d08de9.png)

不好意思啦，没注意看issue。版本是2.10.7
另外debug就是日志吗
我将项目下载到本地就没问题
日志如下
[13:32:05 INF] ---开始 持久化Cookie ---
[13:32:05 INF] 当前运行平台：QingLong
[13:32:16 ERR] 程序发生异常：不支持将ContentType为 text/html; charset=utf-8 的内容转换为Ray.BiliBiliTool.Agent.QingLong.QingLongGenericResponse`1[System.Collections.Generic.List`1[Ray.BiliBiliTool.Agent.QingLong.QingLongEnv]]
[13:32:16 INF] ------------结束------------

[13:32:16 ERR] 程序发生异常：不支持将ContentType为 text/html; charset=utf-8 的内容转换为Ray.BiliBiliTool.Agent.QingLong.QingLongGenericResponse`1[System.Collections.Generic.List`1[Ray.BiliBiliTool.Agent.QingLong.QingLongEnv]]
[13:32:16 INF] =========结束=========

[13:32:16 ERR] 程序异常终止，原因：不支持将ContentType为 text/html; charset=utf-8 的内容转换为Ray.BiliBiliTool.Agent.QingLong.QingLongGenericResponse`1[System.Collections.Generic.List`1[Ray.BiliBiliTool.Agent.QingLong.QingLongEnv]]
[13:32:16 INF] 运行环境：Development
[13:32:16 INF] 应用目录：/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[13:32:16 INF] 运行结束
[13:32:16 FTL] Host terminated unexpectedly!
System.Net.Http.HttpRequestException: 不支持将ContentType为 text/html; charset=utf-8 的内容转换为Ray.BiliBiliTool.Agent.QingLong.QingLongGenericResponse`1[System.Collections.Generic.List`1[Ray.BiliBiliTool.Agent.QingLong.QingLongEnv]]
 ---> WebApiClientCore.Exceptions.ApiReturnNotSupportedExteption: 不支持将ContentType为 text/html; charset=utf-8 的内容转换为Ray.BiliBiliTool.Agent.QingLong.QingLongGenericResponse`1[System.Collections.Generic.List`1[Ray.BiliBiliTool.Agent.QingLong.QingLongEnv]]
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(ApiRequestContext request)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   --- End of inner exception stack trace ---
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   at Ray.BiliBiliTool.DomainService.LoginDomainService.SaveCookieToQinLongAsync(BiliCookie ckInfo, CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/LoginDomainService.cs:line 216
   at Ray.BiliBiliTool.Application.LoginTaskAppService.SaveCookieAsync(BiliCookie ckInfo, CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 80
   at Ray.BiliBiliTool.Application.LoginTaskAppService.DoTaskAsync(CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 54
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 188
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 64
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 29

**Comment by RayWangQvQ** [comment]
可以升级青龙版本解决

**Comment by treasunew** [comment]
谢谢大佬，我升级试试

在7楼 ***@***.***>于2023年3月14日 周二20:03写道：
