### ISSUE TITLE
V2.0.0 本地 打开报错 

### ISSUE THREAD

**Issue by junmoyer** [RayWangQvQ/BiliBiliToolPro#552]
版本号：V2.0.0
运行环境：Win-64 本地

问题描述：打开就报错 上个版本没问题  虽然没权限 但是币是投了的

无日志
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Ray.Serilog.Sinks.Batched, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, processorArchitecture=MSIL'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Ray.Serilog.Sinks.Batched, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, processorArchitecture=MSIL'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack , ObjectHandleOnStack , StackCrawlMarkHandle , Boolean , ObjectHandleOnStack , ObjectHandleOnStack )
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName , RuntimeAssembly , StackCrawlMark& , Boolean , AssemblyLoadContext )
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName , StackCrawlMark& , AssemblyLoadContext )
   at System.Reflection.Assembly.Load(AssemblyName )
   at Serilog.Settings.Configuration.ConfigurationReader.LoadConfigurationAssemblies(IConfigurationSection section, AssemblyFinder assemblyFinder)
   at Serilog.Settings.Configuration.ConfigurationReader..ctor(IConfigurationSection configSection, AssemblyFinder assemblyFinder, IConfiguration configuration)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, String sectionName, DependencyContext dependencyContext)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, DependencyContext dependencyContext)
   at Ray.BiliBiliTool.Console.Program.<>c.<CreateHostBuilder>b__2_2(HostBuilderContext hostBuilderContext, ILoggingBuilder loggingBuilder)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass4_1.<ConfigureLogging>b__1(ILoggingBuilder )
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection , Action`1 )
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass4_0.<ConfigureLogging>b__0(HostBuilderContext , IServiceCollection )
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Ray.BiliBiliTool.Console.Program.CreateHost(String[] args)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args)
   at Ray.BiliBiliTool.Console.Program.<Main>(String[] args)

**Comment by RayWangQvQ** [comment]
最新版是否已解决
