### ISSUE TITLE
【Bug】win x64 本地配置报错 Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by mavnp** [RayWangQvQ/BiliBiliToolPro#581]
版本号：2.0.1
运行环境：win11 x64

问题描述：执行日常任务时报错 Object reference not set to an instance of an object.

日志信息：2023-07-22 21:54:19.949 +08:00 [INF] ---开始 签到 ---
2023-07-22 21:55:06.146 +08:00 [DBG] [REQUEST]
POST /pgc/activity/score/task/sign HTTP/1.1
Host: api.bilibili.com
Referer: https://big.bilibili.com/mobile/bigPoint/task
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.158 Mobile Safari/537.36 os/android model/MuMu build/6720300 osVer/6.0.1 sdkInt/23 network/2 BiliApp/6720300 mobi_app/android channel/html5_search_baidu Buvid/XZFC135F5263B6897C8A4BE7AEB125BBF10F8 sessionID/72d3f4c9 innerVer/6720310 c_locale/zh_CN s_locale/zh_CN disable_rcmd/0 6.72.0 os/android model/MuMu mobi_app/android build/6720300 channel/html5_search_baidu innerVer/6720310 osVer/6.0.1 network/2
Accept: application/json; q=0.001, application/xml; q=0.001
Content-Type: application/x-www-form-urlencoded

statistics=%7b%22appId%22%3a1%2c%22platform%22%3a3%2c%22version%22%3a%226.85.0%22%2c%22abtest%22%3a%22%22%7d

[RESPONSE]
HTTP/1.1 200 OK
Date: Sat, 22 Jul 2023 13:55:06 GMT
Connection: keep-alive
Bili-Status-Code: 6007000
X-Bili-Trace-Id: 74cc1ff691b0e1887b6d49799264bbdf
X-Cache-Webcdn: BYPASS from blzone08
Content-Type: application/json
Content-Length: 96

{"code":6007000,"message":"抱歉，您的账号存在风险，暂时无法参与本任务哦~"}

[ELAPSED] 00:00:46.1781077
2023-07-22 21:55:06.221 +08:00 [ERR] 签到失败，继续其他任务。失败信息:{"Code":6007000,"Message":"抱歉，您的账号存在风险，暂时无法参与本任务哦~","Data":null}

2023-07-22 21:55:06.223 +08:00 [INF] -----结束-----

2023-07-22 21:55:06.226 +08:00 [INF] ---开始 福利任务 ---
2023-07-22 21:55:06.227 +08:00 [ERR] 福利任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2023-07-22 21:55:06.227 +08:00 [INF] -------结束-------

2023-07-22 21:55:06.231 +08:00 [INF] ---开始 体验任务 ---
2023-07-22 21:55:06.232 +08:00 [ERR] 体验任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2023-07-22 21:55:06.232 +08:00 [INF] -------结束-------

2023-07-22 21:55:06.235 +08:00 [INF] ---开始 浏览追番频道页10秒 ---
2023-07-22 21:55:06.236 +08:00 [ERR] 浏览追番频道页10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2023-07-22 21:55:06.237 +08:00 [INF] -------------结束-------------

2023-07-22 21:55:06.240 +08:00 [INF] ---开始 浏览影视频道页10秒 ---
2023-07-22 21:55:06.241 +08:00 [ERR] 浏览影视频道页10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2023-07-22 21:55:06.242 +08:00 [INF] -------------结束-------------

2023-07-22 21:55:06.243 +08:00 [INF] ---开始 浏览会员购页面10秒 ---
2023-07-22 21:55:06.243 +08:00 [INF] 待实现...
2023-07-22 21:55:06.244 +08:00 [INF] -------------结束-------------

2023-07-22 21:55:06.246 +08:00 [INF] ---开始 观看任意正片内容 ---
2023-07-22 21:55:06.247 +08:00 [ERR] 观看任意正片内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2023-07-22 21:55:06.248 +08:00 [INF] -----------结束-----------

2023-07-22 21:55:06.250 +08:00 [INF] ---开始 购买单点付费影片（仅领取） ---
2023-07-22 21:55:06.251 +08:00 [ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2023-07-22 21:55:06.252 +08:00 [INF] ----------------结束----------------

2023-07-22 21:55:06.254 +08:00 [INF] ---开始 购买指定大会员产品（仅领取） ---
2023-07-22 21:55:06.255 +08:00 [ERR] 购买指定大会员产品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2023-07-22 21:55:06.255 +08:00 [INF] -----------------结束-----------------

2023-07-22 21:55:06.258 +08:00 [INF] ---开始 购买指定会员购商品（仅领取） ---
2023-07-22 21:55:06.258 +08:00 [ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2023-07-22 21:55:06.259 +08:00 [INF] -----------------结束-----------------

2023-07-22 21:55:06.259 +08:00 [ERR] 程序发生异常：Object reference not set to an instance of an object.
2023-07-22 21:55:06.260 +08:00 [INF] ===========结束===========

2023-07-22 21:55:06.286 +08:00 [WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken)
2023-07-22 21:55:06.287 +08:00 [INF] 

========================

 v2.0.1 开源 by https://github.com/RayWangQvQ/BiliBiliToolPro

2023-07-22 21:55:06.288 +08:00 [INF] ·开始推送·Daily&VipBigPoint任务·
2023-07-22 21:55:06.574 +08:00 [INF] 运行环境：Production
2023-07-22 21:55:06.575 +08:00 [INF] 应用目录：D:\下载\bilibili-tool-pro-v2.0.1-win-x64\win-x64\

2023-07-22 21:55:06.575 +08:00 [INF] 运行结束

**Comment by RayWangQvQ** [comment]
更新最新版试试
