### ISSUE TITLE
【Bug】直播时长挂机失败，青龙是最新的，脚本重新拉取最新的。

### ISSUE THREAD

**Issue by jianjam** [RayWangQvQ/BiliBiliToolPro#606]
版本号：V.2.0.1
运行环境：运行在NAS 的docker上

问题描述：直播挂机任务失败，青龙是最新的，2.16.2，脚本删除了重新拉取问题依旧。

日志信息：
`## 开始执行... 2023-09-14 02:05:01

任务随机延迟 582 秒，配置文件参数 RandomDelay 置空可取消延迟 

./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.121

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

  ____               ____    _   _____           _  
 |  _ \ __ _ _   _  | __ ) _| |_|_   _|__   ___ | | 
 | |_) / _` | | | | |  _ \(_) (_) | |/ _ \ / _ \| | 
 |  _ < (_| | |_| | | |_) | | | | | | (_) | (_) | | 
 |_| \_\__,_|\__, | |____/|_|_|_| |_|\___/ \___/|_| 
             |___/                                  

[02:14:50 INF] BiliBiliToolPro 开始运行...

[02:14:50 INF] 【账号个数】1个

[02:14:50 INF] 【目标任务】LiveFansMedal
[02:14:50 INF] ######### 账号 1 #########

[02:14:50 INF] =====开始 直播间互动 =====

[02:14:50 INF] ---开始 发送弹幕 ---
[02:14:50 INF] 检测到直播 Cookie 未正确配置，尝试自动配置中...
[02:14:55 INF] 直播 Cookie 配置成功！
[02:14:55 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
[02:14:58 INF] 【主播】棋手战鹰 
[02:15:12 INF] 【主播】Army菌 
[02:15:28 INF] 【主播】PCEVA评测室 
[02:15:43 INF] 【主播】嘻咦啊看 
[02:15:56 INF] 【主播】随遇谦 
[02:16:08 INF] 【主播】柯洁 
[02:16:24 INF] 【主播】那岩KJMX 
[02:16:38 INF] 【主播】浙艺没有菲戈 
[02:16:53 INF] 【主播】极客湾Geekerwan 
[02:17:10 INF] 【主播】Jason-老湿 
[02:17:25 INF] 【直播间】棋手战鹰
[02:17:25 INF] 【粉丝牌】鹰快飞
[02:17:25 INF] 正在发送弹幕...
[02:17:28 INF] 【直播间】Army菌
[02:17:28 INF] 【粉丝牌】Army菌
[02:17:28 INF] 正在发送弹幕...
[02:17:34 INF] 【直播间】PCEVA评测室
[02:17:34 INF] 【粉丝牌】PCEVA
[02:17:34 INF] 正在发送弹幕...
[02:17:36 INF] 【弹幕发送】成功~，你和主播 棋手战鹰 的亲密值增加了100！
[02:17:37 INF] 【直播间】嘻咦啊看
[02:17:37 INF] 【粉丝牌】醉虾
[02:17:37 INF] 正在发送弹幕...
[02:17:44 INF] 【直播间】随遇谦
[02:17:44 INF] 【粉丝牌】苍蝇侠
[02:17:44 INF] 正在发送弹幕...
[02:17:48 INF] 【弹幕发送】成功~，你和主播 Army菌 的亲密值增加了100！
[02:17:49 INF] 【弹幕发送】成功~，你和主播 PCEVA评测室 的亲密值增加了100！
[02:17:50 INF] 【直播间】柯洁
[02:17:50 INF] 【粉丝牌】小柯爱
[02:17:50 INF] 正在发送弹幕...
[02:17:55 INF] 【直播间】那岩KJMX
[02:17:55 INF] 【粉丝牌】那岩
[02:17:55 INF] 正在发送弹幕...
[02:17:58 INF] 【弹幕发送】成功~，你和主播 随遇谦 的亲密值增加了100！
[02:17:59 INF] 【弹幕发送】成功~，你和主播 嘻咦啊看 的亲密值增加了100！
[02:18:00 INF] 【直播间】浙艺没有菲戈
[02:18:00 INF] 【粉丝牌】菲嘎
[02:18:00 INF] 正在发送弹幕...
[02:18:03 INF] 【直播间】极客湾Geekerwan
[02:18:03 INF] 【粉丝牌】极客
[02:18:03 INF] 正在发送弹幕...
[02:18:04 INF] 【弹幕发送】成功~，你和主播 柯洁 的亲密值增加了100！
[02:18:08 INF] 【直播间】Jason-老湿
[02:18:08 INF] 【粉丝牌】托尼龟
[02:18:08 INF] 正在发送弹幕...
[02:18:12 INF] 【弹幕发送】成功~，你和主播 那岩KJMX 的亲密值增加了100！
[02:18:15 INF] 【弹幕发送】成功~，你和主播 极客湾Geekerwan 的亲密值增加了100！
[02:18:15 INF] -------结束-------

[02:18:15 INF] ---开始 点赞直播间 ---
[02:18:15 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
[02:18:17 INF] 【弹幕发送】成功~，你和主播 浙艺没有菲戈 的亲密值增加了100！
[02:18:18 INF] 【主播】棋手战鹰 
[02:18:25 INF] 【弹幕发送】成功~，你和主播 Jason-老湿 的亲密值增加了100！
[02:18:39 INF] 【主播】Army菌 
[02:18:52 INF] 【主播】PCEVA评测室 
[02:19:05 INF] 【主播】嘻咦啊看 
[02:19:22 INF] 【主播】随遇谦 
[02:19:37 INF] 【主播】柯洁 
[02:19:56 INF] 【主播】那岩KJMX 
[02:20:10 INF] 【主播】浙艺没有菲戈 
[02:20:21 INF] 【主播】极客湾Geekerwan 
[02:20:34 INF] 【主播】Jason-老湿 
[02:20:59 INF] 【点赞直播间】23141761 完成
[02:21:06 INF] 【点赞直播间】3195859 完成
[02:21:09 INF] 【点赞直播间】6707764 完成
[02:21:16 INF] 【点赞直播间】4552074 完成
[02:21:22 INF] 【点赞直播间】21818798 完成
[02:21:25 INF] 【点赞直播间】23555200 完成
[02:21:31 INF] 【点赞直播间】554456 完成
[02:21:37 INF] 【点赞直播间】24402390 完成
[02:21:41 INF] 【点赞直播间】544843 完成
[02:21:46 INF] --------结束--------

[02:21:46 INF] ---开始 直播时长挂机 ---
[02:21:46 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
[02:21:46 INF] 【点赞直播间】22200991 完成
[02:21:53 INF] 【主播】棋手战鹰 
[02:22:12 INF] 【主播】Army菌 
[02:22:32 INF] 【主播】PCEVA评测室 
[02:22:47 INF] 【主播】嘻咦啊看 
[02:23:03 INF] 【主播】随遇谦 
[02:23:18 INF] 【主播】柯洁 
[02:23:31 INF] 【主播】那岩KJMX 
[02:23:46 INF] 【主播】浙艺没有菲戈 
[02:24:04 INF] 【主播】极客湾Geekerwan 
[02:24:20 INF] 【主播】Jason-老湿 
[02:24:37 ERR] [REQUEST]
POST /xlive/data-interface/v1/x25Kn/E HTTP/1.1
Host: live-trace.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded

id=%5b3%2c354%2c0%2c23141761%5d&ruid=2051617240&ts=1694629474811&is_patch=0&heart_beat=%5b%5d&ua=Mozilla%2f5.0+(Windows+NT+10.0%3b+Win64%3b+x64)+AppleWebKit%2f537.36+(KHTML%2c+like+Gecko)+Chrome%2f110.0.0.0+Safari%2f537.36+Edg%2f110.0.1587.41&csrf_token=04037de908f98ce32399fe8468027966&csrf=04037de908f98ce32399fe8468027966&visit_id=&device=%5b%22AUTO6216946288900999%3b+expires%3dFri%2c+31-Dec-2038+23%3a59%3a59+GMT%3b+path%3d%2f%3b+domain%3d.bilibili.com%22%2c%2253b2dc61-29a5-46c5-b159-e6131e61875b%22%5d

[EXCEPTION]
System.Net.Http.HttpRequestException: Connection refused (live-trace.bilibili.com:443)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpRequestMessage request, Context context, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 32
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)

[ELAPSED] 00:00:03.0213108
[02:24:37 ERR] 直播时长挂机失败，继续其他任务。失败信息:Connection refused (live-trace.bilibili.com:443)

[02:24:37 INF] ---------结束---------

[02:24:37 INF] ==========结束==========

[02:24:37 INF] 

========================

 v2.0.1 开源 by https://github.com/RayWangQvQ/BiliBiliToolPro

[02:24:37 INF] ·开始推送·LiveFansMedal任务·
2023-09-13T18:24:37.9012703Z 开始推送到:PushPlus
2023-09-13T18:24:37.9668845Z Response status: OK.
2023-09-13T18:24:37.9669668Z Response content: {"code":200,"msg":"请求成功","data":"e457d6e7acaf4b608cdf57eaa8a8debe","count":null}.

[02:24:37 INF] 运行环境：Development
[02:24:37 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[02:24:37 INF] 运行结束

**Comment by fancyword** [comment]
一样
