### ISSUE TITLE
【Bug】青龙面板大会员大积分任务报错

### ISSUE THREAD

**Issue by BZ88888** [RayWangQvQ/BiliBiliToolPro#607]
版本号：昨天刚拉取的最新版本
运行环境：青龙面板

问题描述：大会员大积分任务报错
日志信息：[11:25:45 INF] ---开始 购买指定大会员产品（仅领取） ---
[11:25:45 ERR] 购买指定大会员产品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[11:25:45 INF] -----------------结束-----------------

[11:25:45 INF] ---开始 购买指定会员购商品（仅领取） ---
[11:25:45 ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[11:25:45 INF] -----------------结束-----------------

[11:25:45 ERR] 程序发生异常：Object reference not set to an instance of an object.
[11:25:45 INF] ===========结束===========

[11:25:45 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs:line 82
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 188
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76
[11:25:45 INF] 运行环境：Development
[11:25:45 INF] 应用目录：/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[11:25:45 INF] 运行结束

**Comment by RayWangQvQ** [comment]
最新版已解决，更新后再试试
