### ISSUE TITLE
【bug】投币报错443，Name does not resolve

### ISSUE THREAD

**Issue by 15817167867** [RayWangQvQ/BiliBiliToolPro#64]
## 开始执行... 2022-04-02 09:00:00

[09:00:09 INF] BiliBiliToolPro 开始运行...

[09:00:10 INF] 【目标任务】Daily
[09:00:10 INF] 【账号个数】2个

[09:00:10 INF] 随机休眠12分钟

[09:12:10 INF] 账号 1 ：

[09:12:10 INF] =====开始 每日任务 =====

[09:12:10 INF] ---开始 登录 ---
[09:12:32 INF] 【用户名】 茶xx喵
[09:12:32 INF] 【硬币余额】 297.2
[09:12:32 INF] 【距升级 Lv6】 5天（如每日做满65点经验）
[09:12:32 INF] 登录成功，经验+5 √
[09:12:32 INF] -----结束-----

[09:12:44 INF] ---开始 观看、分享视频 ---
[09:13:20 INF] 【随机视频】新手0基础搭建网站快速入门（补充录制）
[09:13:20 INF] 今天已经观看过了，不需要再看啦
[09:13:44 INF] 视频分享成功，经验+5 √
[09:13:44 INF] ----------结束----------

[09:13:44 INF] ---开始 投币 ---
[09:14:01 INF] 【今日已投】2枚
[09:14:01 INF] 【目标欲投】5枚
[09:14:01 INF] 【还需再投】3枚
[09:14:14 ERR] [REQUEST]
GET /site/getCoin HTTP/1.1
Referer: https://account.bilibili.com/account/coin
Host: account.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[EXCEPTION]
System.Net.Http.HttpRequestException: Name does not resolve (account.bilibili.com:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /ql/repo/raywangqvq_bilibilitoolpro_develop/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 30
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)

[ELAPSED] 00:00:13.0612861
[09:14:14 ERR] 投币失败，继续其他任务。失败信息:Name does not resolve (account.bilibili.com:443)

[09:14:14 INF] ---开始 直播签到 ---
[09:14:26 INF] 【签到结果】成功
[09:14:26 INF] 【本次获取】3000点用户经验,2根辣条,再签到3天可以获得666银瓜子
[09:14:26 INF] -------结束-------

[09:14:26 INF] ---开始 漫画签到 ---
[09:14:43 INF] 【签到结果】成功
[09:14:43 INF] -------结束-------

[09:14:43 INF] ---开始 银瓜子兑换硬币 ---
[09:14:43 INF] 已配置为关闭，跳过
[09:14:43 INF] ----------结束----------

[09:14:43 INF] ---开始 领取大会员福利 ---
[09:14:43 INF] 普通会员和月度大会员每月不赠送B币券，不需要领取权益喽
[09:14:43 INF] ----------结束----------

[09:14:43 INF] ---开始 领取大会员漫画权益 ---
[09:14:43 INF] 不是会员，跳过
[09:14:43 INF] ------------结束------------

[09:14:43 INF] ---开始 B币券充电 ---
[09:14:43 INF] 不是年度大会员，跳过
[09:14:43 INF] --------结束--------

[09:14:43 INF] =========结束=========

[09:14:43 INF] 
---------------------------------------
 RayBiliBiliToolPro-v0.0.9 in Production env.
开源 by https://github.com/RayWangQvQ/BiliBiliToolPro
[09:14:43 INF] ·开始推送·Daily任务·账号【1】

**Comment by RayWangQvQ** [comment]
可以更新到最新版本尝试解决
