### ISSUE TITLE
首次运行<bili扫码登录> dotnet报错 System.IOException: The configured user limit (128) on the number of inotify instances has been reached

### ISSUE THREAD

**Issue by languede** [RayWangQvQ/BiliBiliToolPro#645]
#### 版本号：
                      * dotnet==6.0.125
                      * 青龙==2.16.5

#### 问题描述：
首次运行<bili扫码登录>自动安装dotnet成功，然后报错: System.IOException: The configured user limit (128) on the number of inotify instances has been reached,  or the per-process limit on the number of open file descriptors has been reached.

看起来是 dotnet 的问题？ 搜索了一下：

         * 尝试1: 
          `echo fs.inotify.max_user_instances=1024 | sudo tee -a /etc/sysctl.conf`
          `echo fs.inotify.max_user_watches=1048576 | sudo tee -a /etc/sysctl.conf`    
          `sudo sysctl -p`
           无效， 好像docker 不能运行sysctl -p, 权限问题

         * 尝试2: 
           删除订阅，重新订阅， 重启docker -> 无效

         * 尝试3:
            运行自带的bili自动修复脚本 -> 无效

#### 日志信息：

bili扫码登录的日志：
 
./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.125

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

  ____               ____    _   _____           _  
 |  _ \ __ _ _   _  | __ ) _| |_|_   _|__   ___ | | 
 | |_) / _` | | | | |  _ \(_) (_) | |/ _ \ / _ \| | 
 |  _ < (_| | |_| | | |_) | | | | | | (_) | (_) | | 
 |_| \_\__,_|\__, | |____/|_|_|_| |_|\___/ \___/|_| 
             |___/                                  

Unhandled exception. System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Ray.BiliBiliTool.Console.Program.CreateHost(String[] args) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 43
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 23
   at Ray.BiliBiliTool.Console.Program.<Main>(String[] args)

**Comment by RayWangQvQ** [comment]
感谢反馈，先汇总到 #691 ，稍后统一解决
