### ISSUE TITLE
【Bug】Ubuntu中安装了dotnet8.0,但是青龙中运行扫码登录报错如下日志描述。

### ISSUE THREAD

**Issue by wangxh86** [RayWangQvQ/BiliBiliToolPro#648]
版本号：Ubuntu18.04    
               青龙2.11.3
              dotnet --version   8.0.100
运行环境：青龙

问题描述：Ubuntu中执行以下命令：curl -sSL https://ghproxy.com/https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/qinglong/ray-dotnet-install.sh | bash /dev/stdin --no-official安装了dotnet8.0.100，但是在青龙中运行扫码登录报错如下日志描述：

日志信息：（添加PATH
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
/dev/stdin: line 116:  1237 Aborted                 (core dumped) dotnet --info

-------set up dot net env finish-------
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
bili_task_base.sh: line 35:  1244 Aborted                 (core dumped) dotnet --version
安装失败，没办法了，毁灭吧，自己解决吧：https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-alpine
）

**Comment by ZiaYao** [comment]
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/92203686/baee817e-b28d-4fdb-a708-e5c097d6c85d)
