### ISSUE TITLE
【Bug】虚拟机使用宿主clash代理启动青龙，扫码登入http502 Bad Gateway

### ISSUE THREAD

**Issue by scccy** [RayWangQvQ/BiliBiliToolPro#658]
[15:29:56 INF] ---开始 持久化Cookie ---
[15:29:56 INF] 当前运行平台：QingLong
[15:29:58 ERR] [REQUEST]
[EXCEPTION]
WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：502 Bad Gateway
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

在docker-compose 中加入了宿主机的clash代理端口

**Comment by scccy** [comment]
Host terminated unexpectedly!
System.Net.Http.HttpRequestException: 服务器响应了错误的http状态码：502 Bad Gateway
 ---> WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：502 Bad Gateway
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(ApiRequestContext request)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   --- End of inner exception stack trace ---
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   at Ray.BiliBiliTool.DomainService.LoginDomainService.SaveCookieToQinLongAsync(BiliCookie ckInfo, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/LoginDomainService.cs:line 216
   at Ray.BiliBiliTool.Application.LoginTaskAppService.SaveCookieAsync(BiliCookie ckInfo, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 80
   at Ray.BiliBiliTool.Application.LoginTaskAppService.DoTaskAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 54
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 194
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 27

**Comment by DoiiarX** [comment]
我觉得你应该提供更完整的日志，不过我觉得我解决了你这个问题。经过熬夜排查，以下是思路和解决方案。

主要是端口问题，这部分报错不在你日志内。

https://notion.doiiars.com/article/fixing-bilibilitoolpro-dockercompose-failure
