### ISSUE TITLE
【Bug】win11 X64本地部署 大积分领取，每次都报错然后自动退出（安装了net6）

### ISSUE THREAD

**Issue by w32x42y** [RayWangQvQ/BiliBiliToolPro#682]
版本号：v2.0.2
运行环境：win11 X64 本地

问题描述：大积分领取，每次都报错然后自动退出

![微信图片_20240410114008](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/129025140/d8f4babc-9f38-4fe8-b6af-065c8492f4c9)

日志信息：2024-04-10 10:36:12.562 +08:00 [INF] ---开始 签到 ---
2024-04-10 10:36:12.567 +08:00 [INF] 已完成，跳过
2024-04-10 10:36:12.568 +08:00 [INF] 今日获得签到积分：10
2024-04-10 10:36:12.569 +08:00 [INF] 累计签到73天
2024-04-10 10:36:12.571 +08:00 [INF] -----结束-----

2024-04-10 10:36:12.583 +08:00 [INF] ---开始 福利任务 ---
2024-04-10 10:36:12.585 +08:00 [INF] 已完成，跳过
2024-04-10 10:36:12.586 +08:00 [INF] -------结束-------

2024-04-10 10:36:12.598 +08:00 [INF] ---开始 体验任务 ---
2024-04-10 10:36:12.600 +08:00 [INF] 已完成，跳过
2024-04-10 10:36:12.601 +08:00 [INF] -------结束-------

2024-04-10 10:36:12.609 +08:00 [INF] ---开始 浏览追番频道页10秒 ---
2024-04-10 10:36:12.613 +08:00 [INF] 已完成，跳过
2024-04-10 10:36:12.614 +08:00 [INF] -------------结束-------------

2024-04-10 10:36:12.618 +08:00 [INF] ---开始 浏览会员购页面10秒 ---
2024-04-10 10:36:12.619 +08:00 [INF] 待实现...
2024-04-10 10:36:12.620 +08:00 [INF] -------------结束-------------

2024-04-10 10:36:12.630 +08:00 [INF] ---开始 观看任意正片内容 ---
2024-04-10 10:36:12.641 +08:00 [ERR] 观看任意正片内容失败，继续其他任务。失败信息:Sequence contains no matching element

2024-04-10 10:36:12.649 +08:00 [INF] -----------结束-----------

2024-04-10 10:36:12.658 +08:00 [INF] ---开始 购买单点付费影片（仅领取） ---
2024-04-10 10:36:12.662 +08:00 [ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-04-10 10:36:12.665 +08:00 [INF] ----------------结束----------------

2024-04-10 10:36:12.672 +08:00 [INF] ---开始 购买指定会员购商品（仅领取） ---
2024-04-10 10:36:12.673 +08:00 [ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-04-10 10:36:12.675 +08:00 [INF] -----------------结束-----------------

2024-04-10 10:36:12.676 +08:00 [ERR] 程序发生异常：Object reference not set to an instance of an object.
2024-04-10 10:36:12.679 +08:00 [INF] ===========结束===========

2024-04-10 10:36:12.750 +08:00 [WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken)
2024-04-10 10:36:12.751 +08:00 [INF] 运行环境：Production
2024-04-10 10:36:12.753 +08:00 [INF] 应用目录：C:\Users\wang9\Desktop\bilibili-tool-pro-v2.0.2-win-x64\win-x64\

2024-04-10 10:36:12.754 +08:00 [INF] 运行结束

**Comment by drw2005** [comment]
我的是提示帐号有风险：
[08:57:00 INF] ---开始 签到 ---
[08:57:04 ERR] 签到失败，继续其他任务。失败信息:{"Code":6007000,"Message":"抱歉，您的账号存在风险，暂时无法参与本任务哦~","Data":null}

有知道原因的没？难道是被风控了？

**Comment by Polaris-cn10086** [comment]
老毛病了。

如果可以试着用一下develop分支自己构建一下，看能不能用，我现在没有大会员了。

或者等我有空发个编译好的。

**Comment by w32x42y** [comment]
> 老毛病了。
> 
> 如果可以试着用一下develop分支自己构建一下，看能不能用，我现在没有大会员了。
> 
> 或者等我有空发个编译好的。

哈哈，自己构建对于我来说太复杂了，作者的交流群你加了吗，如果加了方便分享下群二维码吗

**Comment by Polaris-cn10086** [comment]
> > 老毛病了。
> > 
> > 如果可以试着用一下develop分支自己构建一下，看能不能用，我现在没有大会员了。
> > 
> > 或者等我有空发个编译好的。
> 
> 哈哈，自己构建对于我来说太复杂了，作者的交流群你加了吗，如果加了方便分享下群二维码吗

我自己试了一下，B站的api更新了，我试着修复一下

**Comment by drw2005** [comment]
> > > 老毛病了。
> > > 如果可以试着用一下develop分支自己构建一下，看能不能用，我现在没有大会员了。
> > > 或者等我有空发个编译好的。
> > 
> > 
> > 哈哈，自己构建对于我来说太复杂了，作者的交流群你加了吗，如果加了方便分享下群二维码吗
> 
> 我自己试了一下，B站的api更新了，我试着修复一下

等待你的成功消息。。。

**Comment by catlair** [comment]
> > > 老毛病了。
> > > 如果可以试着用一下develop分支自己构建一下，看能不能用，我现在没有大会员了。
> > > 或者等我有空发个编译好的。
> > 
> > 
> > 哈哈，自己构建对于我来说太复杂了，作者的交流群你加了吗，如果加了方便分享下群二维码吗
> 
> 我自己试了一下，B站的api更新了，我试着修复一下

早一点还可以参考 bilioutils，不过现在跑路了

**Comment by Polaris-cn10086** [comment]
> > > > 老毛病了。
> > > > 如果可以试着用一下develop分支自己构建一下，看能不能用，我现在没有大会员了。
> > > > 或者等我有空发个编译好的。
> > > 
> > > 
> > > 哈哈，自己构建对于我来说太复杂了，作者的交流群你加了吗，如果加了方便分享下群二维码吗
> > 
> > 
> > 我自己试了一下，B站的api更新了，我试着修复一下
> 
> 早一点还可以参考 bilioutils，不过现在跑路了

咋跑路了啊，我前两天看还好好的呢 (っ °Д °;)っ

**Comment by RayWangQvQ** [comment]
确认下最新版是否已解决？
