### ISSUE TITLE
【异常】青龙上运行，提示任务终止。

### ISSUE THREAD

**Issue by drw2005** [RayWangQvQ/BiliBiliToolPro#7]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
拉取的最新版本

运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）
青龙

问题描述：（提issue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）
日志-bili_task_test.sh
## 开始执行... 2022-01-28 09:20:32

Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
bili_task_test.sh: line 5:  1181 Aborted                 (core dumped) dotnet run --project /ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console -runTasks=Test

## 执行结束... 2022-01-28 09:20:32 耗时 0 秒

按照青龙部署教程一步步来的，拉取任务后，提示上面的错误，请大佬指点解决办法，谢谢！
dotnet 环境也安装了，过程如下：
![1](https://user-images.githubusercontent.com/33473981/151470984-7d139bb9-d67f-413a-a800-34e8af5c837e.png)

**Comment by drw2005** [comment]
今天重新拉库后MS正常了。。。

**Comment by RayWangQvQ** [comment]
参考：#266
