### ISSUE TITLE
【Bug】大会员任务异常报错

### ISSUE THREAD

**Issue by TianMiao8152** [RayWangQvQ/BiliBiliToolPro#700]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
v2.0.4

运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）
docker

问题描述：（提issue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）
大会员任务无法完成

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）
# dotnet Ray.BiliBiliTool.Console.dll           
  ____               ____    _   _____           _  
 |  _ \ __ _ _   _  | __ ) _| |_|_   _|__   ___ | | 
 | |_) / _` | | | | |  _ \(_) (_) | |/ _ \ / _ \| | 
 |  _ < (_| | |_| | | |_) | | | | | | (_) | (_) | | 
 |_| \_\__,_|\__, | |____/|_|_|_| |_|\___/ \___/|_| 
             |___/                                  

[10:49:47 INF] BiliBiliToolPro 开始运行...

[10:49:47 INF] 【账号个数】1个

[10:49:47 INF] 未指定目标任务，请选择要运行的任务：
[10:49:47 INF] 1):Daily
[10:49:47 INF] 2):LiveFansMedal
[10:49:47 INF] 3):LiveLottery
[10:49:47 INF] 4):Login
[10:49:47 INF] 5):Test
[10:49:47 INF] 6):UnfollowBatched
[10:49:47 INF] 7):VipBigPoint
[10:49:47 INF] 请输入：
7
[10:49:56 INF] 【目标任务】VipBigPoint
[10:49:56 INF] ######### 账号 1 #########

[10:49:57 INF] =====开始 大会员大积分 =====

[10:49:57 INF] ---开始 测试Cookie ---
[10:50:14 INF] 【用户名】***
[10:50:14 INF] 【会员类型】年度大会员
[10:50:14 INF] 【会员状态】正常
[10:50:14 INF] 【硬币余额】1.2
[10:50:14 INF] 【距升级Lv6】预计262天
[10:50:14 INF] -----------结束-----------

[10:50:32 INF] ------当前任务状态------
[10:50:32 INF] 打卡：X
[10:50:32 INF] -福利任务
[10:50:32 INF] ---大会员福利大积分：√
[10:50:32 INF] -体验任务
[10:50:32 INF] ---浏览大会员权益页面：√
[10:50:32 INF] -日常任务
[10:50:32 INF] ---浏览装扮商城主页：X
[10:50:32 INF] ---浏览会员购页面10秒：X
[10:50:32 INF] ---购买指定会员购商品：X
[10:50:32 INF] ---浏览追番频道页10秒：X
[10:50:32 INF] ---观看剧集内容：X
[10:50:32 INF] ---购买单点付费影片：X
[10:50:32 INF] ---购买指定装扮商品：X
[10:50:32 INF] ------------------------

[10:50:32 INF] 大会员经验领取任务开始
[10:50:43 INF] 大会员经验未兑换
[10:50:53 INF] 领取成功，经验+10 √
[10:50:53 INF] ---开始 签到 ---
[10:51:13 ERR] 签到失败，继续其他任务。失败信息:{"Code":6007000,"Message":"抱歉，您的账号存在风险，暂时无法参与本任务哦~","Data":null}

[10:51:13 INF] -----结束-----

[10:51:13 INF] ---开始 福利任务 ---
[10:51:13 ERR] 福利任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[10:51:13 INF] -------结束-------

[10:51:13 INF] ---开始 体验任务 ---
[10:51:13 ERR] 体验任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[10:51:13 INF] -------结束-------

[10:51:13 INF] ---开始 浏览追番频道页10秒 ---
[10:51:13 ERR] 浏览追番频道页10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[10:51:13 INF] -------------结束-------------

[10:51:13 INF] ---开始 浏览会员购页面10秒 ---
[10:51:13 ERR] 浏览会员购页面10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[10:51:13 INF] -------------结束-------------

[10:51:13 INF] ---开始 浏览装扮商城主页 ---
[10:51:13 ERR] 浏览装扮商城主页失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[10:51:13 INF] -----------结束-----------

[10:51:13 INF] ---开始 观看剧集内容 ---
[10:51:13 ERR] 观看剧集内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[10:51:13 INF] ---------结束---------

[10:51:13 INF] ---开始 购买单点付费影片（仅领取） ---
[10:51:13 ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[10:51:13 INF] ----------------结束----------------

[10:51:13 INF] ---开始 购买指定会员购商品（仅领取） ---
[10:51:13 ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[10:51:13 INF] -----------------结束-----------------

[10:51:13 ERR] 程序发生异常：Object reference not set to an instance of an object.
[10:51:13 INF] ===========结束===========

[10:51:13 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken) in /code/src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs:line 157
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /code/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 194
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /code/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76
[10:51:13 INF] 运行环境：Production
[10:51:13 INF] 应用目录：/app/

[10:51:13 INF] 运行结束

**Comment by RayWangQvQ** [comment]
请更新到最新版本后再次尝试

**Comment by TianMiao8152** [comment]
> 请更新到最新版本后再次尝试

今日任务已完成，待明日测试
