### ISSUE TITLE
【Bug】请在标题中清晰地概述你要反馈的异常或缺陷

### ISSUE THREAD

**Issue by qianshihua** [RayWangQvQ/BiliBiliToolPro#707]
版本号：develop
运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）

问题描述：
扫码登录任务提示：程序异常终止，原因：第 1 个cookie不存在

日志信息：
## 开始执行... 2024-05-06 02:04:38

bilitool: 青龙repo目录: /ql/data/repo
bilitool: bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop
bilitool: Calling: check_os 
bilitool: Calling: get_current_os_name 
bilitool: Calling: get_linux_platform_name 
bilitool: 当前系统发行版本：alpine.3.19.1
bilitool: Calling: is_musl_based_distro 
bilitool: 当前系统：linux-musl
bilitool: Calling: get_machine_architecture 
bilitool: 当前架构：x64
bilitool: Calling: machine_has curl
bilitool: 当前选择的运行方式：dotnet
bilitool: Calling: install 
bilitool: Calling: check 
bilitool: Calling: check_dotnet 
bilitool: 已安装dotnet，当前版本：6.0.129
bilitool: which dotnet: /usr/bin/dotnet
bilitool: 环境正常，本次无需安装
bilitool: Calling: run_task Login
  ____               ____    _   _____           _  
 |  _ \ __ _ _   _  | __ ) _| |_|_   _|__   ___ | | 
 | |_) / _` | | | | |  _ \(_) (_) | |/ _ \ / _ \| | 
 |  _ < (_| | |_| | | |_) | | | | | | (_) | (_) | | 
 |_| \_\__,_|\__, | |____/|_|_|_| |_|\___/ \___/|_| 
             |___/                                  

[02:04:44 INF] BiliBiliToolPro 开始运行...

[02:04:44 INF] 【账号个数】0个

[02:04:44 INF] 【目标任务】Login
[02:04:44 ERR] 程序异常终止，原因：第 1 个cookie不存在
[02:04:44 INF] 运行环境：Development
[02:04:44 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[02:04:44 INF] 运行结束
[02:04:45 FTL] Host terminated unexpectedly!
System.Exception: 第 1 个cookie不存在
   at Ray.BiliBiliTool.Infrastructure.Cookie.CookieStrFactory.GetCurrentCookieDic() in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Infrastructure/Cookie/CookieStrFactory.cs:line 35
   at Ray.BiliBiliTool.Infrastructure.Cookie.CookieInfo.get_CookieItemDictionary() in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Infrastructure/Cookie/CookieInfo.cs:line 18
   at Ray.BiliBiliTool.Infrastructure.Cookie.CookieInfo.ToString() in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Infrastructure/Cookie/CookieInfo.cs:line 31
   at Ray.BiliBiliTool.Agent.Extensions.ServiceCollectionExtension.<>c.<AddBiliBiliClientApi>b__0_2(IServiceProvider sp, HttpClient c) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Agent/Extensions/ServiceCollectionExtension.cs:line 66
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass1_1.<ConfigureHttpClient>b__2(HttpClient client)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at Microsoft.Extensions.DependencyInjection.HttpApiExtensions.HttpApiProvider`1.CreateHttpApi(IServiceProvider serviceProvider, String name)
   at Microsoft.Extensions.DependencyInjection.HttpApiExtensions.<>c__DisplayClass0_0`1.<AddHttpApi>b__0(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 193
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Program.cs:line 27

## 执行结束... 2024-05-06 02:04:45  耗时 7 秒

**Comment by aosenqaq** [comment]
今天使用青龙面板2.17.4重新部署的先行版，扫码登陆报同样的错误了

**Comment by RayWangQvQ** [comment]
收到，我来修一下

**Comment by RayWangQvQ** [comment]
拉取最新代码重试下

**Comment by qianshihua** [comment]
感谢，已经修复

**Comment by aosenqaq** [comment]
已重新部署，成功扫码登陆，感谢
