### ISSUE TITLE
Couldn't find a project to run ，请问这个问题该如何解决？

### ISSUE THREAD

**Issue by Flyingpen** [RayWangQvQ/BiliBiliToolPro#724]
bilitool: 青龙repo目录: /ql/data/repo
bilitool: bili仓库目录: 
bilitool: 当前系统发行版本：alpine.3.15.0
bilitool: 当前系统：linux-musl
bilitool: 当前架构：x64
bilitool: 当前选择的运行方式：dotnet
bilitool: 已安装dotnet，当前版本：6.0.421
bilitool: which dotnet: /root/.dotnet/dotnet
bilitool: 环境正常，本次无需安装
Couldn't find a project to run. Ensure a project exists in /src/Ray.BiliBiliTool.Console, or pass the path to the project using --project.

**Comment by Flyingpen** [comment]
以上是使用dotnet时候的错误信息。
如果是使用tools，同样也有报错，人麻了。且切换dev版本和正式版本，都有同样报错。
以下是tools的报错信息——
`Unhandled exception. System.InvalidOperationException: The configuration value in Serilog:WriteTo:5:Name has no 'Name' element.
   at Serilog.Settings.Configuration.ConfigurationReader.<GetMethodCalls>g__GetSectionName|18_8(IConfigurationSection s)
   at Serilog.Settings.Configuration.ConfigurationReader.<>c.<GetMethodCalls>b__18_3(IConfigurationSection child)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource )
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource )
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 , Func`2 , Func`2 , IEqualityComparer`1 )
   at System.Linq.Enumerable.ToLookup[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToLookup[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Serilog.Settings.Configuration.ConfigurationReader.GetMethodCalls(IConfigurationSection directive)
   at Serilog.Settings.Configuration.ConfigurationReader.ApplySinks(LoggerConfiguration loggerConfiguration)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, String sectionName, DependencyContext dependencyContext)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, DependencyContext dependencyContext)
   at Ray.BiliBiliTool.Console.Program.<>c.<CreateHostBuilder>b__2_2(HostBuilderContext hostBuilderContext, ILoggingBuilder loggingBuilder)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass4_1.<ConfigureLogging>b__1(ILoggingBuilder )
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection , Action`1 )
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass4_0.<ConfigureLogging>b__0(HostBuilderContext , IServiceCollection )
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Ray.BiliBiliTool.Console.Program.CreateHost(String[] args)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args)
   at Ray.BiliBiliTool.Console.Program.<Main>(String[] args)
bili_task_base.sh: line 451:  2513 Aborted                 (core dumped) ./Ray.BiliBiliTool.Console --ENVIRONMENT=Production`
