### ISSUE TITLE
【Bug】<--开始 持久化Cookie ---着一步的时候报错>

### ISSUE THREAD

**Issue by 2425500165** [RayWangQvQ/BiliBiliToolPro#733]
### 版本

BiliTool版本号：`2.1.1`   // 在git仓库下方选择了docker教程  

### 确认

- [ ] 是的，我已搜索并确认，没有其他相同的议题
- [ ] 是的，我确认，已尝试升级到最新版，但未解决

### 服务器架构

- [x] x64
- [x] arm64
- [ ] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [*] Linux

### 选择的BiliTool运行模式

- [* ] docker

### 问题描述

[<这里>])
在cookies。json 里的 BiliBiliCookies数据里粘贴了我的cookie 然后运行docker exec -it bili bash -c "dotnet Ray.BiliBiliTool.Console.dll --runTasks=Login"  扫完码之后 进行到 开始 持久化Cookie -报错

### 日志信息

[15:16:14 INF] 我数到10，动作快点
[15:16:14 INF] [1]等待扫描...
[15:16:37 INF] 未扫码

[15:16:37 INF] [2]等待扫描...
[15:16:53 INF] 扫描成功！
[15:16:53 INF] --------结束--------

[15:16:53 INF] ---开始 Set Cookie ---
[15:17:10 INF] 访问主站成功
[15:17:10 INF] SetCookie成功
[15:17:10 INF] -------------结束-------------

[15:17:10 INF] ---开始 持久化Cookie ---
[15:17:10 INF] 当前运行平台：Unknown
[15:17:10 INF] 目标json地址：/app/cookies.json
[15:17:10 ERR] 程序发生异常：Count must be positive and count must refer to a location within the string/array/collection. (Parameter 'count')
[15:17:10 INF] ------------结束------------

[15:17:10 ERR] 程序发生异常：Count must be positive and count must refer to a location within the string/array/collection. (Parameter 'count')
[15:17:10 INF] =========结束=========

[15:17:10 ERR] 程序异常终止，原因：Count must be positive and count must refer to a location within the string/array/collection. (Parameter 'count')
[15:17:10 INF] 运行环境：Production
[15:17:10 INF] 应用目录：/app/

[15:17:10 INF] 运行结束
[15:17:10 FTL] Host terminated unexpectedly!
System.ArgumentOutOfRangeException: Count must be positive and count must refer to a location within the string/array/collection. (Parameter 'count')
   at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match)
   at Ray.BiliBiliTool.DomainService.LoginDomainService.SaveCookieToJsonFileAsync(BiliCookie ckInfo, CancellationToken cancellationToken) in /code/src/Ray.BiliBiliTool.DomainService/LoginDomainService.cs:line 187
   at Ray.BiliBiliTool.Application.LoginTaskAppService.SaveCookieAsync(BiliCookie ckInfo, CancellationToken cancellationToken) in /code/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 85
   at Ray.BiliBiliTool.Application.LoginTaskAppService.DoTaskAsync(CancellationToken cancellationToken) in /code/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 54
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /code/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 194
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /code/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /code/src/Ray.BiliBiliTool.Console/Program.cs:line 34

<details>

```
<这里>
```

</details>

**Comment by RayWangQvQ** [comment]
感谢反馈，稍后验证

**Comment by swc19901231** [comment]
我的青龙面板版本为v2.18.1

## 开始执行... 2025-01-28 00:14:07

bilitool: 青龙repo目录: /ql/data/repo
bilitool: bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro
bilitool: 当前系统发行版本：alpine.3.18.4
bilitool: 当前系统：linux-musl
bilitool: 当前架构：x64
bilitool: 当前选择的运行方式：dotnet
bilitool: 已安装dotnet，当前版本：6.0.124
bilitool: which dotnet: /usr/bin/dotnet
bilitool: 环境正常，本次无需安装


[00:15:07 INF] 我数到10，动作快点
[00:15:07 INF] [1]等待扫描...
[00:15:29 INF] 扫描成功！
[00:15:29 INF] --------结束--------

[00:15:29 INF] ---开始 Set Cookie ---
[00:15:46 INF] 访问主站成功
[00:15:46 INF] SetCookie成功
[00:15:46 INF] -------------结束-------------

[00:15:46 INF] ---开始 持久化Cookie ---
[00:15:46 INF] 当前运行平台：QingLong
[00:15:46 ERR] [REQUEST]
GET /api/envs?searchValue=Ray_BiliBiliCookies__ HTTP/1.1
Host: localhost:5600
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiUnFya1NzeXRIVkVzNXYwZkVaLVRFanZVQXJQN1VRcDZsX3QtLTRTSGFSZFdqaDAtX1FUNjVfUVNYbW5FUGt5ZGdZNzVIZTZYX00yNnZIcUpWdEpLdU03dGVrYm0xZVEta3VtaiIsImlhdCI6MTczNzQyNTIyOSwiZXhwIjoxNzM5MTUzMjI5fQ.tr5U-cCc5baE0jmYkZg85O2wZ-fN6Q4JDVH85t87wTLChB942eD4kBCBQvUzTFNR
Accept: application/json; q=0.001, application/xml; q=0.001

[RESPONSE]
HTTP/1.1 401 Unauthorized
X-Powered-By: Express
Access-Control-Allow-Origin: *
ETag: W/"26-uxsmWW1oStvaIaR72OnRYiGujCk"
Date: Mon, 27 Jan 2025 16:15:46 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Type: application/json; charset=utf-8
Content-Length: 38

{"code":401,"message":"jwt malformed"}

[EXCEPTION]
WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：401 Unauthorized
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

[ELAPSED] 00:00:00.0491516
[00:15:46 ERR] 程序发生异常：服务器响应了错误的http状态码：401 Unauthorized
[00:15:46 INF] ------------结束------------

[00:15:46 ERR] 程序发生异常：服务器响应了错误的http状态码：401 Unauthorized
[00:15:46 INF] =========结束=========

[00:15:46 ERR] 程序异常终止，原因：服务器响应了错误的http状态码：401 Unauthorized
[00:15:46 INF] 运行环境：Production
[00:15:46 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[00:15:46 INF] 运行结束
[00:15:46 FTL] Host terminated unexpectedly!
System.Net.Http.HttpRequestException: 服务器响应了错误的http状态码：401 Unauthorized
 ---> WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：401 Unauthorized
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(ApiRequestContext request)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   --- End of inner exception stack trace ---
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   at Ray.BiliBiliTool.DomainService.LoginDomainService.SaveCookieToQinLongAsync(BiliCookie ckInfo, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/LoginDomainService.cs:line 216
   at Ray.BiliBiliTool.Application.LoginTaskAppService.SaveCookieAsync(BiliCookie ckInfo, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 80
   at Ray.BiliBiliTool.Application.LoginTaskAppService.DoTaskAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 54
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 194
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 34
/ql/shell/otask.sh: line 252: pop_var_context: head of shell_variables not a function context
/ql/shell/otask.sh: line 286: pop_var_context: head of shell_variables not a function context

**Comment by bluerk145** [comment]
**我的面板为2.18.0**
:09 INF] 我数到10，动作快点
[23:46:09 INF] [1]等待扫描...
[23:46:28 INF] 未扫码

[23:46:28 INF] [2]等待扫描...
[23:46:52 INF] 扫描成功！
[23:46:52 INF] --------结束--------

[23:46:52 INF] ---开始 Set Cookie ---
[23:47:12 INF] 访问主站成功
[23:47:12 INF] SetCookie成功
[23:47:12 INF] -------------结束-------------

[23:47:12 INF] ---开始 持久化Cookie ---
[23:47:12 INF] 当前运行平台：QingLong
[23:47:12 ERR] [REQUEST]
GET /api/envs?searchValue=Ray_BiliBiliCookies__ HTTP/1.1
Host: localhost:5600
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiSEZSYzl1VnJDNXplYUIxLUVGRDJmbmhVOGY5LU9QRWNYZ3pMNE1PRllYaXNaWUlObm1SWlFSVHdKTkFkVjYyIiwiaWF0IjoxNzM2NjgxMjg3LCJleHAiOjE3Mzg0MDkyODd9.OonfKTenIZ3fzPkWEpyVfUpzB12injoxXqo1KYJELcebru-Vcw_Gsq-hA289UGJc
Accept: application/json; q=0.001, application/xml; q=0.001

[RESPONSE]
HTTP/1.1 401 Unauthorized
X-Powered-By: Express
Access-Control-Allow-Origin: *
ETag: W/"24-u8Hf+k6Wy8ADUpUKF39W93JzxzA"
Date: Mon, 03 Feb 2025 15:47:12 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Type: application/json; charset=utf-8
Content-Length: 36

{"code":401,"message":"jwt expired"}

[EXCEPTION]
WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：401 Unauthorized
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)

[ELAPSED] 00:00:00.0076867
[23:47:12 ERR] 程序发生异常：服务器响应了错误的http状态码：401 Unauthorized
[23:47:12 INF] ------------结束------------

[23:47:12 ERR] 程序发生异常：服务器响应了错误的http状态码：401 Unauthorized
[23:47:12 INF] =========结束=========

[23:47:12 ERR] 程序异常终止，原因：服务器响应了错误的http状态码：401 Unauthorized
[23:47:12 INF] 运行环境：Production
[23:47:12 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[23:47:12 INF] 运行结束
[23:47:12 FTL] Host terminated unexpectedly!
System.Net.Http.HttpRequestException: 服务器响应了错误的http状态码：401 Unauthorized
 ---> WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：401 Unauthorized
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
   at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(ApiRequestContext request)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   --- End of inner exception stack trace ---
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   at Ray.BiliBiliTool.DomainService.LoginDomainService.SaveCookieToQinLongAsync(BiliCookie ckInfo, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/LoginDomainService.cs:line 216
   at Ray.BiliBiliTool.Application.LoginTaskAppService.SaveCookieAsync(BiliCookie ckInfo, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 80
   at Ray.BiliBiliTool.Application.LoginTaskAppService.DoTaskAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/LoginTaskAppService.cs:line 54
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 194
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 34
/ql/shell/otask.sh: line 252: pop_var_context: head of shell_variables not a function context
/ql/shell/otask.sh: line 286: pop_var_context: head of shell_variables not a function context

**Comment by main1994** [comment]
## 开始执行... 2025-02-10 01:25:40
bilitool: 青龙repo目录: /ql/data/repo
bilitool: bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro
bilitool: 当前系统发行版本：alpine.3.21.2
bilitool: 当前系统：linux-musl
bilitool: 当前架构：x64
bilitool: 当前选择的运行方式：dotnet
bilitool: 已安装dotnet，当前版本：8.0.405
bilitool: 环境正常，本次无需安装
bilitool: which dotnet: /usr/local/bin/dotnet
  ____               ____    _   _____           _  
 |  _ \ __ _ _   _  | __ ) _| |_|_   _|__   ___ | | 
 | |_) / _` | | | | |  _ \(_) (_) | |/ _ \ / _ \| | 
 |  _ < (_| | |_| | | |_) | | | | | | (_) | (_) | | 
 |_| \_\__,_|\__, | |____/|_|_|_| |_|\___/ \___/|_| 
             |___/                                  

[01:26:00 INF] BiliBiliToolPro 开始运行...

[01:26:00 INF] 【账号个数】0个

[01:26:00 INF] 【目标任务】Login
[01:26:01 ERR] 程序异常终止，原因：The format of value '' is invalid.
[01:26:01 INF] 运行环境：Production
[01:26:01 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net8.0/

[01:26:01 INF] 运行结束
[01:26:01 FTL] Host terminated unexpectedly!
System.FormatException: The format of value '' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at Ray.BiliBiliTool.Agent.Extensions.ServiceCollectionExtension.<>c.<AddBiliBiliClientApi>b__0_2(IServiceProvider sp, HttpClient c) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/Extensions/ServiceCollectionExtension.cs:line 66
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass1_1.<ConfigureHttpClient>b__2(HttpClient client)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at Microsoft.Extensions.DependencyInjection.HttpApiExtensions.HttpApiProvider`1.CreateHttpApi(IServiceProvider serviceProvider, String name)
   at Microsoft.Extensions.DependencyInjection.HttpApiExtensions.<>c__DisplayClass0_0`1.<AddHttpApi>b__0(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 193
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Program.cs:line 34
/ql/shell/otask.sh: line 252: pop_var_context: head of shell_variables not a function context
/ql/shell/otask.sh: line 286: pop_var_context: head of shell_variables not a function context

**Comment by RayWangQvQ** [comment]
试试最新版 2.2.0
