### ISSUE TITLE
大会员又出现异常了。。。

### ISSUE THREAD

**Issue by drw2005** [RayWangQvQ/BiliBiliToolPro#784]
BiliTool版本号：`6.0.133`

两个帐号，另一个正常，这个最近几天开始提示错误：

[08:14:42 INF] ---开始 福利任务 ---
[08:14:42 INF] 已完成，跳过
[08:14:42 INF] -------结束-------

[08:14:42 INF] ---开始 体验任务 ---
[08:14:42 INF] 已完成，跳过
[08:14:42 INF] -------结束-------

[08:14:42 INF] ---开始 浏览追番频道页10秒 ---
[08:14:42 ERR] 浏览追番频道页10秒失败，继续其他任务。失败信息:Sequence contains no matching element

[08:14:42 INF] -------------结束-------------

[08:14:42 INF] ---开始 浏览会员购页面10秒 ---
[08:14:42 ERR] 浏览会员购页面10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[08:14:42 INF] -------------结束-------------

[08:14:42 INF] ---开始 浏览装扮商城主页 ---
[08:14:42 ERR] 浏览装扮商城主页失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[08:14:42 INF] -----------结束-----------

[08:14:42 INF] ---开始 观看剧集内容 ---
[08:14:42 ERR] 观看剧集内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[08:14:42 INF] ---------结束---------

[08:14:42 INF] ---开始 购买单点付费影片（仅领取） ---
[08:14:42 ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[08:14:42 INF] ----------------结束----------------

[08:14:42 INF] ---开始 购买指定会员购商品（仅领取） ---
[08:14:42 ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[08:14:42 INF] -----------------结束-----------------

[08:14:42 ERR] 程序发生异常：Object reference not set to an instance of an object.
[08:14:42 INF] ===========结束===========

[08:14:42 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs:line 157
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 194
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76

**Comment by FreezingArts** [comment]
同样

**Comment by Shnivv** [comment]
一样

**Comment by Shnivv** [comment]
> 直接注释掉【浏览追番频道页10秒】这项任务就行，因为App任务列表里面没有这项任务！ [屏幕截图 2024-09-24 022905](https://github.com/user-attachments/assets/542e6ab3-8e1e-4ece-af52-570dfd77d042)

正解！感谢

**Comment by drw2005** [comment]
> 直接注释掉【浏览追番频道页10秒】这项任务就行，因为App任务列表里面没有这项任务！ [屏幕截图 2024-09-24 022905](https://github.com/user-attachments/assets/542e6ab3-8e1e-4ece-af52-570dfd77d042)

我是在青龙上运行，请教这个需要修改的文件路径在哪里？
还有，我另一个帐号倒是一直运行正常。

**Comment by Shnivv** [comment]
> > 直接注释掉【浏览追番频道页10秒】这项任务就行，因为App任务列表里面没有这项任务！ [屏幕截图 2024-09-24 022905](https://github.com/user-attachments/assets/542e6ab3-8e1e-4ece-af52-570dfd77d042)
> 
> 我是在青龙上运行，请教这个需要修改的文件路径在哪里？ 还有，我另一个帐号倒是一直运行正常。

src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs

**Comment by drw2005** [comment]
> > > 直接注释掉【浏览追番频道页10秒】这项任务就行，因为App任务列表里面没有这项任务！ [屏幕截图 2024-09-24 022905](https://github.com/user-attachments/assets/542e6ab3-8e1e-4ece-af52-570dfd77d042)
> > 
> > 
> > 我是在青龙上运行，请教这个需要修改的文件路径在哪里？ 还有，我另一个帐号倒是一直运行正常。
> 
> src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs

感谢

**Comment by drw2005** [comment]
> 直接注释掉【浏览追番频道页10秒】这项任务就行，因为App任务列表里面没有这项任务！ [屏幕截图 2024-09-24 022905](https://github.com/user-attachments/assets/542e6ab3-8e1e-4ece-af52-570dfd77d042)

注释掉就正常运行了，但是一拉库又覆盖了，还得去注释。

有没有一劳永逸的办法没？

**Comment by Shnivv** [comment]
> > 直接注释掉【浏览追番频道页10秒】这项任务就行，因为App任务列表里面没有这项任务！ [屏幕截图 2024-09-24 022905](https://github.com/user-attachments/assets/542e6ab3-8e1e-4ece-af52-570dfd77d042)
> 
> 注释掉就正常运行了，但是一拉库又覆盖了，还得去注释。
> 
> 有没有一劳永逸的办法没？

拉库的时候把这个文件黑名单，或者不拉库了，或者私库都行，反正最近没更新

**Comment by drw2005** [comment]
> > > 直接注释掉【浏览追番频道页10秒】这项任务就行，因为App任务列表里面没有这项任务！ [屏幕截图 2024-09-24 022905](https://github.com/user-attachments/assets/542e6ab3-8e1e-4ece-af52-570dfd77d042)
> > 
> > 
> > 注释掉就正常运行了，但是一拉库又覆盖了，还得去注释。
> > 有没有一劳永逸的办法没？
> 
> 拉库的时候把这个文件黑名单，或者不拉库了，或者私库都行，反正最近没更新

暂时禁止拉库了。
另外，为啥我另一个帐号不注释这一行也能正常运行完毕呢？可知道原因？

**Comment by RenegadeTuke** [comment]
> > 直接注释掉【浏览追番频道页10秒】这项任务就行，因为App任务列表里面没有这项任务！ [屏幕截图 2024-09-24 022905](https://github.com/user-attachments/assets/542e6ab3-8e1e-4ece-af52-570dfd77d042)
> 
> 注释掉就正常运行了，但是一拉库又覆盖了，还得去注释。
> 
> 有没有一劳永逸的办法没？

目前的解决办法：把本地代码上传到自己的代码库，编辑、提交，后面就直接从自己的代码库拉取就行了啊

**Comment by RenegadeTuke** [comment]
> > > > 直接注释掉【浏览追番频道页10秒】这项任务就行，因为App任务列表里面没有这项任务！ [屏幕截图 2024-09-24 022905](https://github.com/user-attachments/assets/542e6ab3-8e1e-4ece-af52-570dfd77d042)
> > > 
> > > 
> > > 注释掉就正常运行了，但是一拉库又覆盖了，还得去注释。
> > > 有没有一劳永逸的办法没？
> > 
> > 
> > 拉库的时候把这个文件黑名单，或者不拉库了，或者私库都行，反正最近没更新
> 
> 暂时禁止拉库了。 另外，为啥我另一个帐号不注释这一行也能正常运行完毕呢？可知道原因？

可能是.net6环境的问题，运行一下bili_task_base.sh和bili_task_tryFix.sh两个任务，修复一下

**Comment by drw2005** [comment]
> > > > > 直接注释掉【浏览追番频道页10秒】这项任务就行，因为App任务列表里面没有这项任务！ [屏幕截图 2024-09-24 022905](https://github.com/user-attachments/assets/542e6ab3-8e1e-4ece-af52-570dfd77d042)
> > > > 
> > > > 
> > > > 注释掉就正常运行了，但是一拉库又覆盖了，还得去注释。
> > > > 有没有一劳永逸的办法没？
> > > 
> > > 
> > > 拉库的时候把这个文件黑名单，或者不拉库了，或者私库都行，反正最近没更新
> > 
> > 
> > 暂时禁止拉库了。 另外，为啥我另一个帐号不注释这一行也能正常运行完毕呢？可知道原因？
> 
> 可能是.net6环境的问题，运行一下bili_task_base.sh和bili_task_tryFix.sh两个任务，修复一下

这两个任务运行过，提示环境正常。
