### ISSUE TITLE
【Bug】【青龙】无法使用大会员签到功能

### ISSUE THREAD

**Issue by FreezingArts** [RayWangQvQ/BiliBiliToolPro#787]
### 版本

BiliTool版本号：` v2.1.2`

青龙版本号：`2.17.3`

### 确认

- [√] 是的，我已搜索并确认，没有其他相同的议题
- [√] 是的，我确认，已尝试升级bilitool到最新版，但未解决

### 服务器架构

- [√] x64

### 服务器系统

-  Ubuntu

### 青龙容器类型

-Docker

### 青龙镜像
- whyour/qinglong:debian（Debian）

### 选择的BiliTool运行模式

- [ ] dotnet
- [ ] bilitool

### 如果是青龙拉库相关bug，请贴出拉库方式截图

- [ ] 否

### 如果是缺失文件相关bug，请贴出容器内文件路径信息

- [ ] 否
- [ ] 是，信息如下

查看方式参考文档：[提示文件不存在或路径异常怎么排查](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md#43-提示文件不存在或路径异常怎么排查)

BiliTool仓库文件路径：`/ql/data/repo/RayWangQvQ_BiliBiliToolPro`

### 问题描述

无法进行签到及其后续任务

### 日志信息

<details>

```
[15:33:20 INF] ------当前任务状态------
[15:33:20 INF] 打卡：X
[15:33:20 INF] -福利任务
[15:33:20 INF] ---大会员福利大积分：√
[15:33:20 INF] -体验任务
[15:33:20 INF] ---浏览大会员权益页面：√
[15:33:20 INF] -日常任务
[15:33:20 INF] ---浏览装扮商城主页：X
[15:33:20 INF] ---浏览会员购页面10秒：X
[15:33:20 INF] ---购买指定会员购商品：X
[15:33:20 INF] ---观看剧集内容：X
[15:33:20 INF] ---购买单点付费影片：X
[15:33:20 INF] ---购买指定装扮商品：X
[15:33:20 INF] ------------------------

[15:33:20 INF] 大会员经验领取任务开始
[15:33:37 INF] 大会员经验已兑换
[15:33:37 INF] ---开始 签到 ---
[15:33:54 ERR] 签到失败，继续其他任务。失败信息:{"Code":6007000,"Message":"请求错误","Data":null}

[15:33:54 INF] -----结束-----

[15:33:54 INF] ---开始 福利任务 ---
[15:33:54 ERR] 福利任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[15:33:54 INF] -------结束-------

[15:33:54 INF] ---开始 体验任务 ---
[15:33:54 ERR] 体验任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[15:33:54 INF] -------结束-------

[15:33:54 INF] ---开始 浏览会员购页面10秒 ---
[15:33:54 ERR] 浏览会员购页面10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[15:33:54 INF] -------------结束-------------

[15:33:54 INF] ---开始 浏览装扮商城主页 ---
[15:33:54 ERR] 浏览装扮商城主页失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[15:33:54 INF] -----------结束-----------

[15:33:54 INF] ---开始 观看剧集内容 ---
[15:33:54 ERR] 观看剧集内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[15:33:54 INF] ---------结束---------

[15:33:54 INF] ---开始 购买单点付费影片（仅领取） ---
[15:33:54 ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[15:33:54 INF] ----------------结束----------------

[15:33:54 INF] ---开始 购买指定会员购商品（仅领取） ---
[15:33:54 ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[15:33:54 INF] -----------------结束-----------------

[15:33:54 ERR] 程序发生异常：Object reference not set to an instance of an object.
[15:33:54 INF] ===========结束===========

[15:33:54 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs:line 157
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 194
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76
[15:33:54 INF] 运行环境：Production
[15:33:54 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[15:33:54 INF] 运行结束
```

</details>

**Comment by CyLzzh** [comment]
可能是bug，但是可确认的是账号被风控了，我的大号连续运行120天之后只加签到那10分，然后我用小号再开了会员，任务都完成正常

**Comment by hcv2** [comment]
我这边也是一样的情况

**Comment by litscorpi-star** [comment]
一样，不知道怎么解除风控

**Comment by xiaozhouzhoua** [comment]
一样的报错，不知道怎么解决。

**Comment by swc19901231** [comment]
用了几天之后也出现这个问题了

## 开始执行... 2025-01-28 01:07:00

bilitool: 青龙repo目录: /ql/data/repo
bilitool: bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro
bilitool: 当前系统发行版本：alpine.3.18.4
bilitool: 当前系统：linux-musl
bilitool: 当前架构：x64
bilitool: 当前选择的运行方式：dotnet
bilitool: 已安装dotnet，当前版本：6.0.124
bilitool: which dotnet: /usr/bin/dotnet
bilitool: 环境正常，本次无需安装
  ____               ____    _   _____           _  
 |  _ \ __ _ _   _  | __ ) _| |_|_   _|__   ___ | | 
 | |_) / _` | | | | |  _ \(_) (_) | |/ _ \ / _ \| | 
 |  _ < (_| | |_| | | |_) | | | | | | (_) | (_) | | 
 |_| \_\__,_|\__, | |____/|_|_|_| |_|\___/ \___/|_| 
             |___/                                  

[01:07:51 INF] BiliBiliToolPro 开始运行...

[01:07:51 INF] 【账号个数】1个

[01:07:51 INF] 随机休眠2分钟

[01:09:51 INF] 【目标任务】VipBigPoint
[01:09:51 INF] ######### 账号 1 #########

[01:09:52 INF] =====开始 大会员大积分 =====

[01:09:52 INF] ---开始 测试Cookie ---
[01:10:07 INF] 【用户名】艾x艾
[01:10:07 INF] 【会员类型】年度大会员
[01:10:07 INF] 【会员状态】正常
[01:10:07 INF] 【硬币余额】1618.1
[01:10:07 INF] 【当前经验】33979
[01:10:07 INF] 您已是 Lv6 的大佬了，无敌是多么寂寞~
[01:10:07 INF] -----------结束-----------

[01:10:20 INF] ------当前任务状态------
[01:10:20 INF] 打卡：X
[01:10:20 INF] -福利任务
[01:10:20 INF] ---大会员福利大积分：√
[01:10:20 INF] -体验任务
[01:10:20 INF] ---浏览大会员权益页面：√
[01:10:20 INF] -日常任务
[01:10:20 INF] ---浏览装扮商城主页：X
[01:10:20 INF] ---浏览会员购页面10秒：X
[01:10:20 INF] ---购买指定会员购商品：X
[01:10:20 INF] ---浏览追番频道页10秒：X
[01:10:20 INF] ---浏览影视频道页10秒：X
[01:10:20 INF] ---观看剧集内容：X
[01:10:20 INF] ---购买单点付费影片：X
[01:10:20 INF] ---购买指定装扮商品：X
[01:10:20 INF] ------------------------

[01:10:20 INF] 大会员经验领取任务开始
[01:10:39 INF] 大会员经验未兑换
[01:10:55 INF] 大会员经验领取失败，错误信息：用户经验已经领取
[01:10:55 INF] ---开始 签到 ---
[01:11:08 ERR] 签到失败，继续其他任务。失败信息:{"Code":6007000,"Message":"请求错误","Data":null}

[01:11:08 INF] -----结束-----

[01:11:08 INF] ---开始 福利任务 ---
[01:11:08 ERR] 福利任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:11:08 INF] -------结束-------

[01:11:08 INF] ---开始 体验任务 ---
[01:11:08 ERR] 体验任务失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:11:08 INF] -------结束-------

[01:11:08 INF] ---开始 浏览追番频道页10秒 ---
[01:11:08 ERR] 浏览追番频道页10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:11:08 INF] -------------结束-------------

[01:11:08 INF] ---开始 浏览会员购页面10秒 ---
[01:11:08 ERR] 浏览会员购页面10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:11:08 INF] -------------结束-------------

[01:11:08 INF] ---开始 浏览装扮商城主页 ---
[01:11:08 ERR] 浏览装扮商城主页失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:11:08 INF] -----------结束-----------

[01:11:08 INF] ---开始 观看剧集内容 ---
[01:11:08 ERR] 观看剧集内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:11:08 INF] ---------结束---------

[01:11:08 INF] ---开始 购买单点付费影片（仅领取） ---
[01:11:08 ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:11:08 INF] ----------------结束----------------

[01:11:08 INF] ---开始 购买指定会员购商品（仅领取） ---
[01:11:08 ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[01:11:08 INF] -----------------结束-----------------

[01:11:08 ERR] 程序发生异常：Object reference not set to an instance of an object.
[01:11:08 INF] ===========结束===========

[01:11:08 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs:line 102
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 194
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76
[01:11:08 INF] 运行环境：Production
[01:11:08 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[01:11:08 INF] 运行结束

## 执行结束... 2025-01-28 01:11:08  耗时 248 秒

**Comment by RayWangQvQ** [comment]
已于 #876 解决
