### ISSUE TITLE
【其他】我在运行docker exec -it qinglong bash /ql/config/extra.sh的时候有如下报错

### ISSUE THREAD

**Issue by 1816109527** [RayWangQvQ/BiliBiliToolPro#79]
（提issue前请先确认没有其他人提过相同的议题）
-------set up dot net env-------
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
--2022-04-06 23:14:48--  https://download.visualstudio.microsoft.com/download/pr/70fb6022-ef53-473b-bfde-dc8cd6b673ca/2c04303064ed5c5158998c3a0d11fcc1/dotnet-sdk-6.0.201-linux-musl-x64.tar.gz
Resolving download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)... 58.220.65.34
Connecting to download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)|58.220.65.34|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 176079572 (168M) [application/octet-stream]
Saving to: 'dotnet-sdk.tar.gz'

dotnet-sdk.tar.gz    100%[=====================>] 167.92M  12.7MB/s    in 15s     

2022-04-06 23:15:03 (11.3 MB/s) - 'dotnet-sdk.tar.gz' saved [176079572/176079572]

ln: failed to create symbolic link '/usr/local/bin/dotnet': File exists
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
Aborted (core dumped)

-------set up dot net env finish-------

**Comment by fei0327** [comment]
我也遇到了这种情况，老哥有没有解决？

**Comment by 1816109527** [comment]
把Linux下的依赖删除，重新按步骤来就可以

**Comment by 1816109527** [comment]
也不是全部，你翻到上面，有个err报错提示，把下面提示的依赖删除就可以

**Comment by mima454188** [comment]
老哥解决了吗?

**Comment by zwb124** [comment]
一样的错误，怎么弄都不行

**Comment by RayWangQvQ** [comment]
已有解决办法，请参考 #266
