### ISSUE TITLE
任务异常结束

### ISSUE THREAD

**Issue by Mtxgeek** [RayWangQvQ/BiliBiliToolPro#793]
### 确认

- [ ] 是的，我确认要选Other，因为我的内容既不是Bug，也不是Feature
- [ ] 是的，我已搜索并确认，没有其他相同的议题

### 描述

<这里>
[ELAPSED] 00:00:17.2183941
2024-10-30 16:00:28.742 +08:00 [INF] 确认：true
2024-10-30 16:00:28.743 +08:00 [INF] -------结束-------

2024-10-30 16:00:28.748 +08:00 [INF] ---开始 浏览追番频道页10秒 ---
2024-10-30 16:00:28.755 +08:00 [ERR] 浏览追番频道页10秒失败，继续其他任务。失败信息:Sequence contains no matching element

2024-10-30 16:00:28.759 +08:00 [INF] -------------结束-------------

2024-10-30 16:00:28.764 +08:00 [INF] ---开始 浏览会员购页面10秒 ---
2024-10-30 16:00:28.765 +08:00 [ERR] 浏览会员购页面10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-10-30 16:00:28.765 +08:00 [INF] -------------结束-------------

2024-10-30 16:00:28.770 +08:00 [INF] ---开始 浏览装扮商城主页 ---
2024-10-30 16:00:28.771 +08:00 [ERR] 浏览装扮商城主页失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-10-30 16:00:28.771 +08:00 [INF] -----------结束-----------

2024-10-30 16:00:28.776 +08:00 [INF] ---开始 观看剧集内容 ---
2024-10-30 16:00:28.777 +08:00 [ERR] 观看剧集内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-10-30 16:00:28.778 +08:00 [INF] ---------结束---------

2024-10-30 16:00:28.781 +08:00 [INF] ---开始 购买单点付费影片（仅领取） ---
2024-10-30 16:00:28.782 +08:00 [ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-10-30 16:00:28.783 +08:00 [INF] ----------------结束----------------

2024-10-30 16:00:28.785 +08:00 [INF] ---开始 购买指定会员购商品（仅领取） ---
2024-10-30 16:00:28.786 +08:00 [ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-10-30 16:00:28.787 +08:00 [INF] -----------------结束-----------------

2024-10-30 16:00:28.787 +08:00 [ERR] 程序发生异常：Object reference not set to an instance of an object.
2024-10-30 16:00:28.788 +08:00 [INF] ===========结束===========

2024-10-30 16:00:28.820 +08:00 [WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken)
2024-10-30 16:00:28.821 +08:00 [INF] 运行环境：Production
2024-10-30 16:00:28.822 +08:00 [INF] 应用目录：E:\desktop\bilitool\win-x64\

**Comment by Mtxgeek** [comment]
这个新提交的ls要怎么删除了 我发现了ERR 程序发生异常已经有人提交了

**Comment by Mtxgeek** [comment]
[ELAPSED] 00:00:17.2183941
2024-10-30 16:00:28.742 +08:00 [INF] 确认：true
2024-10-30 16:00:28.743 +08:00 [INF] -------结束-------

2024-10-30 16:00:28.748 +08:00 [INF] ---开始 浏览追番频道页10秒 ---
2024-10-30 16:00:28.755 +08:00 [ERR] 浏览追番频道页10秒失败，继续其他任务。失败信息:Sequence contains no matching element

2024-10-30 16:00:28.759 +08:00 [INF] -------------结束-------------

2024-10-30 16:00:28.764 +08:00 [INF] ---开始 浏览会员购页面10秒 ---
2024-10-30 16:00:28.765 +08:00 [ERR] 浏览会员购页面10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-10-30 16:00:28.765 +08:00 [INF] -------------结束-------------

2024-10-30 16:00:28.770 +08:00 [INF] ---开始 浏览装扮商城主页 ---
2024-10-30 16:00:28.771 +08:00 [ERR] 浏览装扮商城主页失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-10-30 16:00:28.771 +08:00 [INF] -----------结束-----------

2024-10-30 16:00:28.776 +08:00 [INF] ---开始 观看剧集内容 ---
2024-10-30 16:00:28.777 +08:00 [ERR] 观看剧集内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-10-30 16:00:28.778 +08:00 [INF] ---------结束---------

2024-10-30 16:00:28.781 +08:00 [INF] ---开始 购买单点付费影片（仅领取） ---
2024-10-30 16:00:28.782 +08:00 [ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-10-30 16:00:28.783 +08:00 [INF] ----------------结束----------------

2024-10-30 16:00:28.785 +08:00 [INF] ---开始 购买指定会员购商品（仅领取） ---
2024-10-30 16:00:28.786 +08:00 [ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

2024-10-30 16:00:28.787 +08:00 [INF] -----------------结束-----------------

2024-10-30 16:00:28.787 +08:00 [ERR] 程序发生异常：Object reference not set to an instance of an object.
2024-10-30 16:00:28.788 +08:00 [INF] ===========结束===========

2024-10-30 16:00:28.820 +08:00 [WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken)
2024-10-30 16:00:28.821 +08:00 [INF] 运行环境：Production
2024-10-30 16:00:28.822 +08:00 [INF] 应用目录：E:\desktop\bilitool\win-x64\

**Comment by ypq123456789** [comment]
我也是
