### ISSUE TITLE
【Bug】【青龙】除了bili天选时刻，其他都无法执行

### ISSUE THREAD

**Issue by cyxnzb** [RayWangQvQ/BiliBiliToolPro#801]
### 版本

BiliTool版本号：`2.1.1`

青龙版本号：`2.17.2`

### 确认

- [ ] 是的，我已搜索并确认，没有其他相同的议题
- [ ] 是的，我确认，已尝试升级bilitool到最新版，但未解决
- [ ] 是的，我确认，已尝试升级青龙到最新版，但未解决

### 服务器架构

- [ ] x64
- [ ] arm64
- [ ] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [ ] Windows
- [ ] macOS
- [ ] Linux
    - [ ] Debian
    - [ ] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - [ ] Centos
    - [ ] 其他（请在下面补充）

### 青龙容器类型

- [ ] Docker
- [ ] Podman
- [ ] 其他（请在下面补充）

### 青龙镜像

- [ ] whyour/qinglong:latest（Alpine）
- [ ] whyour/qinglong:debian（Debian）

### 选择的BiliTool运行模式

- [ ] dotnet
- [ ] bilitool

### 如果是青龙拉库相关bug，请贴出拉库方式截图

- [ ] 否

### 如果是缺失文件相关bug，请贴出容器内文件路径信息

- [ ] 否

### 问题描述

无法正常运行脚本

### 日志信息

<details>

```
## 开始执行... 2024-11-16 20:12:31

bilitool: 青龙repo目录: /ql/data/repo
bilitool: bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro
bilitool: 当前系统发行版本：alpine.3.20.3
bilitool: 当前系统：linux-musl
bilitool: 当前架构：x64
bilitool: 当前选择的运行方式：bilitool
bilitool: tag.txt记录的版本：2.1.1
bilitool: bilitool已安装
bilitool: 环境正常，本次无需安装
Failed to create CoreCLR, HRESULT: 0x8007FF0B
/ql/shell/otask.sh: line 252: pop_var_context: head of shell_variables not a function context
/ql/shell/otask.sh: line 286: pop_var_context: head of shell_variables not a function context
```

</details>

**Comment by xzh0** [comment]
+1 我也是这样

**Comment by cyxnzb** [comment]
2024年11月17日更新：
bili直播粉丝牌会触发风控
bili大会员大积分会提示：“失败信息:Sequence contains no matching element”、“Object reference not set to an instance of an object.”、“异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken)”
运行结束会抛出：“运行结束
/ql/data/config/task_before.sh: line 846: time_text: unbound variable
”

**Comment by qg46** [comment]
> 2024年11月17日更新： bili直播粉丝牌会触发风控 bili大会员大积分会提示：“失败信息:Sequence contains no matching element”、“Object reference not set to an instance of an object.”、“异常：System.NullReferenceException: Object reference not set to an instance of an object. at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken) at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken)” 运行结束会抛出：“运行结束 /ql/data/config/task_before.sh: line 846: time_text: unbound variable ”

wocao我也这样

**Comment by HHHm3** [comment]
蹲

**Comment by RayWangQvQ** [comment]
最新版本是否还是同样问题？

**Comment by HHHm3** [comment]
已经不搞这些了hh




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年2月16日(星期天) 晚上8:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RayWangQvQ/BiliBiliToolPro] 【Bug】【青龙】除了bili天选时刻，其他都无法执行 (Issue #801)












   
最新版本是否还是同样问题？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  RayWangQvQ left a comment (RayWangQvQ/BiliBiliToolPro#801)
 
最新版本是否还是同样问题？

**Comment by cyxnzb** [comment]
> 最新版本是否还是同样问题？

目前无
