### ISSUE TITLE
【Bug】【青龙】持续报错request was canceled due to the configured HttpClient

### ISSUE THREAD

**Issue by zy19970** [RayWangQvQ/BiliBiliToolPro#805]
### 版本

BiliTool版本号：`2.1.1`

青龙版本号：`2.17.12`

### 确认

- [-] 是的，我已搜索并确认，没有其他相同的议题
- [ ] 是的，我确认，已尝试升级bilitool到最新版，但未解决
- [ ] 是的，我确认，已尝试升级青龙到最新版，但未解决

### 服务器架构

- [-] x64
- [ ] arm64
- [ ] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [ ] Windows
- [ ] macOS
- [-] Linux
    - [ ] Debian
    - [-] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - [ ] Centos
    - [ ] 其他（请在下面补充）

### 青龙容器类型

- [-] Docker
- [ ] Podman
- [ ] 其他（请在下面补充）

### 青龙镜像

- [-] whyour/qinglong:latest（Alpine）
- [ ] whyour/qinglong:debian（Debian）

### 选择的BiliTool运行模式

- [-] dotnet
- [ ] bilitool

### 如果是青龙拉库相关bug，请贴出拉库方式截图

- [-] 否
- [ ] 是，截图如下

### 如果是缺失文件相关bug，请贴出容器内文件路径信息

- [-] 否
- [ ] 是，信息如下

查看方式参考文档：[提示文件不存在或路径异常怎么排查](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md#43-提示文件不存在或路径异常怎么排查)

BiliTool仓库文件路径：`<粘贴路径>`

脚本文件路径：`<粘贴路径>`

<这里贴截图>

### 问题描述

一直报同样错误。包括每日任务等....

### 日志信息

<details>

```
## 开始执行... 2024-11-29 14:14:43

bilitool: 青龙repo目录: /ql/data/repo
bilitool: bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro
bilitool: 当前系统发行版本：alpine.3.20.3
bilitool: 当前系统：linux-musl
bilitool: 当前架构：x64
bilitool: 当前选择的运行方式：dotnet
bilitool: 已安装dotnet，当前版本：6.0.136
bilitool: which dotnet: /usr/bin/dotnet
bilitool: 环境正常，本次无需安装
  ____               ____    _   _____           _  
 |  _ \ __ _ _   _  | __ ) _| |_|_   _|__   ___ | | 
 | |_) / _` | | | | |  _ \(_) (_) | |/ _ \ / _ \| | 
 |  _ < (_| | |_| | | |_) | | | | | | (_) | (_) | | 
 |_| \_\__,_|\__, | |____/|_|_|_| |_|\___/ \___/|_| 
             |___/                                  

[14:15:24 INF] BiliBiliToolPro 开始运行...

[14:15:24 INF] 【账号个数】1个

[14:15:24 INF] 【目标任务】LiveLottery
[14:15:24 INF] ######### 账号 1 #########

[14:15:25 INF] =====开始 天选时刻抽奖 =====

[14:15:25 INF] ---开始 打印用户信息 ---
[14:15:37 INF] 【会员类型】无
[14:15:37 INF] 【会员状态】无/过期
[14:15:37 INF] 【硬币余额】1434.1
[14:15:37 INF] ---------结束---------

[14:15:37 INF] ---开始 抽奖 ---
[14:16:09 INF] 【扫描分区】网游...

[14:17:49 ERR] [REQUEST]
GET /xlive/web-interface/v1/second/getList?platform=web&parent_area_id=2&area_id=0&sort_type=&page=1 HTTP/1.1
Referer: https://live.bilibili.com/
Origin: https://live.bilibili.com
Host: api.live.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[EXCEPTION]
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpRequestMessage request, Context context, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 32
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)

[ELAPSED] 00:01:40.0038365
[14:17:49 ERR] 程序发生异常：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
[14:17:49 INF] -----结束-----

[14:17:49 ERR] 程序发生异常：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
[14:17:49 INF] ===========结束===========

[14:17:49 WRN] 异常：System.Net.Http.HttpRequestException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpRequestMessage request, Context context, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 32
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(ApiRequestContext request)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   --- End of inner exception stack trace ---
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   at Ray.BiliBiliTool.DomainService.LiveDomainService.TianXuan() in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/LiveDomainService.cs:line 175
   at Ray.BiliBiliTool.Application.LiveLotteryTaskAppService.LotteryTianXuan() in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/LiveLotteryTaskAppService.cs:line 48
   at Ray.BiliBiliTool.Application.LiveLotteryTaskAppService.DoTaskAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/LiveLotteryTaskAppService.cs:line 35
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 194
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76
[14:17:49 INF] 运行环境：Production
[14:17:49 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[14:17:49 INF] 运行结束

## 执行结束... 2024-11-29 14:17:49  耗时 186 秒　　　　　
```

</details>

**Comment by RayWangQvQ** [comment]
请求超时了，确认下，浏览器请求阿B接口能通不
