### ISSUE TITLE
【Bug】运行过程中出现错误(已解决)

### ISSUE THREAD

**Issue by wanlongsj** [RayWangQvQ/BiliBiliToolPro#9]
版本号：（v0.0.1）
运行环境：（腾讯函数云,Actions,Win）

问题描述：（启动后到时间运行失败）

日志信息：<html>
<body>

System.Collections.Generic.KeyNotFoundException: The given key ',' was not present in the dictionary.
--
at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasks(String[] tasks) in /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 135

</body>
</html>

**Comment by wanlongsj** [comment]
已自行解决

**Comment by wanlongsj** [comment]
这个嘛....它自动部署不会删后面注释，然后我手动删除了awa













在 2022-02-18 14:02:39，"MaxwelsDonc" ***@***.***> 写道：

怎么解决的？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
